// ============================================================
// SECTION: Type Definitions
// ============================================================

interface TreeNode {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  branch: string;
  level: number;
  xp: number;
  status: 'mastered' | 'available' | 'locked';
  progress: number;
  completed: number;
  total: number;
  parent: string | null;
  children: string[];
  unlocked: boolean;
  visible: boolean;
  x: number;
  y: number;
  radius: number;
  color: string;
  glow: string;
  iconName: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  estimatedMinutes: number;
  tags: string[];
  prerequisites: string[];
}

// ============================================================
// SECTION: Biological Psychology Nodes
// ============================================================

export const biologicalNodes: TreeNode[] = [
  {
    id: 'biological',
    title: 'Biological Psychology',
    subtitle: 'Neuroscience and the Biology of Behavior',
    description: 'The study of the biological bases of psychological processes and behavior. Explores neural structures, neurotransmission, brain anatomy, endocrine systems, genetics, and the physiological mechanisms underlying sensation, emotion, and cognition.',
    branch: 'biological',
    level: 1,
    xp: 65,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: ['neurons', 'brain', 'endocrine-system', 'sleep', 'consciousness', 'plasticity', 'genetics', 'evolution'],
    unlocked: true,
    visible: true,
    x: 0,
    y: 0,
    radius: 44,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.35)',
    iconName: 'dna',
    difficulty: 'beginner',
    estimatedMinutes: 0,
    tags: ['neuroscience', 'biology', 'physiology'],
    prerequisites: ['psychology'],
  },
  {
    id: 'neurons',
    title: 'Neurons',
    subtitle: 'Fundamental Units of the Nervous System',
    description: 'Specialized cells that transmit electrical and chemical signals throughout the nervous system. The basic building blocks of the brain, spinal cord, and peripheral nerves, responsible for processing and communicating information.',
    branch: 'biological',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'biological',
    children: ['neuron-structure', 'action-potential', 'synapse', 'neurotransmitters', 'neural-communication', 'glial-cells'],
    unlocked: false,
    visible: true,
    x: -400,
    y: -280,
    radius: 34,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.25)',
    iconName: 'activity',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['cells', 'nervous-system', 'signaling'],
    prerequisites: ['biological'],
  },
  {
    id: 'neuron-structure',
    title: 'Neuron Structure',
    subtitle: 'Anatomy of a Nerve Cell',
    description: 'The structural components of neurons including the cell body (soma), dendrites that receive signals, the axon that transmits signals, and the axon terminals that communicate with other cells. Myelin sheaths insulate and speed transmission.',
    branch: 'biological',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurons',
    children: ['dendrites', 'axon', 'myelin-sheath'],
    unlocked: false,
    visible: true,
    x: -520,
    y: -400,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'microscope',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['anatomy', 'soma', 'dendrites'],
    prerequisites: ['neurons'],
  },
  {
    id: 'dendrites',
    title: 'Dendrites',
    subtitle: 'Signal Receiving Extensions',
    description: 'Branching extensions of a neuron that receive messages from other cells and conduct impulses toward the cell body. Their tree-like structure maximizes surface area for synaptic input and determines neuronal integration properties.',
    branch: 'biological',
    level: 4,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neuron-structure',
    children: [],
    unlocked: false,
    visible: true,
    x: -600,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'git-branch',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['input', 'branches', 'reception'],
    prerequisites: ['neuron-structure'],
  },
  {
    id: 'axon',
    title: 'Axon',
    subtitle: 'Signal Transmitting Fiber',
    description: 'The long, slender projection of a neuron that conducts electrical impulses away from the cell body toward other neurons, muscles, or glands. Can range from micrometers to over a meter in length in motor neurons.',
    branch: 'biological',
    level: 4,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neuron-structure',
    children: [],
    unlocked: false,
    visible: true,
    x: -520,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'arrow-right',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['output', 'transmission', 'fiber'],
    prerequisites: ['neuron-structure'],
  },
  {
    id: 'myelin-sheath',
    title: 'Myelin Sheath',
    subtitle: 'Insulating Neural Transmission',
    description: 'A fatty layer that wraps around axons, formed by glial cells, that insulates and speeds up the transmission of nerve impulses through saltatory conduction. Demyelination is characteristic of multiple sclerosis.',
    branch: 'biological',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neuron-structure',
    children: [],
    unlocked: false,
    visible: true,
    x: -440,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'shield',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['insulation', 'schwann', 'oligodendrocytes'],
    prerequisites: ['neuron-structure'],
  },
  {
    id: 'action-potential',
    title: 'Action Potential',
    subtitle: 'The Neural Impulse',
    description: 'A brief electrical charge that travels down an axon, generated by the movement of positively charged ions across the neuronal membrane. The all-or-none principle governs its firing, forming the basis of neural communication.',
    branch: 'biological',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurons',
    children: ['resting-potential', 'depolarization', 'refractory-period', 'all-or-none'],
    unlocked: false,
    visible: true,
    x: -400,
    y: -400,
    radius: 28,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'zap',
    difficulty: 'intermediate',
    estimatedMinutes: 40,
    tags: ['impulse', 'electrical', 'ions'],
    prerequisites: ['neurons'],
  },
  {
    id: 'resting-potential',
    title: 'Resting Potential',
    subtitle: 'The Neuron at Rest',
    description: 'The electrical potential across the neuronal membrane when the neuron is not firing, typically around -70 millivolts. Maintained by the sodium-potassium pump and selective ion permeability, creating the electrochemical gradient necessary for signaling.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'action-potential',
    children: [],
    unlocked: false,
    visible: true,
    x: -480,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'battery-low',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['membrane', 'potential', 'ions'],
    prerequisites: ['action-potential'],
  },
  {
    id: 'depolarization',
    title: 'Depolarization',
    subtitle: 'Reversing Membrane Potential',
    description: 'The process during which the inside of the neuron becomes less negative relative to the outside, caused by the influx of sodium ions through voltage-gated channels. The rising phase of the action potential.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'action-potential',
    children: [],
    unlocked: false,
    visible: true,
    x: -400,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'trending-up',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['sodium', 'influx', 'rising-phase'],
    prerequisites: ['action-potential'],
  },
  {
    id: 'refractory-period',
    title: 'Refractory Period',
    subtitle: 'Temporary Recovery After Firing',
    description: 'A brief period after an action potential during which a new action potential cannot be elicited. The absolute refractory period prevents backward propagation, while the relative refractory period requires stronger stimulation.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'action-potential',
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'timer-off',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['recovery', 'absolute', 'relative'],
    prerequisites: ['action-potential'],
  },
  {
    id: 'all-or-none',
    title: 'All-or-None Principle',
    subtitle: 'Binary Neural Firing',
    description: 'The principle stating that a neuron either fires completely at maximum strength or does not fire at all. The intensity of a stimulus is coded by the frequency of action potentials, not their amplitude.',
    branch: 'biological',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'action-potential',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'toggle-right',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['binary', 'frequency', 'coding'],
    prerequisites: ['action-potential'],
  },
  {
    id: 'synapse',
    title: 'Synapse',
    subtitle: 'Junction Between Neurons',
    description: 'The microscopic gap between the axon terminal of one neuron and the dendrite or cell body of another. The site where neurotransmitters are released to transmit signals from one neuron to the next.',
    branch: 'biological',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurons',
    children: ['synaptic-transmission', 'synaptic-cleft', 'receptors', 'excitatory-inhibitory'],
    unlocked: false,
    visible: true,
    x: -280,
    y: -400,
    radius: 28,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'git-merge',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['junction', 'gap', 'transmission'],
    prerequisites: ['neurons'],
  },
  {
    id: 'synaptic-transmission',
    title: 'Synaptic Transmission',
    subtitle: 'Chemical Signaling Across Synapses',
    description: 'The process by which a nerve impulse passes from one neuron to another through the release of neurotransmitters into the synaptic cleft, binding to receptors on the postsynaptic membrane.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'synapse',
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'arrow-left-right',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['chemical', 'release', 'binding'],
    prerequisites: ['synapse'],
  },
  {
    id: 'synaptic-cleft',
    title: 'Synaptic Cleft',
    subtitle: 'The Gap Between Neurons',
    description: 'The microscopic space between the presynaptic and postsynaptic membranes into which neurotransmitters are released. Typically 20-40 nanometers wide, it is the site of chemical neurotransmission.',
    branch: 'biological',
    level: 4,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'synapse',
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'gap',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['space', 'nanometers', 'diffusion'],
    prerequisites: ['synapse'],
  },
  {
    id: 'receptors',
    title: 'Neurotransmitter Receptors',
    subtitle: 'Proteins That Bind Chemical Messengers',
    description: 'Specialized protein molecules on the postsynaptic membrane that bind to specific neurotransmitters, triggering ion channel opening or intracellular signaling cascades. Classified as ionotropic or metabotropic.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'synapse',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'target',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['proteins', 'binding', 'ionotropic'],
    prerequisites: ['synapse'],
  },
  {
    id: 'excitatory-inhibitory',
    title: 'Excitatory and Inhibitory Signals',
    subtitle: 'Push and Pull of Neural Communication',
    description: 'The dual nature of synaptic transmission where excitatory postsynaptic potentials depolarize the membrane and increase firing probability, while inhibitory postsynaptic potentials hyperpolarize and decrease firing probability.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'synapse',
    children: [],
    unlocked: false,
    visible: true,
    x: -120,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'scale',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['epsp', 'ipsp', 'integration'],
    prerequisites: ['synapse'],
  },
  {
    id: 'neurotransmitters',
    title: 'Neurotransmitters',
    subtitle: 'Chemical Messengers of the Brain',
    description: 'Chemical substances released by neurons that transmit signals across synapses to target cells. They regulate mood, arousal, memory, motor control, and virtually every psychological function.',
    branch: 'biological',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurons',
    children: ['dopamine', 'serotonin', 'acetylcholine', 'gaba', 'glutamate', 'norepinephrine', 'endorphins'],
    unlocked: false,
    visible: true,
    x: -160,
    y: -400,
    radius: 28,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'flask-conical',
    difficulty: 'intermediate',
    estimatedMinutes: 45,
    tags: ['chemicals', 'messengers', 'signaling'],
    prerequisites: ['neurons'],
  },
  {
    id: 'dopamine',
    title: 'Dopamine',
    subtitle: 'Reward, Motivation, and Movement',
    description: 'A monoamine neurotransmitter involved in reward processing, motivation, motor control, and pleasure. Dysregulation is implicated in Parkinson\'s disease, schizophrenia, and addiction. Projections from the ventral tegmental area and substantia nigra.',
    branch: 'biological',
    level: 4,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurotransmitters',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'trophy',
    difficulty: 'advanced',
    estimatedMinutes: 40,
    tags: ['reward', 'motivation', 'parkinsons'],
    prerequisites: ['neurotransmitters'],
  },
  {
    id: 'serotonin',
    title: 'Serotonin',
    subtitle: 'Mood, Sleep, and Appetite Regulation',
    description: 'A monoamine neurotransmitter primarily produced in the raphe nuclei of the brainstem. Regulates mood, sleep, appetite, and pain perception. Imbalances are linked to depression, anxiety, and obsessive-compulsive disorder.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurotransmitters',
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'smile',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['mood', 'sleep', 'depression'],
    prerequisites: ['neurotransmitters'],
  },
  {
    id: 'acetylcholine',
    title: 'Acetylcholine',
    subtitle: 'Learning, Memory, and Muscle Contraction',
    description: 'The first neurotransmitter discovered, involved in muscle contraction at the neuromuscular junction, and critical for attention, learning, and memory in the central nervous system. Degeneration is characteristic of Alzheimer\'s disease.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurotransmitters',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'brain',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['memory', 'alzheimers', 'muscle'],
    prerequisites: ['neurotransmitters'],
  },
  {
    id: 'gaba',
    title: 'GABA',
    subtitle: 'Primary Inhibitory Neurotransmitter',
    description: 'Gamma-aminobutyric acid, the main inhibitory neurotransmitter in the central nervous system. Reduces neuronal excitability throughout the nervous system and is the target of benzodiazepines and alcohol.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurotransmitters',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'shield-check',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['inhibitory', 'anxiety', 'calm'],
    prerequisites: ['neurotransmitters'],
  },
  {
    id: 'glutamate',
    title: 'Glutamate',
    subtitle: 'Primary Excitatory Neurotransmitter',
    description: 'The most abundant excitatory neurotransmitter in the vertebrate nervous system. Essential for synaptic plasticity, learning, and memory. Excessive glutamate activity causes excitotoxicity and neuronal damage.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurotransmitters',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'zap',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['excitatory', 'plasticity', 'learning'],
    prerequisites: ['neurotransmitters'],
  },
  {
    id: 'norepinephrine',
    title: 'Norepinephrine',
    subtitle: 'Arousal, Alertness, and Stress Response',
    description: 'A catecholamine neurotransmitter and hormone involved in the fight-or-flight response, arousal, and attention. Produced primarily in the locus coeruleus, it modulates vigilance and the sympathetic nervous system.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurotransmitters',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'alert-triangle',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['arousal', 'stress', 'locus-coeruleus'],
    prerequisites: ['neurotransmitters'],
  },
  {
    id: 'endorphins',
    title: 'Endorphins',
    subtitle: 'Natural Painkillers and Euphoria',
    description: 'Endogenous opioid peptides produced by the central nervous system and pituitary gland that function as natural pain relievers and produce feelings of euphoria. Released during exercise, stress, and pleasurable activities.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurotransmitters',
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: -480,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'heart',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['opioids', 'pain', 'euphoria'],
    prerequisites: ['neurotransmitters'],
  },
  {
    id: 'neural-communication',
    title: 'Neural Communication',
    subtitle: 'How Neurons Talk to Each Other',
    description: 'The fundamental process by which neurons transmit information through electrical signals within cells and chemical signals between cells. Involves integration of inputs, action potential generation, and synaptic transmission.',
    branch: 'biological',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurons',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -400,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'radio',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['signaling', 'integration', 'networks'],
    prerequisites: ['neurons'],
  },
  {
    id: 'glial-cells',
    title: 'Glial Cells',
    subtitle: 'Support Cells of the Nervous System',
    description: 'Non-neuronal cells that provide support, protection, and nutrition to neurons. Include astrocytes, oligodendrocytes, microglia, and Schwann cells. Once thought merely supportive, they are now recognized as active participants in neural signaling.',
    branch: 'biological',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neurons',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -400,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'shield',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['astrocytes', 'support', 'maintenance'],
    prerequisites: ['neurons'],
  },
  {
    id: 'brain',
    title: 'Brain',
    subtitle: 'The Central Organ of the Nervous System',
    description: 'The complex organ that serves as the center of the nervous system in all vertebrates. Controls thought, memory, emotion, touch, motor skills, vision, breathing, temperature, hunger, and every process that regulates the body.',
    branch: 'biological',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'biological',
    children: ['cerebrum', 'cerebellum', 'brain-stem', 'limbic-system', 'frontal-lobe', 'temporal-lobe', 'occipital-lobe', 'parietal-lobe'],
    unlocked: false,
    visible: true,
    x: -200,
    y: -120,
    radius: 36,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.25)',
    iconName: 'brain',
    difficulty: 'beginner',
    estimatedMinutes: 50,
    tags: ['anatomy', 'structure', 'organization'],
    prerequisites: ['biological'],
  },
  {
    id: 'cerebrum',
    title: 'Cerebrum',
    subtitle: 'Largest Part of the Brain',
    description: 'The largest and most developed part of the human brain, divided into two hemispheres and four lobes. Responsible for higher brain functions including thought, action, sensory processing, and conscious experience.',
    branch: 'biological',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain',
    children: ['cerebral-cortex', 'corpus-callosum', 'hemispheric-lateralization'],
    unlocked: false,
    visible: true,
    x: -360,
    y: -240,
    radius: 28,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'circle',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['hemispheres', 'cortex', 'higher-functions'],
    prerequisites: ['brain'],
  },
  {
    id: 'cerebral-cortex',
    title: 'Cerebral Cortex',
    subtitle: 'Outer Layer of Neural Tissue',
    description: 'The outermost layer of the cerebrum, consisting of folded gray matter responsible for higher-order brain functions. The folds increase surface area and are organized into six layers with distinct cellular compositions.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'cerebrum',
    children: [],
    unlocked: false,
    visible: true,
    x: -440,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'layers',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['gray-matter', 'folds', 'layers'],
    prerequisites: ['cerebrum'],
  },
  {
    id: 'corpus-callosum',
    title: 'Corpus Callosum',
    subtitle: 'Bridge Between Hemispheres',
    description: 'The thick band of nerve fibers connecting the left and right cerebral hemispheres, enabling communication and integration of information between the two sides of the brain. Severed in split-brain patients for epilepsy treatment.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'cerebrum',
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'link',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['hemispheres', 'communication', 'split-brain'],
    prerequisites: ['cerebrum'],
  },
  {
    id: 'hemispheric-lateralization',
    title: 'Hemispheric Lateralization',
    subtitle: 'Specialized Functions by Hemisphere',
    description: 'The tendency for some neural functions or cognitive processes to be specialized to one side of the brain. Language is typically left-lateralized, while spatial processing is often right-lateralized, though the brain is highly interconnected.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'cerebrum',
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'split',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['left-brain', 'right-brain', 'specialization'],
    prerequisites: ['cerebrum'],
  },
  {
    id: 'cerebellum',
    title: 'Cerebellum',
    subtitle: 'Coordination and Motor Control',
    description: 'A major structure of the hindbrain located at the back of the brain, primarily involved in motor control, coordination, precision, and timing. Also contributes to cognitive functions including attention and language.',
    branch: 'biological',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain',
    children: ['motor-learning', 'balance'],
    unlocked: false,
    visible: true,
    x: -240,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'rotate-ccw',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['coordination', 'motor', 'timing'],
    prerequisites: ['brain'],
  },
  {
    id: 'motor-learning',
    title: 'Motor Learning',
    subtitle: 'Acquiring Movement Skills',
    description: 'The process of improving motor skills through practice and experience, heavily dependent on the cerebellum and basal ganglia. Involves procedural memory and the automation of movement sequences.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'cerebellum',
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'dumbbell',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['skills', 'practice', 'procedural'],
    prerequisites: ['cerebellum'],
  },
  {
    id: 'balance',
    title: 'Balance and Equilibrium',
    subtitle: 'Maintaining Postural Stability',
    description: 'The cerebellar and vestibular system functions that maintain body posture and equilibrium during movement and rest. Integrates visual, proprioceptive, and vestibular information for spatial orientation.',
    branch: 'biological',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'cerebellum',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'scale',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['posture', 'vestibular', 'stability'],
    prerequisites: ['cerebellum'],
  },
  {
    id: 'brain-stem',
    title: 'Brain Stem',
    subtitle: 'Vital Connection Between Brain and Body',
    description: 'The posterior part of the brain, adjoining and structurally continuous with the spinal cord. Includes the midbrain, pons, and medulla oblongata, controlling vital functions such as breathing, heart rate, and arousal.',
    branch: 'biological',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain',
    children: ['medulla-oblongata', 'pons', 'midbrain', 'reticular-formation'],
    unlocked: false,
    visible: true,
    x: -120,
    y: -240,
    radius: 28,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'activity',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['vital', 'connection', 'arousal'],
    prerequisites: ['brain'],
  },
  {
    id: 'medulla-oblongata',
    title: 'Medulla Oblongata',
    subtitle: 'Control Center for Vital Functions',
    description: 'The lowest part of the brainstem, continuous with the spinal cord, controlling autonomic functions including breathing, heart rate, blood pressure, and reflexes such as vomiting, coughing, and sneezing.',
    branch: 'biological',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain-stem',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'heart-pulse',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['breathing', 'heart-rate', 'reflexes'],
    prerequisites: ['brain-stem'],
  },
  {
    id: 'pons',
    title: 'Pons',
    subtitle: 'Bridge and Relay Station',
    description: 'A structure on the brain stem that relays signals between the cerebrum and cerebellum, and plays a role in sleep, respiration, swallowing, bladder control, hearing, equilibrium, taste, eye movement, facial expressions, and posture.',
    branch: 'biological',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain-stem',
    children: [],
    unlocked: false,
    visible: true,
    x: -120,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'arrow-left-right',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['relay', 'sleep', 'facial'],
    prerequisites: ['brain-stem'],
  },
  {
    id: 'midbrain',
    title: 'Midbrain',
    subtitle: 'Sensory and Motor Integration',
    description: 'The uppermost portion of the brainstem, involved in functions such as vision, hearing, motor control, sleep-wake cycles, alertness, and temperature regulation. Contains the superior and inferior colliculi.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain-stem',
    children: [],
    unlocked: false,
    visible: true,
    x: -40,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'eye',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['vision', 'hearing', 'alertness'],
    prerequisites: ['brain-stem'],
  },
  {
    id: 'reticular-formation',
    title: 'Reticular Formation',
    subtitle: 'Arousal and Alertness Network',
    description: 'A diffuse network of neurons in the brainstem that projects to the cortex and regulates wakefulness, arousal, and attention. Damage can result in coma or persistent vegetative state.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain-stem',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'radio',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['arousal', 'wakefulness', 'coma'],
    prerequisites: ['brain-stem'],
  },
  {
    id: 'limbic-system',
    title: 'Limbic System',
    subtitle: 'Emotion, Memory, and Motivation',
    description: 'A set of brain structures including the hippocampus, amygdala, hypothalamus, and cingulate cortex that support emotion, behavior, motivation, long-term memory, and olfaction. Often called the emotional brain.',
    branch: 'biological',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain',
    children: ['hypothalamus', 'amygdala', 'hippocampus', 'cingulate-cortex'],
    unlocked: false,
    visible: true,
    x: 0,
    y: -240,
    radius: 28,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'heart',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['emotion', 'motivation', 'memory'],
    prerequisites: ['brain'],
  },
  {
    id: 'hypothalamus',
    title: 'Hypothalamus',
    subtitle: 'Master Regulator of Homeostasis',
    description: 'A small region near the base of the brain that plays a crucial role in hormone production, temperature regulation, hunger, thirst, sleep, emotional behavior, and the regulation of the autonomic nervous system.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'limbic-system',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -320,
    radius: 22,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'thermometer',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['homeostasis', 'hormones', 'hunger'],
    prerequisites: ['limbic-system'],
  },
  {
    id: 'amygdala',
    title: 'Amygdala',
    subtitle: 'Fear Processing and Emotional Memory',
    description: 'Almond-shaped nuclei in the temporal lobes involved in processing emotions, especially fear and threat detection. Critical for emotional learning, memory modulation, and social and sexual behavior.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'limbic-system',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -320,
    radius: 22,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'alert-circle',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['fear', 'emotion', 'threat'],
    prerequisites: ['limbic-system'],
  },
  {
    id: 'hippocampus',
    title: 'Hippocampus',
    subtitle: 'Memory Formation and Spatial Navigation',
    description: 'A seahorse-shaped structure in the medial temporal lobe essential for the formation of new explicit memories and spatial navigation. Damage results in anterograde amnesia as famously demonstrated by patient H.M.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'limbic-system',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -320,
    radius: 22,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'map-pin',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['memory', 'spatial', 'hm'],
    prerequisites: ['limbic-system'],
  },
  {
    id: 'cingulate-cortex',
    title: 'Cingulate Cortex',
    subtitle: 'Emotion Regulation and Pain Processing',
    description: 'A region of the brain surrounding the corpus callosum involved in emotion formation and processing, learning, memory, and pain perception. The anterior cingulate is particularly important for error detection and conflict monitoring.',
    branch: 'biological',
    level: 4,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'limbic-system',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -320,
    radius: 22,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'shield',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['emotion', 'pain', 'conflict'],
    prerequisites: ['limbic-system'],
  },
  {
    id: 'frontal-lobe',
    title: 'Frontal Lobe',
    subtitle: 'Executive Functions and Personality',
    description: 'The largest lobe of the cerebral cortex, located at the front of the brain. Responsible for executive functions, decision-making, planning, personality expression, motor control, and aspects of language production.',
    branch: 'biological',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain',
    children: ['prefrontal-cortex', 'motor-cortex', 'broca-area', 'phineas-gage'],
    unlocked: false,
    visible: true,
    x: 80,
    y: -240,
    radius: 28,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'brain-circuit',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['executive', 'planning', 'personality'],
    prerequisites: ['brain'],
  },
  {
    id: 'prefrontal-cortex',
    title: 'Prefrontal Cortex',
    subtitle: 'Highest Level of Cognitive Control',
    description: 'The anterior part of the frontal lobes responsible for executive functions, working memory, decision-making, social behavior, and personality expression. Last brain region to mature, continuing development into the mid-20s.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'frontal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'crown',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['executive', 'control', 'development'],
    prerequisites: ['frontal-lobe'],
  },
  {
    id: 'motor-cortex',
    title: 'Motor Cortex',
    subtitle: 'Voluntary Movement Control',
    description: 'The region of the cerebral cortex involved in the planning, control, and execution of voluntary movements. Located in the posterior frontal lobe, it contains a somatotopic map of the body known as the motor homunculus.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'frontal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'move',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['movement', 'homunculus', 'voluntary'],
    prerequisites: ['frontal-lobe'],
  },
  {
    id: 'broca-area',
    title: 'Broca\'s Area',
    subtitle: 'Speech Production Center',
    description: 'A region in the frontal lobe of the dominant hemisphere, usually the left, involved in speech production and language processing. Damage causes Broca\'s aphasia, characterized by non-fluent, effortful speech with preserved comprehension.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'frontal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'mic',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['speech', 'language', 'aphasia'],
    prerequisites: ['frontal-lobe'],
  },
  {
    id: 'phineas-gage',
    title: 'Phineas Gage Case',
    subtitle: 'Frontal Lobe and Personality',
    description: 'The famous 1848 case of a railroad worker who survived an iron rod through his frontal lobes, resulting in dramatic personality changes. Provided early evidence for the role of the frontal cortex in personality and social behavior.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'frontal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'user',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['case-study', 'personality', 'history'],
    prerequisites: ['frontal-lobe'],
  },
  {
    id: 'temporal-lobe',
    title: 'Temporal Lobe',
    subtitle: 'Hearing, Memory, and Language',
    description: 'A region of the cerebral cortex located beneath the lateral fissure on both cerebral hemispheres. Involved in auditory perception, memory acquisition, language comprehension, and high-level visual processing of faces and scenes.',
    branch: 'biological',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain',
    children: ['auditory-cortex', 'wernicke-area', 'fusiform-face-area'],
    unlocked: false,
    visible: true,
    x: 160,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'ear',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['hearing', 'memory', 'language'],
    prerequisites: ['brain'],
  },
  {
    id: 'auditory-cortex',
    title: 'Auditory Cortex',
    subtitle: 'Sound Processing Center',
    description: 'The region of the temporal lobe that processes auditory information. Located in the superior temporal gyrus, it performs basic and higher-level sound processing including pitch, loudness, and location discrimination.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'temporal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'volume-2',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['sound', 'hearing', 'processing'],
    prerequisites: ['temporal-lobe'],
  },
  {
    id: 'wernicke-area',
    title: 'Wernicke\'s Area',
    subtitle: 'Language Comprehension Center',
    description: 'A region in the posterior superior temporal gyrus, usually in the left hemisphere, critical for language comprehension. Damage causes Wernicke\'s aphasia, characterized by fluent but meaningless speech and poor comprehension.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'temporal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'message-circle',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['comprehension', 'language', 'aphasia'],
    prerequisites: ['temporal-lobe'],
  },
  {
    id: 'fusiform-face-area',
    title: 'Fusiform Face Area',
    subtitle: 'Specialized Face Processing',
    description: 'A region in the fusiform gyrus of the temporal lobe that is selectively activated by viewing faces. Damage can cause prosopagnosia, the inability to recognize familiar faces despite intact vision and intellect.',
    branch: 'biological',
    level: 4,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'temporal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'user-check',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['faces', 'prosopagnosia', 'recognition'],
    prerequisites: ['temporal-lobe'],
  },
  {
    id: 'occipital-lobe',
    title: 'Occipital Lobe',
    subtitle: 'Visual Processing Center',
    description: 'The smallest of the four lobes of the cerebral cortex, located at the back of the brain. The primary visual cortex and surrounding association areas process visual information from the retina, enabling sight and visual interpretation.',
    branch: 'biological',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain',
    children: ['primary-visual-cortex', 'visual-association-areas'],
    unlocked: false,
    visible: true,
    x: 240,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'eye',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['vision', 'sight', 'processing'],
    prerequisites: ['brain'],
  },
  {
    id: 'primary-visual-cortex',
    title: 'Primary Visual Cortex',
    subtitle: 'V1 and Basic Visual Processing',
    description: 'Also known as V1 or striate cortex, the region in the occipital lobe that receives direct input from the retina via the thalamus. Processes basic visual features such as orientation, spatial frequency, and color.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'occipital-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'scan-eye',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['v1', 'features', 'striate'],
    prerequisites: ['occipital-lobe'],
  },
  {
    id: 'visual-association-areas',
    title: 'Visual Association Areas',
    subtitle: 'Higher-Order Visual Processing',
    description: 'Regions surrounding the primary visual cortex that process complex visual information including object recognition, motion perception, and spatial relationships. Damage can cause visual agnosia or blindsight.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'occipital-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'scan',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['objects', 'motion', 'agnosia'],
    prerequisites: ['occipital-lobe'],
  },
  {
    id: 'parietal-lobe',
    title: 'Parietal Lobe',
    subtitle: 'Spatial Processing and Integration',
    description: 'A region of the cerebral cortex located between the frontal and occipital lobes. Involved in processing somatosensory information, spatial awareness, navigation, and the integration of sensory information from different modalities.',
    branch: 'biological',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'brain',
    children: ['somatosensory-cortex', 'spatial-neglect'],
    unlocked: false,
    visible: true,
    x: 320,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'map',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['touch', 'space', 'integration'],
    prerequisites: ['brain'],
  },
  {
    id: 'somatosensory-cortex',
    title: 'Somatosensory Cortex',
    subtitle: 'Touch and Body Sensation Processing',
    description: 'A region of the parietal lobe that processes tactile and proprioceptive information from the body. Contains a somatotopic map called the sensory homunculus, with disproportionate representation of sensitive body parts.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'parietal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'hand',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['touch', 'homunculus', 'body'],
    prerequisites: ['parietal-lobe'],
  },
  {
    id: 'spatial-neglect',
    title: 'Spatial Neglect',
    subtitle: 'Ignoring One Side of Space',
    description: 'A neurological condition, often following right parietal damage, in which patients fail to attend to or acknowledge stimuli on the contralesional side of space. Demonstrates the parietal lobe\'s role in spatial attention.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'parietal-lobe',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'eye-off',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['attention', 'damage', 'hemispatial'],
    prerequisites: ['parietal-lobe'],
  },
  {
    id: 'endocrine-system',
    title: 'Endocrine System',
    subtitle: 'Hormonal Regulation of Behavior',
    description: 'The system of glands that secrete hormones directly into the bloodstream to regulate physiological processes, growth, metabolism, reproduction, mood, and stress response. Works in concert with the nervous system.',
    branch: 'biological',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'biological',
    children: ['hormones', 'pituitary-gland', 'adrenal-glands', 'thyroid', 'stress-response'],
    unlocked: false,
    visible: true,
    x: 0,
    y: -120,
    radius: 34,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.25)',
    iconName: 'flask-conical',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['glands', 'hormones', 'regulation'],
    prerequisites: ['biological'],
  },
  {
    id: 'hormones',
    title: 'Hormones',
    subtitle: 'Chemical Messengers of the Body',
    description: 'Chemical substances produced by endocrine glands that travel through the bloodstream to target organs and tissues, regulating metabolism, growth, development, reproduction, mood, and stress responses.',
    branch: 'biological',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'endocrine-system',
    children: ['cortisol', 'adrenaline', 'oxytocin', 'testosterone', 'estrogen'],
    unlocked: false,
    visible: true,
    x: -120,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'droplets',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['chemicals', 'bloodstream', 'regulation'],
    prerequisites: ['endocrine-system'],
  },
  {
    id: 'cortisol',
    title: 'Cortisol',
    subtitle: 'Stress Hormone',
    description: 'A glucocorticoid hormone produced by the adrenal cortex in response to stress. Regulates metabolism, immune response, and the sleep-wake cycle. Chronic elevation is associated with depression, anxiety, and impaired memory.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'hormones',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'alert-triangle',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['stress', 'glucocorticoid', 'metabolism'],
    prerequisites: ['hormones'],
  },
  {
    id: 'adrenaline',
    title: 'Adrenaline',
    subtitle: 'Fight-or-Flight Hormone',
    description: 'Also known as epinephrine, a hormone and neurotransmitter released by the adrenal medulla in response to stress or danger. Prepares the body for fight-or-flight by increasing heart rate, blood pressure, and glucose availability.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'hormones',
    children: [],
    unlocked: false,
    visible: true,
    x: -120,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'zap',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['epinephrine', 'stress', 'arousal'],
    prerequisites: ['hormones'],
  },
  {
    id: 'oxytocin',
    title: 'Oxytocin',
    subtitle: 'Bonding and Trust Hormone',
    description: 'A hormone and neuropeptide produced in the hypothalamus and released by the posterior pituitary. Involved in social bonding, trust, sexual reproduction, childbirth, and lactation. Often called the love hormone.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'hormones',
    children: [],
    unlocked: false,
    visible: true,
    x: -40,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'heart',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['bonding', 'trust', 'social'],
    prerequisites: ['hormones'],
  },
  {
    id: 'testosterone',
    title: 'Testosterone',
    subtitle: 'Primary Male Sex Hormone',
    description: 'An androgen hormone produced primarily in the testes and in smaller amounts in the ovaries and adrenal glands. Regulates sexual development, muscle mass, bone density, and influences aggression and dominance behavior.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'hormones',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'male',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['androgen', 'sex', 'aggression'],
    prerequisites: ['hormones'],
  },
  {
    id: 'estrogen',
    title: 'Estrogen',
    subtitle: 'Primary Female Sex Hormone',
    description: 'A group of steroid hormones produced primarily in the ovaries that regulate the menstrual cycle, reproductive system, and secondary sexual characteristics. Also influences mood, cognition, and bone health.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'hormones',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'female',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['steroid', 'reproduction', 'mood'],
    prerequisites: ['hormones'],
  },
  {
    id: 'pituitary-gland',
    title: 'Pituitary Gland',
    subtitle: 'Master Gland of the Endocrine System',
    description: 'A pea-sized gland at the base of the brain that secretes hormones regulating growth, reproduction, metabolism, and stress response. Controlled by the hypothalamus, it influences other endocrine glands throughout the body.',
    branch: 'biological',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'endocrine-system',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'circle-dot',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['master', 'growth', 'regulation'],
    prerequisites: ['endocrine-system'],
  },
  {
    id: 'adrenal-glands',
    title: 'Adrenal Glands',
    subtitle: 'Stress Response and Metabolism',
    description: 'Triangular glands located on top of the kidneys that produce hormones including cortisol, aldosterone, and adrenaline. The adrenal medulla releases catecholamines during stress; the cortex produces steroid hormones.',
    branch: 'biological',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'endocrine-system',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'triangle',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['kidneys', 'stress', 'steroids'],
    prerequisites: ['endocrine-system'],
  },
  {
    id: 'thyroid',
        title: 'Thyroid Gland',
    subtitle: 'Metabolism and Energy Regulation',
    description: 'A butterfly-shaped gland in the neck that produces hormones regulating metabolism, growth, and development. Thyroid hormones influence virtually every organ system and are critical for normal brain development.',
    branch: 'biological',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'endocrine-system',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'activity',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['metabolism', 'energy', 'development'],
    prerequisites: ['endocrine-system'],
  },
  {
    id: 'stress-response',
    title: 'Stress Response',
    subtitle: 'Physiological Reaction to Threat',
    description: 'The body\'s coordinated response to perceived threats, involving the sympathetic nervous system, HPA axis, and the release of stress hormones. Acute stress enhances performance; chronic stress damages health and cognition.',
    branch: 'biological',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'endocrine-system',
    children: ['hpa-axis', 'fight-or-flight', 'tend-and-befriend'],
    unlocked: false,
    visible: true,
    x: 240,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'shield-alert',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['threat', 'cortisol', 'adaptation'],
    prerequisites: ['endocrine-system'],
  },
  {
    id: 'hpa-axis',
    title: 'HPA Axis',
    subtitle: 'Hypothalamic-Pituitary-Adrenal Cascade',
    description: 'The neuroendocrine system that regulates stress response through the hypothalamus, pituitary gland, and adrenal glands. Dysregulation is implicated in depression, PTSD, and chronic fatigue syndrome.',
    branch: 'biological',
    level: 4,
    xp: 200,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'stress-response',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'git-merge',
    difficulty: 'advanced',
    estimatedMinutes: 40,
    tags: ['cascade', 'feedback', 'regulation'],
    prerequisites: ['stress-response'],
  },
  {
    id: 'fight-or-flight',
    title: 'Fight-or-Flight Response',
    subtitle: 'Sympathetic Activation for Survival',
    description: 'An acute stress response triggered by the sympathetic nervous system, preparing the body to confront or flee from danger. Involves increased heart rate, dilated pupils, and redirected blood flow to muscles.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'stress-response',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'sword',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['cannon', 'sympathetic', 'survival'],
    prerequisites: ['stress-response'],
  },
  {
    id: 'tend-and-befriend',
    title: 'Tend-and-Befriend Response',
    subtitle: 'Social Bonding Under Stress',
    description: 'A stress response pattern proposed by Shelley Taylor, primarily observed in females, characterized by nurturing behaviors and social affiliation rather than fight-or-flight. Mediated by oxytocin and estrogen.',
    branch: 'biological',
    level: 4,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'stress-response',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'heart-handshake',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['taylor', 'oxytocin', 'social'],
    prerequisites: ['stress-response'],
  },
  {
    id: 'sleep',
    title: 'Sleep',
    subtitle: 'Restorative Neural State',
    description: 'A naturally recurring state of altered consciousness characterized by reduced sensory activity, inhibited muscle tone, and reduced interactions with the environment. Essential for memory consolidation, immune function, and metabolic health.',
    branch: 'biological',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'biological',
    children: ['sleep-stages', 'circadian-rhythm', 'dreams', 'sleep-disorders', 'sleep-memory'],
    unlocked: false,
    visible: true,
    x: 200,
    y: -120,
    radius: 34,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.25)',
    iconName: 'moon',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['rest', 'cycles', 'restoration'],
    prerequisites: ['biological'],
  },
  {
    id: 'sleep-stages',
    title: 'Sleep Stages',
    subtitle: 'Cycling Through the Night',
    description: 'The progression through distinct phases of sleep including NREM stages 1-3 and REM sleep, cycling approximately every 90 minutes. Each stage has characteristic brain wave patterns, muscle tone, and physiological signatures.',
    branch: 'biological',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep',
    children: ['nrem-sleep', 'rem-sleep', 'slow-wave-sleep'],
    unlocked: false,
    visible: true,
    x: 120,
    y: -240,
    radius: 28,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'layers',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['nrem', 'rem', 'cycles'],
    prerequisites: ['sleep'],
  },
  {
    id: 'nrem-sleep',
    title: 'NREM Sleep',
    subtitle: 'Quiet and Restorative Sleep',
    description: 'Non-rapid eye movement sleep comprising stages 1 through 3, characterized by decreasing brain activity, slower heart rate, and reduced body temperature. Stage 3 slow-wave sleep is critical for physical restoration and growth hormone release.',
    branch: 'biological',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep-stages',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'minus',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['quiet', 'restoration', 'growth'],
    prerequisites: ['sleep-stages'],
  },
  {
    id: 'rem-sleep',
    title: 'REM Sleep',
    subtitle: 'Active Dreaming Sleep',
    description: 'Rapid eye movement sleep characterized by high brain activity, vivid dreaming, muscle atonia, and irregular breathing and heart rate. Essential for emotional regulation, memory consolidation, and creative problem-solving.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep-stages',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'eye',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['dreaming', 'atonia', 'consolidation'],
    prerequisites: ['sleep-stages'],
  },
  {
    id: 'slow-wave-sleep',
    title: 'Slow-Wave Sleep',
    subtitle: 'Deep Restorative Sleep',
    description: 'The deepest stage of NREM sleep characterized by high-amplitude delta waves. Critical for physical restoration, immune function, and the glymphatic clearance of metabolic waste from the brain.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep-stages',
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'waves',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['delta', 'deep', 'clearance'],
    prerequisites: ['sleep-stages'],
  },
  {
    id: 'circadian-rhythm',
    title: 'Circadian Rhythm',
    subtitle: 'Internal Biological Clock',
    description: 'The approximately 24-hour cycle of physiological processes regulated by the suprachiasmatic nucleus. Governs sleep-wake cycles, hormone release, body temperature, and metabolism, synchronized by light exposure.',
    branch: 'biological',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep',
    children: ['suprachiasmatic-nucleus', 'melatonin'],
    unlocked: false,
    visible: true,
    x: 280,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'clock',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['clock', '24-hour', 'light'],
    prerequisites: ['sleep'],
  },
  {
    id: 'suprachiasmatic-nucleus',
    title: 'Suprachiasmatic Nucleus',
    subtitle: 'Master Circadian Pacemaker',
    description: 'A pair of small nuclei in the hypothalamus that function as the master circadian clock, receiving direct input from the retina and synchronizing peripheral clocks throughout the body.',
    branch: 'biological',
    level: 4,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'circadian-rhythm',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'sun',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['scn', 'pacemaker', 'hypothalamus'],
    prerequisites: ['circadian-rhythm'],
  },
  {
    id: 'melatonin',
    title: 'Melatonin',
    subtitle: 'Sleep-Promoting Hormone',
    description: 'A hormone produced by the pineal gland in response to darkness that promotes sleep onset and regulates circadian rhythms. Suppressed by light exposure, making it central to understanding jet lag and shift work effects.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'circadian-rhythm',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'moon',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['pineal', 'darkness', 'onset'],
    prerequisites: ['circadian-rhythm'],
  },
  {
    id: 'dreams',
    title: 'Dreams',
    subtitle: 'Subjective Experiences During Sleep',
    description: 'Mental experiences during sleep, most vivid during REM, characterized by narrative imagery, emotional content, and reduced critical thinking. Theories of function include memory consolidation, threat simulation, and emotional processing.',
    branch: 'biological',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep',
    children: ['freud-dream-theory', 'activation-synthesis', 'threat-simulation-theory'],
    unlocked: false,
    visible: true,
    x: 360,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'cloud',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['rem', 'narrative', 'meaning'],
    prerequisites: ['sleep'],
  },
  {
    id: 'freud-dream-theory',
    title: 'Freud\'s Dream Theory',
    subtitle: 'Wish Fulfillment and the Unconscious',
    description: 'Sigmund Freud\'s theory that dreams represent disguised fulfillments of repressed wishes, with manifest content masking latent content through condensation, displacement, and symbolization.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'dreams',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'lock',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['freud', 'wish', 'unconscious'],
    prerequisites: ['dreams'],
  },
  {
    id: 'activation-synthesis',
    title: 'Activation-Synthesis Hypothesis',
    subtitle: 'Random Brain Activation with Narrative Construction',
    description: 'Hobson and McCarley\'s theory that dreams result from the brain\'s attempt to make sense of random neural activation during REM sleep. The forebrain synthesizes a narrative from chaotic brainstem signals.',
    branch: 'biological',
    level: 4,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'dreams',
    children: [],
    unlocked: false,
    visible: true,
    x: 440,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'shuffle',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['hobson', 'random', 'narrative'],
    prerequisites: ['dreams'],
  },
  {
    id: 'threat-simulation-theory',
    title: 'Threat Simulation Theory',
    subtitle: 'Dreams as Rehearsal for Danger',
    description: 'Revonsuo\'s evolutionary theory proposing that dreams serve as a mechanism for simulating threatening events, allowing the dreamer to rehearse threat perception and avoidance in a safe virtual environment.',
    branch: 'biological',
    level: 4,
    xp: 200,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'dreams',
    children: [],
    unlocked: false,
    visible: true,
    x: 520,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'shield',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['revonsuo', 'evolution', 'rehearsal'],
    prerequisites: ['dreams'],
  },
  {
    id: 'sleep-disorders',
    title: 'Sleep Disorders',
    subtitle: 'Disruptions to Normal Sleep Patterns',
    description: 'Medical conditions that impair sleep quality, timing, or duration. Include insomnia, sleep apnea, narcolepsy, and parasomnias such as sleepwalking and REM behavior disorder, with significant impacts on health and cognition.',
    branch: 'biological',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep',
    children: ['insomnia', 'sleep-apnea', 'narcolepsy'],
    unlocked: false,
    visible: true,
    x: 440,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'alert-circle',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['disorders', 'quality', 'health'],
    prerequisites: ['sleep'],
  },
  {
    id: 'insomnia',
    title: 'Insomnia',
    subtitle: 'Chronic Difficulty Falling or Staying Asleep',
    description: 'A sleep disorder characterized by persistent difficulty initiating or maintaining sleep despite adequate opportunity, resulting in daytime impairment. The most common sleep complaint, often comorbid with anxiety and depression.',
    branch: 'biological',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep-disorders',
    children: [],
    unlocked: false,
    visible: true,
    x: 440,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'moon-off',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['onset', 'maintenance', 'impairment'],
    prerequisites: ['sleep-disorders'],
  },
  {
    id: 'sleep-apnea',
    title: 'Sleep Apnea',
    subtitle: 'Breathing Interruptions During Sleep',
    description: 'A serious sleep disorder in which breathing repeatedly stops and starts during sleep. Obstructive sleep apnea is caused by throat muscle relaxation; central sleep apnea occurs when the brain fails to signal breathing muscles.',
    branch: 'biological',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep-disorders',
    children: [],
    unlocked: false,
    visible: true,
    x: 520,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'wind',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['breathing', 'obstructive', 'central'],
    prerequisites: ['sleep-disorders'],
  },
  {
    id: 'narcolepsy',
    title: 'Narcolepsy',
    subtitle: 'Sudden Uncontrollable Sleep Attacks',
    description: 'A chronic neurological disorder characterized by overwhelming daytime drowsiness and sudden sleep attacks. Caused by the loss of hypocretin-producing neurons in the hypothalamus, disrupting sleep-wake regulation.',
    branch: 'biological',
    level: 4,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep-disorders',
    children: [],
    unlocked: false,
    visible: true,
    x: 600,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'zap-off',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['hypocretin', 'cataplexy', 'attacks'],
    prerequisites: ['sleep-disorders'],
  },
  {
    id: 'sleep-memory',
    title: 'Sleep and Memory Consolidation',
    subtitle: 'Strengthening Memories During Rest',
    description: 'The process by which sleep, particularly slow-wave and REM sleep, strengthens and stabilizes newly formed memories. Involves synaptic homeostasis, systems consolidation, and the transfer of memories to cortical networks.',
    branch: 'biological',
    level: 3,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'sleep',
    children: [],
    unlocked: false,
    visible: true,
    x: 520,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'save',
    difficulty: 'advanced',
    estimatedMinutes: 40,
    tags: ['consolidation', 'learning', 'synaptic'],
    prerequisites: ['sleep'],
  },
  {
    id: 'consciousness',
    title: 'Consciousness',
    subtitle: 'Awareness of Self and Environment',
    description: 'The state of being aware of and able to think about one\'s own existence, thoughts, and surroundings. Biological psychology examines the neural correlates of consciousness, altered states, and the hard problem of subjective experience.',
    branch: 'biological',
    level: 2,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'biological',
    children: ['neural-correlates', 'altered-states', 'coma', 'vegetative-state', 'split-brain-consciousness'],
    unlocked: false,
    visible: true,
    x: 400,
    y: -120,
    radius: 34,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.25)',
    iconName: 'sun',
    difficulty: 'intermediate',
    estimatedMinutes: 45,
    tags: ['awareness', 'subjective', 'neural'],
    prerequisites: ['biological'],
  },
  {
    id: 'neural-correlates',
    title: 'Neural Correlates of Consciousness',
    subtitle: 'Brain Activity Underlying Awareness',
    description: 'The minimal set of neuronal events and mechanisms jointly sufficient for any one specific conscious percept. Searches for the neural substrates of conscious experience using neuroimaging and lesion studies.',
    branch: 'biological',
    level: 3,
    xp: 220,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'consciousness',
    children: ['global-workspace-theory', 'integrated-information-theory'],
    unlocked: false,
    visible: true,
    x: 320,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'brain-circuit',
    difficulty: 'expert',
    estimatedMinutes: 50,
    tags: ['ncc', 'substrates', 'imaging'],
    prerequisites: ['consciousness'],
  },
  {
    id: 'global-workspace-theory',
    title: 'Global Workspace Theory',
    subtitle: 'Consciousness as Information Broadcasting',
    description: 'Bernard Baars\' theory proposing that consciousness arises from a global workspace in which information is broadcast to multiple brain systems, allowing integration and coordinated response across modules.',
    branch: 'biological',
    level: 4,
    xp: 280,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neural-correlates',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'broadcast',
    difficulty: 'expert',
    estimatedMinutes: 50,
    tags: ['baars', 'broadcasting', 'integration'],
    prerequisites: ['neural-correlates'],
  },
  {
    id: 'integrated-information-theory',
    title: 'Integrated Information Theory',
    subtitle: 'Consciousness as Integrated Information',
    description: 'Giulio Tononi\'s theory proposing that consciousness corresponds to integrated information (phi) in a system. Quantifies consciousness and predicts which systems are conscious based on their causal architecture.',
    branch: 'biological',
    level: 4,
    xp: 320,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'neural-correlates',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'infinity',
    difficulty: 'expert',
    estimatedMinutes: 60,
    tags: ['tononi', 'phi', 'causal'],
    prerequisites: ['neural-correlates'],
  },
  {
    id: 'altered-states',
    title: 'Altered States of Consciousness',
    subtitle: 'Deviations from Normal Waking Awareness',
    description: 'Conditions that differ significantly from normal waking consciousness, including those induced by meditation, hypnosis, psychoactive substances, sensory deprivation, and extreme fatigue.',
    branch: 'biological',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'consciousness',
    children: ['meditation', 'hypnosis', 'psychoactive-substances'],
    unlocked: false,
    visible: true,
    x: 400,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'cloud-fog',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['meditation', 'hypnosis', 'drugs'],
    prerequisites: ['consciousness'],
  },
  {
    id: 'meditation',
    title: 'Meditation',
    subtitle: 'Training Attention and Awareness',
    description: 'A practice of focused attention and awareness that induces altered states of consciousness associated with changes in brain activity, including increased alpha and theta waves, and structural changes in prefrontal and insular cortex.',
    branch: 'biological',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'altered-states',
    children: [],
    unlocked: false,
    visible: true,
    x: 400,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'flower-2',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['mindfulness', 'attention', 'plasticity'],
    prerequisites: ['altered-states'],
  },
  {
    id: 'hypnosis',
    title: 'Hypnosis',
    subtitle: 'Induced Trance State',
    description: 'A trance-like state of heightened suggestibility and focused attention, characterized by reduced peripheral awareness and increased responsiveness to suggestion. Associated with altered brain activity in anterior cingulate and prefrontal regions.',
    branch: 'biological',
    level: 4,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'altered-states',
    children: [],
    unlocked: false,
    visible: true,
    x: 480,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'watch',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['suggestibility', 'trance', 'pain'],
    prerequisites: ['altered-states'],
  },
  {
    id: 'psychoactive-substances',
    title: 'Psychoactive Substances',
    subtitle: 'Chemicals That Alter Consciousness',
    description: 'Substances that affect mental processes such as cognition, mood, and perception by acting on the nervous system. Include depressants, stimulants, opioids, hallucinogens, and cannabinoids, each with distinct neural mechanisms.',
    branch: 'biological',
    level: 4,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'altered-states',
    children: [],
    unlocked: false,
    visible: true,
    x: 560,
    y: -320,
    radius: 20,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.15)',
    iconName: 'pill',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['drugs', 'neurotransmitters', 'alteration'],
    prerequisites: ['altered-states'],
  },
  {
    id: 'coma',
    title: 'Coma',
    subtitle: 'Prolonged Unconsciousness',
    description: 'A state of deep unconsciousness lasting more than six hours, in which a person cannot be awakened, fails to respond to painful stimuli, light, or sound, and lacks a normal sleep-wake cycle. Caused by brain injury, stroke, or metabolic dysfunction.',
    branch: 'biological',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'consciousness',
    children: [],
    unlocked: false,
    visible: true,
    x: 480,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'bed',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['unconscious', 'injury', 'trauma'],
    prerequisites: ['consciousness'],
  },
  {
    id: 'vegetative-state',
    title: 'Vegetative State',
    subtitle: 'Wakefulness Without Awareness',
    description: 'A disorder of consciousness in which patients show sleep-wake cycles and reflexive behaviors but lack awareness of self and environment. Distinguished from coma by preserved arousal and from minimally conscious state by absent awareness.',
    branch: 'biological',
    level: 3,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'consciousness',
    children: [],
    unlocked: false,
    visible: true,
    x: 560,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'eye',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['awareness', 'arousal', 'disorder'],
    prerequisites: ['consciousness'],
  },
  {
    id: 'split-brain-consciousness',
    title: 'Split-Brain Consciousness',
    subtitle: 'Divided Awareness After Commissurotomy',
    description: 'The study of conscious experience in patients with severed corpus callosum, revealing two independent hemispheric minds with distinct perceptions, memories, and intentions. Demonstrates the modular nature of consciousness.',
    branch: 'biological',
    level: 3,
    xp: 200,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'consciousness',
    children: [],
    unlocked: false,
    visible: true,
    x: 640,
    y: -240,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'split',
    difficulty: 'expert',
    estimatedMinutes: 40,
    tags: ['sperry', 'gazzaniga', 'hemispheres'],
    prerequisites: ['consciousness'],
  },
  {
    id: 'plasticity',
    title: 'Neuroplasticity',
    subtitle: 'The Brain\'s Ability to Change',
    description: 'The capacity of the nervous system to modify its structure and function in response to experience, learning, or injury. Includes synaptic plasticity, structural plasticity, and functional reorganization throughout the lifespan.',
    branch: 'biological',
    level: 2,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'biological',
    children: ['synaptic-plasticity', 'long-term-potentiation', 'long-term-depression', 'structural-plasticity', 'critical-periods'],
    unlocked: false,
    visible: true,
    x: -400,
    y: 0,
    radius: 34,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.25)',
    iconName: 'refresh-cw',
    difficulty: 'intermediate',
    estimatedMinutes: 45,
    tags: ['change', 'adaptation', 'learning'],
    prerequisites: ['biological'],
  },
  {
    id: 'synaptic-plasticity',
    title: 'Synaptic Plasticity',
    subtitle: 'Strengthening and Weakening of Synapses',
    description: 'The ability of synapses to change their strength in response to increases or decreases in activity. The cellular basis of learning and memory, governed by Hebbian principles: neurons that fire together wire together.',
    branch: 'biological',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'plasticity',
    children: [],
    unlocked: false,
    visible: true,
    x: -520,
    y: -120,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'link-2',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['hebb', 'strength', 'learning'],
    prerequisites: ['plasticity'],
  },
  {
    id: 'long-term-potentiation',
    title: 'Long-Term Potentiation',
    subtitle: 'Persistent Synaptic Strengthening',
    description: 'A long-lasting increase in synaptic strength following high-frequency stimulation of a synapse. The leading cellular mechanism for learning and memory, involving NMDA receptor activation and protein synthesis.',
    branch: 'biological',
    level: 3,
    xp: 200,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'plasticity',
    children: [],
    unlocked: false,
    visible: true,
    x: -440,
    y: -120,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'trending-up',
    difficulty: 'advanced',
    estimatedMinutes: 45,
    tags: ['ltp', 'nmda', 'memory'],
    prerequisites: ['plasticity'],
  },
  {
    id: 'long-term-depression',
    title: 'Long-Term Depression',
    subtitle: 'Persistent Synaptic Weakening',
    description: 'A long-lasting decrease in synaptic strength following low-frequency stimulation. Complements long-term potentiation in refining neural circuits and may underlie forgetting and the extinction of learned responses.',
    branch: 'biological',
    level: 3,
    xp: 190,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'plasticity',
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: -120,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'trending-down',
    difficulty: 'advanced',
    estimatedMinutes: 40,
    tags: ['ltd', 'weakening', 'extinction'],
    prerequisites: ['plasticity'],
  },
  {
    id: 'structural-plasticity',
    title: 'Structural Plasticity',
    subtitle: 'Physical Changes in Neural Architecture',
    description: 'Changes in the physical structure of neurons including dendritic branching, spine density, axonal sprouting, and the formation of new synapses. Underlies recovery from brain injury and the effects of enriched environments.',
    branch: 'biological',
    level: 3,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'plasticity',
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: -120,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'tree-deciduous',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['dendrites', 'spines', 'growth'],
    prerequisites: ['plasticity'],
  },
  {
    id: 'critical-periods',
    title: 'Critical Periods',
    subtitle: 'Time-Limited Windows for Plasticity',
    description: 'Developmental windows during which the nervous system is particularly sensitive to environmental input and experience-dependent plasticity. After closure, plasticity becomes more restricted though not absent.',
    branch: 'biological',
    level: 3,
    xp: 180,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'plasticity',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -120,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'clock',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['development', 'sensitive', 'windows'],
    prerequisites: ['plasticity'],
  },
  {
    id: 'genetics',
    title: 'Behavioral Genetics',
    subtitle: 'Genes and Behavior',
    description: 'The scientific study of the interplay between genetic and environmental influences on behavior. Examines heritability, molecular genetics, gene-environment interactions, and epigenetics in psychological traits and disorders.',
    branch: 'biological',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'biological',
    children: ['heritability', 'twin-studies', 'gene-environment-interaction', 'epigenetics'],
    unlocked: false,
    visible: true,
    x: -200,
    y: 120,
    radius: 34,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.25)',
    iconName: 'dna',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['genes', 'heredity', 'nature-nurture'],
    prerequisites: ['biological'],
  },
  {
    id: 'heritability',
    title: 'Heritability',
    subtitle: 'Proportion of Variance Due to Genes',
    description: 'A statistic that estimates the proportion of variation in a trait within a population that is attributable to genetic differences. Does not indicate the degree to which an individual\'s trait is genetically determined.',
    branch: 'biological',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'genetics',
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: 0,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'percent',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['variance', 'population', 'misconception'],
    prerequisites: ['genetics'],
  },
  {
    id: 'twin-studies',
    title: 'Twin Studies',
    subtitle: 'Disentangling Genes and Environment',
    description: 'A research design comparing identical and fraternal twins to estimate genetic and environmental contributions to traits. Monozygotic twins share 100% of genes; dizygotic twins share approximately 50%.',
    branch: 'biological',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'genetics',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: 0,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'copy',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['monozygotic', 'dizygotic', 'methodology'],
    prerequisites: ['genetics'],
  },
  {
    id: 'gene-environment-interaction',
    title: 'Gene-Environment Interaction',
    subtitle: 'Genes and Experience Shape Each Other',
    description: 'The phenomenon whereby genetic effects on behavior depend on environmental context, and environmental effects depend on genetic makeup. Demonstrates that nature and nurture are inseparable in shaping behavior.',
    branch: 'biological',
    level: 3,
    xp: 170,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'genetics',
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: 0,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'git-merge',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['interaction', 'context', 'gxE'],
    prerequisites: ['genetics'],
  },
  {
    id: 'epigenetics',
    title: 'Epigenetics',
    subtitle: 'Gene Expression Without DNA Change',
    description: 'The study of heritable changes in gene expression that do not involve alterations to the DNA sequence. Includes DNA methylation and histone modification, explaining how environmental factors can influence gene activity across generations.',
    branch: 'biological',
    level: 3,
    xp: 200,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'genetics',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: 0,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'layers',
    difficulty: 'expert',
    estimatedMinutes: 45,
    tags: ['methylation', 'expression', 'inheritance'],
    prerequisites: ['genetics'],
  },
  {
    id: 'evolution',
    title: 'Evolutionary Psychology',
    subtitle: 'Adaptation and Natural Selection',
    description: 'The application of evolutionary principles to understanding human psychology and behavior. Examines how natural selection has shaped cognitive mechanisms, emotions, and social behaviors to solve adaptive problems in ancestral environments.',
    branch: 'biological',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'biological',
    children: ['natural-selection', 'adaptation', 'evolutionary-pressures', 'sexual-selection'],
    unlocked: false,
    visible: true,
    x: 0,
    y: 120,
    radius: 34,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.25)',
    iconName: 'git-branch',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['darwin', 'adaptation', 'ancestral'],
    prerequisites: ['biological'],
  },
  {
    id: 'natural-selection',
    title: 'Natural Selection',
    subtitle: 'Mechanism of Evolutionary Change',
    description: 'The process by which heritable traits that enhance survival and reproduction become more common in successive generations. The foundational mechanism of evolutionary psychology for understanding the origins of mental adaptations.',
    branch: 'biological',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'evolution',
    children: [],
    unlocked: false,
    visible: true,
    x: -120,
    y: 0,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'arrow-up',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['darwin', 'fitness', 'survival'],
    prerequisites: ['evolution'],
  },
  {
    id: 'adaptation',
    title: 'Psychological Adaptations',
    subtitle: 'Evolved Solutions to Ancestral Problems',
    description: 'Specialized cognitive mechanisms that evolved to solve specific adaptive problems faced by ancestral humans, such as mate selection, social exchange, predator avoidance, and kin recognition.',
    branch: 'biological',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'evolution',
    children: [],
    unlocked: false,
    visible: true,
    x: -40,
    y: 0,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'puzzle',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['mechanisms', 'specialized', 'problems'],
    prerequisites: ['evolution'],
  },
  {
    id: 'evolutionary-pressures',
    title: 'Evolutionary Pressures',
    subtitle: 'Forces That Shaped the Human Mind',
    description: 'The environmental challenges and selective pressures in ancestral environments that shaped the evolution of human cognitive and behavioral traits, including social complexity, predator avoidance, and resource scarcity.',
    branch: 'biological',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'evolution',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: 0,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'mountain',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['environment', 'selection', 'ancestral'],
    prerequisites: ['evolution'],
  },
  {
    id: 'sexual-selection',
    title: 'Sexual Selection',
    subtitle: 'Mate Choice and Competition',
    description: 'A form of natural selection in which individuals with certain inherited characteristics are more likely than others to obtain mates. Explains the evolution of traits that enhance mating success, including cognitive and behavioral displays.',
    branch: 'biological',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'evolution',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: 0,
    radius: 26,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.20)',
    iconName: 'heart',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['mate', 'competition', 'choice'],
    prerequisites: ['evolution'],
  },
];
