export interface TreeNode {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  branch: string;
  level: number;
  xp: number;
  status: 'mastered' | 'available' | 'locked';
  progress: number;
  completed: number;
  total: number;
  parent: string | null;
  children: string[];
  unlocked: boolean;
  visible: boolean;
  x: number;
  y: number;
  radius: number;
  color: string;
  glow: boolean;
  iconName: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';
  estimatedMinutes: number;
  tags: string[];
  prerequisites: string[];
}

export const clinicalNodes: TreeNode[] = [
  {
    id: "clinical-psychology",
    title: "Clinical Psychology",
    subtitle: "The Science and Practice of Mental Health",
    description: "Clinical psychology integrates science, theory, and clinical knowledge to understand, prevent, and relieve psychologically-based distress or dysfunction and to promote subjective well-being and personal development.",
    branch: "Clinical",
    level: 0,
    xp: 500,
    status: "mastered",
    progress: 100,
    completed: 10,
    total: 10,
    parent: null,
    children: ["history-of-clinical-psychology", "mental-health", "mental-illness", "biopsychosocial-model", "ethics-in-clinical-psychology"],
    unlocked: true,
    visible: true,
    x: 500,
    y: 400,
    radius: 40,
    color: "#4F46E5",
    glow: true,
    iconName: "Brain",
    difficulty: "Expert",
    estimatedMinutes: 60,
    tags: ["clinical", "foundation", "overview"],
    prerequisites: []
  },
  {
    id: "history-of-clinical-psychology",
    title: "History of Clinical Psychology",
    subtitle: "From Asylums to Evidence-Based Practice",
    description: "Traces the evolution of clinical psychology from early asylums and moral treatment through the development of psychodynamic, behavioral, and cognitive approaches to modern evidence-based practice.",
    branch: "Clinical",
    level: 1,
    xp: 120,
    status: "available",
    progress: 0,
    completed: 0,
    total: 8,
    parent: "clinical-psychology",
    children: [],
    unlocked: true,
    visible: true,
    x: 300,
    y: 200,
    radius: 28,
    color: "#6366F1",
    glow: false,
    iconName: "History",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["history", "evolution", "foundations"],
    prerequisites: ["clinical-psychology"]
  },
  {
    id: "mental-health",
    title: "Mental Health",
    subtitle: "Well-Being and Psychological Functioning",
    description: "Mental health encompasses emotional, psychological, and social well-being, affecting how individuals think, feel, act, handle stress, relate to others, and make choices.",
    branch: "Clinical",
    level: 1,
    xp: 80,
    status: "available",
    progress: 0,
    completed: 0,
    total: 6,
    parent: "clinical-psychology",
    children: ["dsm-5", "icd-11"],
    unlocked: true,
    visible: true,
    x: 500,
    y: 150,
    radius: 28,
    color: "#10B981",
    glow: false,
    iconName: "Heart",
    difficulty: "Beginner",
    estimatedMinutes: 30,
    tags: ["well-being", "mental-health", "functioning"],
    prerequisites: ["clinical-psychology"]
  },
  {
    id: "mental-illness",
    title: "Mental Illness",
    subtitle: "Understanding Psychopathology",
    description: "Mental illness refers to a wide range of mental health conditions — disorders that affect mood, thinking, and behavior, including depression, anxiety disorders, schizophrenia, eating disorders, and addictive behaviors.",
    branch: "Clinical",
    level: 1,
    xp: 80,
    status: "available",
    progress: 0,
    completed: 0,
    total: 6,
    parent: "clinical-psychology",
    children: ["case-formulation"],
    unlocked: true,
    visible: true,
    x: 700,
    y: 200,
    radius: 28,
    color: "#EF4444",
    glow: false,
    iconName: "AlertTriangle",
    difficulty: "Beginner",
    estimatedMinutes: 30,
    tags: ["psychopathology", "disorders", "mental-illness"],
    prerequisites: ["clinical-psychology"]
  },
  {
    id: "biopsychosocial-model",
    title: "Biopsychosocial Model",
    subtitle: "Integrative Framework for Understanding Disorders",
    description: "The biopsychosocial model proposes that biological, psychological, and social factors all play a significant role in human functioning in the context of disease or illness.",
    branch: "Clinical",
    level: 1,
    xp: 100,
    status: "available",
    progress: 0,
    completed: 0,
    total: 7,
    parent: "clinical-psychology",
    children: ["clinical-interview", "mental-status-examination"],
    unlocked: true,
    visible: true,
    x: 300,
    y: 600,
    radius: 28,
    color: "#8B5CF6",
    glow: false,
    iconName: "Layers",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["biopsychosocial", "integration", "framework"],
    prerequisites: ["clinical-psychology"]
  },
  {
    id: "ethics-in-clinical-psychology",
    title: "Ethics in Clinical Psychology",
    subtitle: "Professional Standards and Moral Principles",
    description: "Covers the ethical principles and code of conduct for clinical psychologists, including confidentiality, informed consent, competence, boundaries, and duty to protect.",
    branch: "Clinical",
    level: 1,
    xp: 100,
    status: "available",
    progress: 0,
    completed: 0,
    total: 7,
    parent: "clinical-psychology",
    children: [],
    unlocked: true,
    visible: true,
    x: 700,
    y: 600,
    radius: 28,
    color: "#F59E0B",
    glow: false,
    iconName: "Shield",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["ethics", "professional-standards", "conduct"],
    prerequisites: ["clinical-psychology"]
  },
  {
    id: "dsm-5",
    title: "DSM-5",
    subtitle: "Diagnostic and Statistical Manual of Mental Disorders",
    description: "The DSM-5 is the standard classification of mental disorders used by mental health professionals in the United States, providing diagnostic criteria and codes for clinical and research purposes.",
    branch: "Clinical",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "mental-health",
    children: [],
    unlocked: false,
    visible: true,
    x: 400,
    y: 50,
    radius: 24,
    color: "#3B82F6",
    glow: false,
    iconName: "BookOpen",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["diagnosis", "classification", "dsm"],
    prerequisites: ["mental-health"]
  },
  {
    id: "icd-11",
    title: "ICD-11",
    subtitle: "International Classification of Diseases 11th Revision",
    description: "The ICD-11 is the global standard for diagnostic health information, including mental, behavioral, and neurodevelopmental disorders, maintained by the World Health Organization.",
    branch: "Clinical",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "mental-health",
    children: [],
    unlocked: false,
    visible: true,
    x: 600,
    y: 50,
    radius: 24,
    color: "#06B6D4",
    glow: false,
    iconName: "Globe",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["classification", "who", "international"],
    prerequisites: ["mental-health"]
  },
  {
    id: "case-formulation",
    title: "Case Formulation",
    subtitle: "Integrative Understanding of the Individual",
    description: "Case formulation is a process of integrating and summarizing information about a client to develop a coherent understanding of their difficulties, including predisposing, precipitating, perpetuating, and protective factors.",
    branch: "Clinical",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 9,
    parent: "mental-illness",
    children: ["psychological-assessment"],
    unlocked: false,
    visible: true,
    x: 850,
    y: 150,
    radius: 24,
    color: "#EC4899",
    glow: false,
    iconName: "FileText",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["formulation", "case-conceptualization", "integration"],
    prerequisites: ["mental-illness"]
  },
  {
    id: "clinical-interview",
    title: "Clinical Interview",
    subtitle: "Structured and Unstructured Assessment Conversations",
    description: "The clinical interview is a foundational assessment method involving structured, semi-structured, or unstructured conversations to gather information about a client's history, symptoms, and concerns.",
    branch: "Clinical",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 8,
    parent: "biopsychosocial-model",
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: 500,
    radius: 24,
    color: "#14B8A6",
    glow: false,
    iconName: "MessageCircle",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["interview", "assessment", "communication"],
    prerequisites: ["biopsychosocial-model"]
  },
  {
    id: "mental-status-examination",
    title: "Mental Status Examination",
    subtitle: "Systematic Evaluation of Mental Functioning",
    description: "The MSE is a structured assessment of a patient's cognitive and emotional functioning, examining appearance, behavior, mood, affect, speech, thought process, thought content, perception, cognition, insight, and judgment.",
    branch: "Clinical",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 9,
    parent: "biopsychosocial-model",
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: 700,
    radius: 24,
    color: "#F97316",
    glow: false,
    iconName: "Stethoscope",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["mse", "examination", "mental-status"],
    prerequisites: ["biopsychosocial-model"]
  },
  {
    id: "psychological-assessment",
    title: "Psychological Assessment",
    subtitle: "Comprehensive Evaluation Methods",
    description: "Psychological assessment involves the integration of information from multiple sources, including tests, interviews, observations, and records, to understand an individual's psychological functioning.",
    branch: "Clinical",
    level: 3,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "case-formulation",
    children: ["intelligence-tests", "personality-assessment", "neuropsychological-assessment", "behavioral-assessment"],
    unlocked: false,
    visible: true,
    x: 950,
    y: 300,
    radius: 26,
    color: "#7C3AED",
    glow: false,
    iconName: "ClipboardCheck",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["assessment", "evaluation", "testing"],
    prerequisites: ["case-formulation"]
  },
  {
    id: "intelligence-tests",
    title: "Intelligence Tests",
    subtitle: "Measuring Cognitive Abilities",
    description: "Intelligence tests assess cognitive abilities including reasoning, problem-solving, abstract thinking, learning speed, and memory. Common instruments include WAIS, WISC, Stanford-Binet, and Raven's Progressive Matrices.",
    branch: "Clinical",
    level: 4,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychological-assessment",
    children: ["reliability", "validity"],
    unlocked: false,
    visible: true,
    x: 800,
    y: 400,
    radius: 22,
    color: "#6366F1",
    glow: false,
    iconName: "BrainCircuit",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["iq", "cognitive", "intelligence"],
    prerequisites: ["psychological-assessment"]
  },
  {
    id: "personality-assessment",
    title: "Personality Assessment",
    subtitle: "Evaluating Personality Traits and Patterns",
    description: "Personality assessment examines individual differences in characteristic patterns of thinking, feeling, and behaving. Methods include self-report inventories (MMPI, NEO-PI), projective tests (Rorschach, TAT), and clinical interviews.",
    branch: "Clinical",
    level: 4,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychological-assessment",
    children: ["reliability", "validity"],
    unlocked: false,
    visible: true,
    x: 950,
    y: 450,
    radius: 22,
    color: "#EC4899",
    glow: false,
    iconName: "User",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["personality", "traits", "assessment"],
    prerequisites: ["psychological-assessment"]
  },
  {
    id: "neuropsychological-assessment",
    title: "Neuropsychological Assessment",
    subtitle: "Brain-Behavior Relationships",
    description: "Neuropsychological assessment evaluates cognitive functioning to understand brain-behavior relationships, diagnose neurological conditions, and plan rehabilitation after brain injury or disease.",
    branch: "Clinical",
    level: 4,
    xp: 280,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 14,
    parent: "psychological-assessment",
    children: ["reliability", "validity"],
    unlocked: false,
    visible: true,
    x: 1100,
    y: 400,
    radius: 22,
    color: "#8B5CF6",
    glow: false,
    iconName: "Activity",
    difficulty: "Expert",
    estimatedMinutes: 60,
    tags: ["neuropsychology", "brain", "cognition"],
    prerequisites: ["psychological-assessment"]
  },
  {
    id: "behavioral-assessment",
    title: "Behavioral Assessment",
    subtitle: "Direct Observation and Functional Analysis",
    description: "Behavioral assessment focuses on observable behaviors and their environmental determinants, using methods such as direct observation, behavioral interviewing, self-monitoring, and functional analysis.",
    branch: "Clinical",
    level: 4,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "psychological-assessment",
    children: ["reliability", "validity"],
    unlocked: false,
    visible: true,
    x: 950,
    y: 250,
    radius: 22,
    color: "#10B981",
    glow: false,
    iconName: "Eye",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["behavior", "observation", "functional-analysis"],
    prerequisites: ["psychological-assessment"]
  },
  {
    id: "reliability",
    title: "Reliability",
    subtitle: "Consistency and Stability of Measurement",
    description: "Reliability refers to the consistency, stability, and dependability of a psychological measure. Types include test-retest, inter-rater, internal consistency, and parallel-forms reliability.",
    branch: "Clinical",
    level: 5,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "intelligence-tests",
    children: [],
    unlocked: false,
    visible: true,
    x: 750,
    y: 550,
    radius: 20,
    color: "#3B82F6",
    glow: false,
    iconName: "Repeat",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["reliability", "psychometrics", "measurement"],
    prerequisites: ["intelligence-tests", "personality-assessment", "neuropsychological-assessment", "behavioral-assessment"]
  },
  {
    id: "validity",
    title: "Validity",
    subtitle: "Accuracy and Meaningfulness of Measurement",
    description: "Validity refers to whether a test measures what it claims to measure. Types include content, criterion-related, construct, face, and ecological validity, as well as threats to validity.",
    branch: "Clinical",
    level: 5,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "intelligence-tests",
    children: [],
    unlocked: false,
    visible: true,
    x: 900,
    y: 550,
    radius: 20,
    color: "#06B6D4",
    glow: false,
    iconName: "CheckCircle",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["validity", "psychometrics", "accuracy"],
    prerequisites: ["intelligence-tests", "personality-assessment", "neuropsychological-assessment", "behavioral-assessment"]
  },
 {
    id: "psychological-disorders",
    title: "Psychological Disorders",
    subtitle: "Classification and Understanding of Mental Disorders",
    description: "Psychological disorders represent clinically significant disturbances in an individual's cognition, emotional regulation, or behavior that reflect dysfunction in psychological, biological, or developmental processes.",
    branch: "Clinical",
    level: 1,
    xp: 200,
    status: "available",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "clinical-psychology",
    children: ["mood-disorders", "anxiety-disorders", "obsessive-compulsive-disorder", "trauma-disorders", "schizophrenia-spectrum", "personality-disorders", "eating-disorders", "somatic-symptom-disorders", "substance-use-disorders", "neurodevelopmental-disorders", "sleep-disorders"],
    unlocked: true,
    visible: true,
    x: 900,
    y: 400,
    radius: 32,
    color: "#DC2626",
    glow: true,
    iconName: "Brain",
    difficulty: "Expert",
    estimatedMinutes: 60,
    tags: ["disorders", "psychopathology", "classification"],
    prerequisites: ["clinical-psychology"]
  },
  {
    id: "mood-disorders",
    title: "Mood Disorders",
    subtitle: "Disturbances in Emotional Experience",
    description: "Mood disorders are a group of psychiatric conditions characterized by pervasive disturbances in mood, including depression, mania, and bipolar states, significantly impacting daily functioning and quality of life.",
    branch: "Clinical",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "psychological-disorders",
    children: ["major-depressive-disorder", "persistent-depressive-disorder", "bipolar-disorder"],
    unlocked: false,
    visible: true,
    x: 700,
    y: 250,
    radius: 26,
    color: "#3B82F6",
    glow: false,
    iconName: "CloudRain",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["mood", "depression", "bipolar"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "major-depressive-disorder",
    title: "Major Depressive Disorder",
    subtitle: "Persistent Depressive Episodes",
    description: "Major depressive disorder involves persistent feelings of sadness, hopelessness, and loss of interest in activities, accompanied by cognitive, behavioral, and physical symptoms lasting at least two weeks.",
    branch: "Clinical",
    level: 3,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "mood-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 600,
    y: 150,
    radius: 22,
    color: "#1E40AF",
    glow: false,
    iconName: "Frown",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["depression", "mdd", "affective"],
    prerequisites: ["mood-disorders"]
  },
  {
    id: "persistent-depressive-disorder",
    title: "Persistent Depressive Disorder",
    subtitle: "Chronic Low-Grade Depression",
    description: "Persistent depressive disorder (dysthymia) involves a chronically depressed mood lasting at least two years in adults, with symptoms less severe but more enduring than major depression.",
    branch: "Clinical",
    level: 3,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "mood-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 700,
    y: 100,
    radius: 22,
    color: "#60A5FA",
    glow: false,
    iconName: "TrendingDown",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["dysthymia", "chronic", "depression"],
    prerequisites: ["mood-disorders"]
  },
  {
    id: "bipolar-disorder",
    title: "Bipolar Disorder",
    subtitle: "Cycling Between Mania and Depression",
    description: "Bipolar disorder is characterized by alternating episodes of mania or hypomania and depression, with significant shifts in energy, activity levels, and ability to carry out daily tasks.",
    branch: "Clinical",
    level: 3,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 14,
    parent: "mood-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 800,
    y: 150,
    radius: 22,
    color: "#7C3AED",
    glow: false,
    iconName: "Zap",
    difficulty: "Expert",
    estimatedMinutes: 60,
    tags: ["bipolar", "mania", "cyclothymia"],
    prerequisites: ["mood-disorders"]
  },
  {
    id: "anxiety-disorders",
    title: "Anxiety Disorders",
    subtitle: "Excessive Fear and Worry",
    description: "Anxiety disorders involve excessive and persistent fear, worry, and related behavioral disturbances that are disproportionate to the actual threat and impair daily functioning.",
    branch: "Clinical",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "psychological-disorders",
    children: ["generalized-anxiety-disorder", "panic-disorder", "phobias", "social-anxiety-disorder"],
    unlocked: false,
    visible: true,
    x: 900,
    y: 200,
    radius: 26,
    color: "#10B981",
    glow: false,
    iconName: "ShieldAlert",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["anxiety", "fear", "worry"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "generalized-anxiety-disorder",
    title: "Generalized Anxiety Disorder",
    subtitle: "Persistent and Excessive Worry",
    description: "Generalized anxiety disorder involves chronic, excessive worry about multiple domains of life, accompanied by physical symptoms such as restlessness, fatigue, difficulty concentrating, and muscle tension.",
    branch: "Clinical",
    level: 3,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "anxiety-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 850,
    y: 100,
    radius: 22,
    color: "#059669",
    glow: false,
    iconName: "AlertCircle",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["gad", "worry", "generalized"],
    prerequisites: ["anxiety-disorders"]
  },
  {
    id: "panic-disorder",
    title: "Panic Disorder",
    subtitle: "Recurrent Unexpected Panic Attacks",
    description: "Panic disorder is characterized by recurrent, unexpected panic attacks accompanied by intense fear and physical symptoms, often leading to persistent concern about future attacks and avoidance behaviors.",
    branch: "Clinical",
    level: 3,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "anxiety-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 950,
    y: 80,
    radius: 22,
    color: "#F59E0B",
    glow: false,
    iconName: "Flame",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["panic", "attacks", "fear"],
    prerequisites: ["anxiety-disorders"]
  },
  {
    id: "phobias",
    title: "Phobias",
    subtitle: "Irrational Fear of Specific Objects or Situations",
    description: "Specific phobias involve intense, irrational fear of particular objects, animals, situations, or natural phenomena, leading to active avoidance that significantly interferes with daily life.",
    branch: "Clinical",
    level: 3,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 9,
    parent: "anxiety-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1050,
    y: 100,
    radius: 22,
    color: "#EF4444",
    glow: false,
    iconName: "EyeOff",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["phobia", "fear", "avoidance"],
    prerequisites: ["anxiety-disorders"]
  },
  {
    id: "social-anxiety-disorder",
    title: "Social Anxiety Disorder",
    subtitle: "Intense Fear of Social Situations",
    description: "Social anxiety disorder involves marked fear or anxiety about social situations where one may be scrutinized by others, leading to avoidance of social interactions and significant impairment in functioning.",
    branch: "Clinical",
    level: 3,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "anxiety-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1150,
    y: 150,
    radius: 22,
    color: "#8B5CF6",
    glow: false,
    iconName: "Users",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["social", "anxiety", "phobia"],
    prerequisites: ["anxiety-disorders"]
  },
  {
    id: "obsessive-compulsive-disorder",
    title: "Obsessive Compulsive Disorder",
    subtitle: "Intrusive Thoughts and Repetitive Behaviors",
    description: "Obsessive-compulsive disorder is characterized by recurrent, intrusive obsessions and repetitive compulsions performed to reduce anxiety, consuming significant time and interfering with daily functioning.",
    branch: "Clinical",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "psychological-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1100,
    y: 300,
    radius: 26,
    color: "#F97316",
    glow: false,
    iconName: "RefreshCw",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["ocd", "obsessions", "compulsions"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "trauma-disorders",
    title: "Trauma Disorders",
    subtitle: "Responses to Traumatic Events",
    description: "Trauma and stressor-related disorders develop after exposure to actual or threatened death, serious injury, or sexual violence, resulting in persistent psychological and physiological disturbances.",
    branch: "Clinical",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "psychological-disorders",
    children: ["ptsd", "acute-stress-disorder"],
    unlocked: false,
    visible: true,
    x: 1200,
    y: 400,
    radius: 26,
    color: "#7C2D12",
    glow: false,
    iconName: "AlertTriangle",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["trauma", "ptsd", "stress"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "ptsd",
    title: "PTSD",
    subtitle: "Post-Traumatic Stress Disorder",
    description: "Post-traumatic stress disorder develops after exposure to trauma, characterized by intrusive memories, avoidance of reminders, negative alterations in cognition and mood, and marked hyperarousal.",
    branch: "Clinical",
    level: 3,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "trauma-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1250,
    y: 300,
    radius: 22,
    color: "#B91C1C",
    glow: false,
    iconName: "Shield",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["ptsd", "trauma", "stress"],
    prerequisites: ["trauma-disorders"]
  },
  {
    id: "acute-stress-disorder",
    title: "Acute Stress Disorder",
    subtitle: "Immediate Trauma Response",
    description: "Acute stress disorder involves dissociative, re-experiencing, avoidance, and arousal symptoms developing immediately after trauma exposure, lasting between three days and one month.",
    branch: "Clinical",
    level: 3,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 9,
    parent: "trauma-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1350,
    y: 350,
    radius: 22,
    color: "#F59E0B",
    glow: false,
    iconName: "Clock",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["acute", "trauma", "dissociation"],
    prerequisites: ["trauma-disorders"]
  },
  {
    id: "schizophrenia-spectrum",
    title: "Schizophrenia Spectrum",
    subtitle: "Psychotic Disorders and Reality Disturbance",
    description: "Schizophrenia spectrum disorders involve disturbances in thought, perception, emotion, language, sense of self, and behavior, including delusions, hallucinations, disorganized thinking, and negative symptoms.",
    branch: "Clinical",
    level: 2,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 14,
    parent: "psychological-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1300,
    y: 500,
    radius: 26,
    color: "#581C87",
    glow: false,
    iconName: "Ghost",
    difficulty: "Expert",
    estimatedMinutes: 60,
    tags: ["schizophrenia", "psychosis", "spectrum"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "personality-disorders",
    title: "Personality Disorders",
    subtitle: "Enduring Maladaptive Patterns of Behavior",
    description: "Personality disorders involve enduring, inflexible, and pervasive patterns of inner experience and behavior that deviate from cultural expectations, causing distress or impairment across multiple contexts.",
    branch: "Clinical",
    level: 2,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychological-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1200,
    y: 600,
    radius: 26,
    color: "#BE185D",
    glow: false,
    iconName: "UserX",
    difficulty: "Expert",
    estimatedMinutes: 55,
    tags: ["personality", "traits", "patterns"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "eating-disorders",
    title: "Eating Disorders",
    subtitle: "Disturbances in Eating Behavior and Body Image",
    description: "Eating disorders involve persistent disturbances in eating-related behaviors and distressing thoughts and emotions about body weight and shape, significantly impacting physical health and psychosocial functioning.",
    branch: "Clinical",
    level: 2,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychological-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1050,
    y: 650,
    radius: 26,
    color: "#EC4899",
    glow: false,
    iconName: "Utensils",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["eating", "anorexia", "bulimia"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "somatic-symptom-disorders",
    title: "Somatic Symptom Disorders",
    subtitle: "Distressing Physical Symptoms with Psychological Components",
    description: "Somatic symptom and related disorders involve distressing physical symptoms accompanied by excessive thoughts, feelings, or behaviors related to those symptoms, often without adequate medical explanation.",
    branch: "Clinical",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "psychological-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 900,
    y: 700,
    radius: 26,
    color: "#14B8A6",
    glow: false,
    iconName: "HeartPulse",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["somatic", "physical", "symptoms"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "substance-use-disorders",
    title: "Substance Use Disorders",
    subtitle: "Problematic Patterns of Substance Use",
    description: "Substance use disorders involve problematic patterns of substance use leading to clinically significant impairment or distress, including impaired control, social impairment, risky use, and pharmacological criteria.",
    branch: "Clinical",
    level: 2,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychological-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 750,
    y: 700,
    radius: 26,
    color: "#78350F",
    glow: false,
    iconName: "Pill",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["substance", "addiction", "dependence"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "neurodevelopmental-disorders",
    title: "Neurodevelopmental Disorders",
    subtitle: "Early-Onset Developmental Deficits",
    description: "Neurodevelopmental disorders are a group of conditions with onset in the developmental period, characterized by developmental deficits producing impairments in personal, social, academic, or occupational functioning.",
    branch: "Clinical",
    level: 2,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychological-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 600,
    y: 650,
    radius: 26,
    color: "#0369A1",
    glow: false,
    iconName: "Baby",
    difficulty: "Expert",
    estimatedMinutes: 55,
    tags: ["neurodevelopmental", "adhd", "autism"],
    prerequisites: ["psychological-disorders"]
  },
  {
    id: "sleep-disorders",
    title: "Sleep Disorders",
    subtitle: "Disturbances in Sleep Patterns and Quality",
    description: "Sleep-wake disorders involve problems with the quality, timing, and amount of sleep, resulting in daytime distress and impairment, including insomnia, hypersomnia, narcolepsy, and breathing-related sleep disorders.",
    branch: "Clinical",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "psychological-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 500,
    y: 550,
    radius: 26,
    color: "#4C1D95",
    glow: false,
    iconName: "Moon",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["sleep", "insomnia", "circadian"],
    prerequisites: ["psychological-disorders"]
  },
   {
    id: "psychotherapy",
    title: "Psychotherapy",
    subtitle: "The Therapeutic Treatment of Mental Disorders",
    description: "Psychotherapy encompasses a range of techniques and methods based on psychological principles, used to help individuals overcome emotional difficulties, modify maladaptive behaviors, and improve their quality of life through structured therapeutic relationships.",
    branch: "Clinical",
    level: 1,
    xp: 200,
    status: "available",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "clinical-psychology",
    children: ["cognitive-behavioral-therapy", "psychodynamic-therapy", "humanistic-therapy", "behavior-therapy", "family-therapy", "group-therapy", "motivational-interviewing", "positive-psychology", "evidence-based-practice"],
    unlocked: true,
    visible: true,
    x: 200,
    y: 400,
    radius: 32,
    color: "#059669",
    glow: true,
    iconName: "HeartHandshake",
    difficulty: "Expert",
    estimatedMinutes: 60,
    tags: ["therapy", "treatment", "intervention"],
    prerequisites: ["clinical-psychology"]
  },
  {
    id: "cognitive-behavioral-therapy",
    title: "Cognitive Behavioral Therapy",
    subtitle: "Changing Thoughts and Behaviors",
    description: "Cognitive behavioral therapy is a structured, time-limited, problem-focused approach that examines the relationships between thoughts, feelings, and behaviors, using cognitive restructuring and behavioral activation to reduce symptoms.",
    branch: "Clinical",
    level: 2,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychotherapy",
    children: ["rebt", "act", "dbt", "mindfulness-based-therapy"],
    unlocked: false,
    visible: true,
    x: 100,
    y: 250,
    radius: 26,
    color: "#3B82F6",
    glow: false,
    iconName: "BrainCircuit",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["cbt", "cognitive", "behavioral"],
    prerequisites: ["psychotherapy"]
  },
  {
    id: "rebt",
    title: "REBT",
    subtitle: "Rational Emotive Behavior Therapy",
    description: "Rational emotive behavior therapy, developed by Albert Ellis, focuses on identifying irrational beliefs, challenging distorted thinking patterns, and replacing absolute musts and shoulds with rational, flexible cognitions.",
    branch: "Clinical",
    level: 3,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "cognitive-behavioral-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 50,
    y: 150,
    radius: 22,
    color: "#1D4ED8",
    glow: false,
    iconName: "MessageSquare",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["rebt", "ellis", "irrational-beliefs"],
    prerequisites: ["cognitive-behavioral-therapy"]
  },
  {
    id: "act",
    title: "ACT",
    subtitle: "Acceptance and Commitment Therapy",
    description: "Acceptance and commitment therapy uses acceptance and mindfulness strategies alongside commitment and behavior change strategies to increase psychological flexibility and help individuals live in accordance with their values.",
    branch: "Clinical",
    level: 3,
    xp: 170,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "cognitive-behavioral-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 150,
    y: 100,
    radius: 22,
    color: "#10B981",
    glow: false,
    iconName: "GitCommit",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["act", "acceptance", "commitment"],
    prerequisites: ["cognitive-behavioral-therapy"]
  },
  {
    id: "dbt",
    title: "DBT",
    subtitle: "Dialectical Behavior Therapy",
    description: "Dialectical behavior therapy, developed by Marsha Linehan, integrates cognitive-behavioral techniques with mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness skills for treating borderline personality disorder and complex conditions.",
    branch: "Clinical",
    level: 3,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "cognitive-behavioral-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 250,
    y: 150,
    radius: 22,
    color: "#7C3AED",
    glow: false,
    iconName: "Shield",
    difficulty: "Expert",
    estimatedMinutes: 55,
    tags: ["dbt", "linehan", "borderline"],
    prerequisites: ["cognitive-behavioral-therapy"]
  },
  {
    id: "mindfulness-based-therapy",
    title: "Mindfulness-Based Therapy",
    subtitle: "Present-Moment Awareness in Treatment",
    description: "Mindfulness-based therapies incorporate meditation and present-moment awareness practices to reduce rumination, increase emotional regulation, and treat depression, anxiety, and stress-related conditions.",
    branch: "Clinical",
    level: 3,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "cognitive-behavioral-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 50,
    y: 50,
    radius: 22,
    color: "#14B8A6",
    glow: false,
    iconName: "Flower2",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["mindfulness", "meditation", "mbct"],
    prerequisites: ["cognitive-behavioral-therapy"]
  },
  {
    id: "behavior-therapy",
    title: "Behavior Therapy",
    subtitle: "Modifying Maladaptive Behaviors",
    description: "Behavior therapy applies principles of learning theory to modify maladaptive behaviors, using techniques such as reinforcement, punishment, modeling, and contingency management to establish adaptive behavioral patterns.",
    branch: "Clinical",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "psychotherapy",
    children: ["exposure-therapy", "systematic-desensitization"],
    unlocked: false,
    visible: true,
    x: 100,
    y: 550,
    radius: 26,
    color: "#F59E0B",
    glow: false,
    iconName: "Activity",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["behavior", "learning", "modification"],
    prerequisites: ["psychotherapy"]
  },
  {
    id: "exposure-therapy",
    title: "Exposure Therapy",
    subtitle: "Confronting Feared Stimuli",
    description: "Exposure therapy involves systematic and repeated confrontation with feared stimuli or situations in a safe environment, reducing anxiety through habituation, extinction, and inhibitory learning mechanisms.",
    branch: "Clinical",
    level: 3,
    xp: 170,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "behavior-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 50,
    y: 650,
    radius: 22,
    color: "#EF4444",
    glow: false,
    iconName: "Eye",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["exposure", "fear", "extinction"],
    prerequisites: ["behavior-therapy"]
  },
  {
    id: "systematic-desensitization",
    title: "Systematic Desensitization",
    subtitle: "Graduated Exposure with Relaxation",
    description: "Systematic desensitization, developed by Joseph Wolpe, combines progressive muscle relaxation with graduated exposure to anxiety-provoking stimuli in a hierarchical manner, replacing fear responses with relaxation.",
    branch: "Clinical",
    level: 3,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "behavior-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 150,
    y: 700,
    radius: 22,
    color: "#F97316",
    glow: false,
    iconName: "ListOrdered",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["desensitization", "wolpe", "hierarchy"],
    prerequisites: ["behavior-therapy"]
  },
  {
    id: "psychodynamic-therapy",
    title: "Psychodynamic Therapy",
    subtitle: "Exploring Unconscious Processes",
    description: "Psychodynamic therapy explores unconscious processes, early developmental experiences, defense mechanisms, and transference patterns to gain insight into current difficulties and achieve lasting personality change.",
    branch: "Clinical",
    level: 2,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychotherapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 300,
    y: 250,
    radius: 26,
    color: "#6366F1",
    glow: false,
    iconName: "Search",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["psychodynamic", "unconscious", "insight"],
    prerequisites: ["psychotherapy"]
  },
  {
    id: "humanistic-therapy",
    title: "Humanistic Therapy",
    subtitle: "Fostering Self-Actualization and Growth",
    description: "Humanistic therapy emphasizes personal growth, self-actualization, free will, and the inherent goodness of people, focusing on the whole person and their capacity for self-directed change and fulfillment.",
    branch: "Clinical",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "psychotherapy",
    children: ["client-centered-therapy"],
    unlocked: false,
    visible: true,
    x: 300,
    y: 550,
    radius: 26,
    color: "#EC4899",
    glow: false,
    iconName: "Sun",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["humanistic", "growth", "self-actualization"],
    prerequisites: ["psychotherapy"]
  },
  {
    id: "client-centered-therapy",
    title: "Client-Centered Therapy",
    subtitle: "Rogerian Non-Directive Approach",
    description: "Client-centered therapy, developed by Carl Rogers, provides a supportive therapeutic environment characterized by unconditional positive regard, empathy, and congruence, allowing clients to direct their own growth and self-discovery.",
    branch: "Clinical",
    level: 3,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "humanistic-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 350,
    y: 650,
    radius: 22,
    color: "#F472B6",
    glow: false,
    iconName: "UserCheck",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["rogers", "client-centered", "empathy"],
    prerequisites: ["humanistic-therapy"]
  },
  {
    id: "family-therapy",
    title: "Family Therapy",
    subtitle: "Treating the Family System",
    description: "Family therapy views psychological problems within the context of family systems, examining communication patterns, boundaries, alliances, and intergenerational dynamics to promote healthier family functioning.",
    branch: "Clinical",
    level: 2,
    xp: 170,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 11,
    parent: "psychotherapy",
    children: ["couples-therapy"],
    unlocked: false,
    visible: true,
    x: 400,
    y: 150,
    radius: 26,
    color: "#8B5CF6",
    glow: false,
    iconName: "Users",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["family", "systems", "relationships"],
    prerequisites: ["psychotherapy"]
  },
  {
    id: "couples-therapy",
    title: "Couples Therapy",
    subtitle: "Improving Romantic Partnerships",
    description: "Couples therapy focuses on improving communication, resolving conflicts, rebuilding trust, and enhancing intimacy between romantic partners using structured interventions tailored to relationship dynamics.",
    branch: "Clinical",
    level: 3,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "family-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 450,
    y: 50,
    radius: 22,
    color: "#A855F7",
    glow: false,
    iconName: "Heart",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["couples", "marriage", "relationship"],
    prerequisites: ["family-therapy"]
  },
  {
    id: "group-therapy",
    title: "Group Therapy",
    subtitle: "Therapeutic Healing in Group Settings",
    description: "Group therapy involves one or more therapists working with multiple clients simultaneously, leveraging group dynamics, peer support, universality, and interpersonal learning to facilitate psychological change.",
    branch: "Clinical",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "psychotherapy",
    children: ["play-therapy"],
    unlocked: false,
    visible: true,
    x: 400,
    y: 650,
    radius: 26,
    color: "#06B6D4",
    glow: false,
    iconName: "UsersRound",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["group", "peer-support", "dynamics"],
    prerequisites: ["psychotherapy"]
  },
  {
    id: "play-therapy",
    title: "Play Therapy",
    subtitle: "Expressive Treatment for Children",
    description: "Play therapy uses toys, games, and creative activities as therapeutic media to help children express emotions, process experiences, develop problem-solving skills, and resolve psychological difficulties in a developmentally appropriate manner.",
    branch: "Clinical",
    level: 3,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 9,
    parent: "group-therapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 450,
    y: 750,
    radius: 22,
    color: "#FBBF24",
    glow: false,
    iconName: "Gamepad2",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["play", "children", "expressive"],
    prerequisites: ["group-therapy"]
  },
  {
    id: "motivational-interviewing",
    title: "Motivational Interviewing",
    subtitle: "Collaborative Conversations for Change",
    description: "Motivational interviewing is a client-centered, directive method for enhancing intrinsic motivation to change by exploring and resolving ambivalence through open-ended questions, affirmations, reflective listening, and summarizing.",
    branch: "Clinical",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "psychotherapy",
    children: ["relapse-prevention"],
    unlocked: false,
    visible: true,
    x: 500,
    y: 400,
    radius: 26,
    color: "#14B8A6",
    glow: false,
    iconName: "MessageCircle",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["motivation", "ambivalence", "change"],
    prerequisites: ["psychotherapy"]
  },
  {
    id: "relapse-prevention",
    title: "Relapse Prevention",
    subtitle: "Sustaining Recovery and Preventing Setbacks",
    description: "Relapse prevention is a cognitive-behavioral approach designed to identify high-risk situations, develop coping strategies, enhance self-efficacy, and maintain behavioral changes by anticipating and managing potential setbacks.",
    branch: "Clinical",
    level: 3,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "motivational-interviewing",
    children: [],
    unlocked: false,
    visible: true,
    x: 550,
    y: 300,
    radius: 22,
    color: "#059669",
    glow: false,
    iconName: "RefreshCcw",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["relapse", "recovery", "maintenance"],
    prerequisites: ["motivational-interviewing"]
  },
  {
    id: "positive-psychology",
    title: "Positive Psychology",
    subtitle: "Building Strengths and Well-Being",
    description: "Positive psychology focuses on human strengths, virtues, well-being, and optimal functioning, moving beyond pathology to cultivate positive emotions, engagement, relationships, meaning, and accomplishment.",
    branch: "Clinical",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 10,
    parent: "psychotherapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 500,
    y: 500,
    radius: 26,
    color: "#F59E0B",
    glow: false,
    iconName: "Smile",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["positive", "strengths", "well-being"],
    prerequisites: ["psychotherapy"]
  },
  {
    id: "evidence-based-practice",
    title: "Evidence-Based Practice",
    subtitle: "Integrating Research with Clinical Expertise",
    description: "Evidence-based practice in clinical psychology integrates the best available research evidence with clinical expertise and patient values to make informed decisions about assessment and intervention, ensuring effective and accountable care.",
    branch: "Clinical",
    level: 2,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 12,
    parent: "psychotherapy",
    children: [],
    unlocked: false,
    visible: true,
    x: 500,
    y: 600,
    radius: 26,
    color: "#3B82F6",
    glow: false,
    iconName: "BookOpen",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["evidence", "research", "integration"],
    prerequisites: ["psychotherapy"]
  }
];
