// ============================================================
// SECTION: Type Definitions
// ============================================================

interface TreeNode {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  branch: string;
  level: number;
  xp: number;
  status: 'mastered' | 'available' | 'locked';
  progress: number;
  completed: number;
  total: number;
  parent: string | null;
  children: string[];
  unlocked: boolean;
  visible: boolean;
  x: number;
  y: number;
  radius: number;
  color: string;
  glow: string;
  iconName: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  estimatedMinutes: number;
  tags: string[];
  prerequisites: string[];
}

// ============================================================
// SECTION: Developmental Psychology Nodes
// ============================================================

export const developmentalNodes: TreeNode[] = [
  {
    id: "developmental-psychology",
    title: "Developmental Psychology",
    subtitle: "The Study of Lifespan Changes",
    description: "Developmental psychology examines how and why human beings change over the course of their life, from conception to death. It encompasses physical, cognitive, social, intellectual, perceptual, personality, and emotional growth.",
    branch: "developmental",
    level: 0,
    xp: 0,
    status: "mastered",
    progress: 100,
    completed: 1,
    total: 1,
    parent: null,
    children: ["prenatal-development", "infancy", "middle-childhood", "adolescence", "emerging-adulthood", "adulthood", "aging", "developmental-disorders"],
    unlocked: true,
    visible: true,
    x: 500,
    y: 100,
    radius: 45,
    color: "#8B5CF6",
    glow: "#A78BFA",
    iconName: "Brain",
    difficulty: "beginner",
    estimatedMinutes: 0,
    tags: ["lifespan", "growth", "change"],
    prerequisites: [],
  },

  // ─── PRENATAL DEVELOPMENT ───
  {
    id: "prenatal-development",
    title: "Prenatal Development",
    subtitle: "From Conception to Birth",
    description: "Prenatal development spans three stages: germinal, embryonic, and fetal. Key processes include cell division, differentiation, and organ formation. Environmental factors such as teratogens, maternal nutrition, and stress significantly influence development.",
    branch: "developmental",
    level: 1,
    xp: 60,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "developmental-psychology",
    children: ["germinal-stage", "embryonic-stage", "fetal-stage", "teratogens"],
    unlocked: true,
    visible: true,
    x: 150,
    y: 250,
    radius: 38,
    color: "#EC4899",
    glow: "#F472B6",
    iconName: "Baby",
    difficulty: "beginner",
    estimatedMinutes: 25,
    tags: ["conception", "pregnancy", "prenatal"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "germinal-stage",
    title: "Germinal Stage",
    subtitle: "First Two Weeks",
    description: "The germinal stage begins at conception and lasts about two weeks. The zygote undergoes rapid cell division and implants in the uterine wall. Approximately 50-75% of zygotes fail to implant successfully.",
    branch: "developmental",
    level: 2,
    xp: 45,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "prenatal-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: 400,
    radius: 30,
    color: "#EC4899",
    glow: "#F472B6",
    iconName: "Dna",
    difficulty: "beginner",
    estimatedMinutes: 15,
    tags: ["zygote", "implantation", "cell-division"],
    prerequisites: ["prenatal-development"],
  },
  {
    id: "embryonic-stage",
    title: "Embryonic Stage",
    subtitle: "Weeks 3 to 8",
    description: "The embryonic stage is the most critical period for organogenesis. The neural tube forms, the heart begins to beat, and major organ systems develop. This stage is highly vulnerable to teratogens.",
    branch: "developmental",
    level: 2,
    xp: 55,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "prenatal-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 150,
    y: 400,
    radius: 30,
    color: "#EC4899",
    glow: "#F472B6",
    iconName: "Heart",
    difficulty: "beginner",
    estimatedMinutes: 20,
    tags: ["embryo", "organogenesis", "neural-tube"],
    prerequisites: ["prenatal-development"],
  },
  {
    id: "fetal-stage",
    title: "Fetal Stage",
    subtitle: "Week 9 to Birth",
    description: "During the fetal stage, the organism grows rapidly and organ systems mature. Brain development accelerates, reflexes emerge, and the fetus becomes viable around 24 weeks. Sensory capabilities develop in the third trimester.",
    branch: "developmental",
    level: 2,
    xp: 50,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "prenatal-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 220,
    y: 400,
    radius: 30,
    color: "#EC4899",
    glow: "#F472B6",
    iconName: "Baby",
    difficulty: "beginner",
    estimatedMinutes: 18,
    tags: ["fetus", "viability", "brain-development"],
    prerequisites: ["prenatal-development"],
  },
  {
    id: "teratogens",
    title: "Teratogens",
    subtitle: "Environmental Hazards",
    description: "Teratogens are agents that can cause birth defects. Common teratogens include alcohol (FAS), tobacco, drugs, infections (rubella, Zika), radiation, and maternal stress. Timing of exposure determines severity and type of effect.",
    branch: "developmental",
    level: 2,
    xp: 65,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "prenatal-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 290,
    y: 400,
    radius: 30,
    color: "#EC4899",
    glow: "#F472B6",
    iconName: "ShieldAlert",
    difficulty: "beginner",
    estimatedMinutes: 22,
    tags: ["fetal-alcohol-syndrome", "birth-defects", "risk-factors"],
    prerequisites: ["prenatal-development"],
  },

  // ─── INFANCY ───
  {
    id: "infancy",
    title: "Infancy",
    subtitle: "Birth to 24 Months",
    description: "Infancy is marked by rapid physical growth, sensorimotor development, and the emergence of social bonds. Key milestones include motor skill acquisition, sensory refinement, and the foundation of cognitive processing.",
    branch: "developmental",
    level: 1,
    xp: 70,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-psychology",
    children: ["attachment", "piaget-sensorimotor", "language-development", "infant-motor-development", "infant-perception"],
    unlocked: true,
    visible: true,
    x: 350,
    y: 250,
    radius: 38,
    color: "#F59E0B",
    glow: "#FBBF24",
    iconName: "Baby",
    difficulty: "beginner",
    estimatedMinutes: 30,
    tags: ["newborn", "milestones", "sensorimotor"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "infant-motor-development",
    title: "Infant Motor Development",
    subtitle: "Reflexes to Coordinated Movement",
    description: "Motor development follows cephalocaudal and proximodistal patterns. Primitive reflexes (rooting, grasping) give way to voluntary movements. Major milestones include head control, sitting, crawling, and walking.",
    branch: "developmental",
    level: 2,
    xp: 50,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "infancy",
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: 400,
    radius: 30,
    color: "#F59E0B",
    glow: "#FBBF24",
    iconName: "Footprints",
    difficulty: "beginner",
    estimatedMinutes: 18,
    tags: ["reflexes", "motor-milestones", "gross-motor"],
    prerequisites: ["infancy"],
  },
  {
    id: "infant-perception",
    title: "Infant Perception",
    subtitle: "Sensory and Perceptual Abilities",
    description: "Newborns possess remarkable perceptual capabilities. They prefer faces, can discriminate speech sounds, and show depth perception by 4 months. Visual acuity improves from 20/400 at birth to near adult levels by 6 months.",
    branch: "developmental",
    level: 2,
    xp: 55,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "infancy",
    children: [],
    unlocked: false,
    visible: true,
    x: 350,
    y: 400,
    radius: 30,
    color: "#F59E0B",
    glow: "#FBBF24",
    iconName: "Eye",
    difficulty: "beginner",
    estimatedMinutes: 20,
    tags: ["visual-perception", "auditory", "face-preference"],
    prerequisites: ["infancy"],
  },

  // ─── ATTACHMENT ───
  {
    id: "attachment",
    title: "Attachment",
    subtitle: "Emotional Bonds in Early Life",
    description: "Attachment theory, developed by John Bowlby and Mary Ainsworth, describes the emotional bond between infants and caregivers. Secure attachment promotes healthy social and emotional development, while insecure attachment predicts later difficulties.",
    branch: "developmental",
    level: 1,
    xp: 120,
    status: "available",
    progress: 0,
    completed: 0,
    total: 6,
    parent: "developmental-psychology",
    children: ["bowlby-attachment-theory", "ainsworth-strange-situation", "attachment-styles", "internal-working-models", "attachment-disorders"],
    unlocked: true,
    visible: true,
    x: 500,
    y: 250,
    radius: 40,
    color: "#EF4444",
    glow: "#F87171",
    iconName: "Heart",
    difficulty: "intermediate",
    estimatedMinutes: 35,
    tags: ["bonding", "caregiver", "emotional-security"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "bowlby-attachment-theory",
    title: "Bowlby's Attachment Theory",
    subtitle: "Evolutionary Basis of Bonding",
    description: "John Bowlby proposed that attachment is an innate biological system promoting survival. Infants are biologically predisposed to form attachments, using behaviors like crying and smiling to maintain proximity to caregivers. The theory emphasizes the critical period for attachment formation.",
    branch: "developmental",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "attachment",
    children: [],
    unlocked: false,
    visible: true,
    x: 420,
    y: 400,
    radius: 32,
    color: "#EF4444",
    glow: "#F87171",
    iconName: "Link",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["evolutionary", "proximity-seeking", "survival"],
    prerequisites: ["attachment"],
  },
  {
    id: "ainsworth-strange-situation",
    title: "Strange Situation",
    subtitle: "Ainsworth's Classification Method",
    description: "Mary Ainsworth developed the Strange Situation procedure to assess attachment quality. Through eight episodes involving separations and reunions with the caregiver, infants are classified as secure, avoidant, ambivalent-resistant, or disorganized.",
    branch: "developmental",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "attachment",
    children: [],
    unlocked: false,
    visible: true,
    x: 500,
    y: 400,
    radius: 32,
    color: "#EF4444",
    glow: "#F87171",
    iconName: "Search",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["assessment", "classification", "experimental-method"],
    prerequisites: ["attachment"],
  },
  {
    id: "attachment-styles",
    title: "Attachment Styles",
    subtitle: "Secure and Insecure Patterns",
    description: "Attachment styles include secure (60-65%), avoidant (20%), ambivalent-resistant (10-15%), and disorganized (5-10%). These patterns influence adult relationships, emotional regulation, and mental health outcomes across the lifespan.",
    branch: "developmental",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "attachment",
    children: [],
    unlocked: false,
    visible: true,
    x: 580,
    y: 400,
    radius: 32,
    color: "#EF4444",
    glow: "#F87171",
    iconName: "Users",
    difficulty: "intermediate",
    estimatedMinutes: 28,
    tags: ["secure", "avoidant", "ambivalent", "disorganized"],
    prerequisites: ["attachment"],
  },
  {
    id: "internal-working-models",
    title: "Internal Working Models",
    subtitle: "Mental Representations of Relationships",
    description: "Bowlby proposed that children develop internal working models based on attachment experiences. These cognitive schemas guide expectations about relationships, self-worth, and others' availability, influencing behavior into adulthood.",
    branch: "developmental",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "attachment",
    children: [],
    unlocked: false,
    visible: true,
    x: 660,
    y: 400,
    radius: 32,
    color: "#EF4444",
    glow: "#F87171",
    iconName: "Brain",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["schemas", "mental-models", "adult-relationships"],
    prerequisites: ["attachment"],
  },
  {
    id: "attachment-disorders",
    title: "Attachment Disorders",
    subtitle: "When Attachment Fails",
    description: "Reactive Attachment Disorder (RAD) and Disinhibited Social Engagement Disorder (DSED) result from severe early deprivation or maltreatment. Symptoms include emotional withdrawal, indiscriminate friendliness, and impaired social reciprocity.",
    branch: "developmental",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "attachment",
    children: [],
    unlocked: false,
    visible: true,
    x: 740,
    y: 400,
    radius: 32,
    color: "#EF4444",
    glow: "#F87171",
    iconName: "AlertTriangle",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["RAD", "DSED", "maltreatment", "deprivation"],
    prerequisites: ["attachment"],
  },

  // ─── PIAGET ───
  {
    id: "piaget-sensorimotor",
    title: "Piaget: Sensorimotor Stage",
    subtitle: "Birth to 2 Years",
    description: "Piaget's first stage involves learning through sensory experiences and motor actions. Key achievements include object permanence (understanding objects exist when out of sight), deferred imitation, and the beginning of symbolic thought.",
    branch: "developmental",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "infancy",
    children: ["piaget-preoperational", "piaget-concrete-operational", "piaget-formal-operational"],
    unlocked: false,
    visible: true,
    x: 420,
    y: 400,
    radius: 32,
    color: "#3B82F6",
    glow: "#60A5FA",
    iconName: "Hand",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["object-permanence", "schemas", "assimilation"],
    prerequisites: ["infancy"],
  },
  {
    id: "piaget-preoperational",
    title: "Piaget: Preoperational Stage",
    subtitle: "Ages 2 to 7",
    description: "Children develop symbolic thinking, language, and pretend play. Limitations include egocentrism (difficulty taking others' perspectives), centration (focusing on one aspect), and lack of conservation understanding. Animism and artificialism are common.",
    branch: "developmental",
    level: 3,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "piaget-sensorimotor",
    children: [],
    unlocked: false,
    visible: true,
    x: 380,
    y: 550,
    radius: 30,
    color: "#3B82F6",
    glow: "#60A5FA",
    iconName: "Palette",
    difficulty: "intermediate",
    estimatedMinutes: 28,
    tags: ["egocentrism", "conservation", "symbolic-play"],
    prerequisites: ["piaget-sensorimotor"],
  },
  {
    id: "piaget-concrete-operational",
    title: "Piaget: Concrete Operational",
    subtitle: "Ages 7 to 11",
    description: "Children gain logical reasoning about concrete events. They understand conservation, reversibility, and classification. However, abstract and hypothetical thinking remain challenging. Seriation and transitive inference emerge.",
    branch: "developmental",
    level: 3,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "piaget-sensorimotor",
    children: [],
    unlocked: false,
    visible: true,
    x: 460,
    y: 550,
    radius: 30,
    color: "#3B82F6",
    glow: "#60A5FA",
    iconName: "Box",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["conservation", "classification", "logic"],
    prerequisites: ["piaget-sensorimotor"],
  },
  {
    id: "piaget-formal-operational",
    title: "Piaget: Formal Operational",
    subtitle: "Ages 11 and Beyond",
    description: "Adolescents develop abstract reasoning, hypothetical-deductive thinking, and systematic problem-solving. They can consider multiple variables, think about possibilities, and engage in metacognition. Not all individuals reach this stage.",
    branch: "developmental",
    level: 3,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "piaget-sensorimotor",
    children: [],
    unlocked: false,
    visible: true,
    x: 540,
    y: 550,
    radius: 30,
    color: "#3B82F6",
    glow: "#60A5FA",
    iconName: "Lightbulb",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["abstract-reasoning", "hypothetical", "metacognition"],
    prerequisites: ["piaget-sensorimotor"],
  },

  // ─── VYGOTSKY ───
  {
    id: "vygotsky",
    title: "Vygotsky's Sociocultural Theory",
    subtitle: "Social Context of Development",
    description: "Lev Vygotsky emphasized the role of social interaction and culture in cognitive development. Key concepts include the Zone of Proximal Development (ZPD), scaffolding, and the importance of language as a tool for thought.",
    branch: "developmental",
    level: 1,
    xp: 150,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-psychology",
    children: ["zone-of-proximal-development", "scaffolding", "private-speech", "cultural-tools"],
    unlocked: true,
    visible: true,
    x: 650,
    y: 250,
    radius: 40,
    color: "#10B981",
    glow: "#34D399",
    iconName: "Users",
    difficulty: "intermediate",
    estimatedMinutes: 35,
    tags: ["social-learning", "culture", "language"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "zone-of-proximal-development",
    title: "Zone of Proximal Development",
    subtitle: "The Gap Between Independent and Guided Performance",
    description: "The ZPD is the distance between what a learner can do independently and what they can achieve with guidance. Effective instruction targets this zone, challenging learners just beyond their current capabilities with appropriate support.",
    branch: "developmental",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "vygotsky",
    children: [],
    unlocked: false,
    visible: true,
    x: 600,
    y: 400,
    radius: 32,
    color: "#10B981",
    glow: "#34D399",
    iconName: "Target",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["ZPD", "potential", "instruction"],
    prerequisites: ["vygotsky"],
  },
  {
    id: "scaffolding",
    title: "Scaffolding",
    subtitle: "Temporary Support for Learning",
    description: "Scaffolding involves providing temporary support that is gradually removed as the learner gains competence. Effective scaffolding adjusts to the learner's needs, fading as skills develop. It is central to guided participation and apprenticeship.",
    branch: "developmental",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "vygotsky",
    children: [],
    unlocked: false,
    visible: true,
    x: 680,
    y: 400,
    radius: 32,
    color: "#10B981",
    glow: "#34D399",
    iconName: "Layers",
    difficulty: "intermediate",
    estimatedMinutes: 22,
    tags: ["support", "guidance", "fading"],
    prerequisites: ["vygotsky"],
  },
  {
    id: "private-speech",
    title: "Private Speech",
    subtitle: "Self-Regulation Through Language",
    description: "Vygotsky viewed private speech (talking to oneself) as a tool for self-regulation and planning, not merely egocentric behavior. It evolves into inner speech, becoming the foundation of verbal thought and executive function.",
    branch: "developmental",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "vygotsky",
    children: [],
    unlocked: false,
    visible: true,
    x: 760,
    y: 400,
    radius: 32,
    color: "#10B981",
    glow: "#34D399",
    iconName: "MessageCircle",
    difficulty: "intermediate",
    estimatedMinutes: 20,
    tags: ["self-regulation", "inner-speech", "planning"],
    prerequisites: ["vygotsky"],
  },
  {
    id: "cultural-tools",
    title: "Cultural Tools",
    subtitle: "Mediators of Cognitive Development",
    description: "Vygotsky emphasized that cognitive development is mediated by cultural tools including language, writing, number systems, and technology. These tools are transmitted through social interaction and shape how individuals think and solve problems.",
    branch: "developmental",
    level: 2,
    xp: 145,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "vygotsky",
    children: [],
    unlocked: false,
    visible: true,
    x: 840,
    y: 400,
    radius: 32,
    color: "#10B981",
    glow: "#34D399",
    iconName: "Tool",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["mediation", "symbols", "technology"],
    prerequisites: ["vygotsky"],
  },

  // ─── LANGUAGE DEVELOPMENT ───
  {
    id: "language-development",
    title: "Language Development",
    subtitle: "From Babbling to Complex Speech",
    description: "Language development follows a universal sequence: cooing (2-4 months), babbling (4-6 months), first words (10-14 months), two-word combinations (18-24 months), and telegraphic speech (2-3 years). Theories include behaviorist, nativist, and interactionist perspectives.",
    branch: "developmental",
    level: 1,
    xp: 140,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-psychology",
    children: ["language-milestones", "nativist-theory", "interactionist-theory", "bilingualism", "critical-period"],
    unlocked: true,
    visible: true,
    x: 800,
    y: 250,
    radius: 40,
    color: "#8B5CF6",
    glow: "#A78BFA",
    iconName: "MessageSquare",
    difficulty: "intermediate",
    estimatedMinutes: 35,
    tags: ["speech", "communication", "acquisition"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "language-milestones",
    title: "Language Milestones",
    subtitle: "Typical Sequence of Acquisition",
    description: "Key milestones include prelinguistic vocalizations, first words, vocabulary spurt (18-24 months), two-word stage, overregularization errors, and complex sentence formation. Individual variation is substantial but the sequence is remarkably consistent across cultures.",
    branch: "developmental",
    level: 2,
    xp: 100,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "language-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 750,
    y: 400,
    radius: 32,
    color: "#8B5CF6",
    glow: "#A78BFA",
    iconName: "List",
    difficulty: "beginner",
    estimatedMinutes: 22,
    tags: ["milestones", "vocabulary", "syntax"],
    prerequisites: ["language-development"],
  },
  {
    id: "nativist-theory",
    title: "Nativist Theory",
    subtitle: "Chomsky and Universal Grammar",
    description: "Noam Chomsky proposed that humans possess an innate Language Acquisition Device (LAD) containing universal grammar. Children acquire language rapidly despite limited input, suggesting biological preparedness. Evidence includes the critical period and creole languages.",
    branch: "developmental",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "language-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 830,
    y: 400,
    radius: 32,
    color: "#8B5CF6",
    glow: "#A78BFA",
    iconName: "Dna",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["Chomsky", "LAD", "universal-grammar"],
    prerequisites: ["language-development"],
  },
  {
    id: "interactionist-theory",
    title: "Interactionist Theory",
    subtitle: "Biology and Environment Together",
    description: "Interactionist theories, including social interactionist and emergentist approaches, emphasize that language development results from the interplay between biological predispositions and environmental input. Caregiver responsiveness and joint attention are critical.",
    branch: "developmental",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "language-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 910,
    y: 400,
    radius: 32,
    color: "#8B5CF6",
    glow: "#A78BFA",
    iconName: "GitMerge",
    difficulty: "intermediate",
    estimatedMinutes: 28,
    tags: ["interaction", "environment", "biology"],
    prerequisites: ["language-development"],
  },
  {
    id: "bilingualism",
    title: "Bilingualism",
    subtitle: "Dual Language Acquisition",
    description: "Bilingual children develop two linguistic systems simultaneously or sequentially. Research shows cognitive advantages in executive function, metalinguistic awareness, and perspective-taking. Code-switching is a normal, sophisticated linguistic skill.",
    branch: "developmental",
    level: 2,
    xp: 170,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "language-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 990,
    y: 400,
    radius: 32,
    color: "#8B5CF6",
    glow: "#A78BFA",
    iconName: "Globe",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["dual-language", "cognitive-advantages", "code-switching"],
    prerequisites: ["language-development"],
  },
  {
    id: "critical-period",
    title: "Critical Period for Language",
    subtitle: "Sensitive Windows of Opportunity",
    description: "The critical period hypothesis suggests there is an optimal window for language acquisition, ending around puberty. Evidence from feral children, deaf individuals without early sign language exposure, and second language acquisition supports this concept.",
    branch: "developmental",
    level: 2,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "language-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 1070,
    y: 400,
    radius: 32,
    color: "#8B5CF6",
    glow: "#A78BFA",
    iconName: "Clock",
    difficulty: "intermediate",
    estimatedMinutes: 28,
    tags: ["sensitive-period", "feral-children", "plasticity"],
    prerequisites: ["language-development"],
  },

  // ─── MORAL DEVELOPMENT ───
  {
    id: "moral-development",
    title: "Moral Development",
    subtitle: "The Growth of Ethical Reasoning",
    description: "Moral development examines how individuals distinguish right from wrong and develop ethical reasoning. Major theories include Kohlberg's stages of moral reasoning, Gilligan's ethics of care, and Eisenberg's prosocial moral reasoning.",
    branch: "developmental",
    level: 1,
    xp: 160,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-psychology",
    children: ["kohlberg-moral-stages", "gilligan-ethics-of-care", "prosocial-behavior", "moral-emotions"],
    unlocked: true,
    visible: true,
    x: 950,
    y: 250,
    radius: 40,
    color: "#F97316",
    glow: "#FB923C",
    iconName: "Scale",
    difficulty: "intermediate",
    estimatedMinutes: 35,
    tags: ["ethics", "reasoning", "values"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "kohlberg-moral-stages",
    title: "Kohlberg's Stages",
    subtitle: "Levels of Moral Reasoning",
    description: "Lawrence Kohlberg proposed three levels of moral development: preconventional (punishment and reward), conventional (social rules and approval), and postconventional (abstract principles and universal ethics). Each level contains two stages. Research using moral dilemmas supports this progression.",
    branch: "developmental",
    level: 2,
    xp: 170,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 6,
    parent: "moral-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 900,
    y: 400,
    radius: 32,
    color: "#F97316",
    glow: "#FB923C",
    iconName: "TrendingUp",
    difficulty: "intermediate",
    estimatedMinutes: 35,
    tags: ["preconventional", "conventional", "postconventional"],
    prerequisites: ["moral-development"],
  },
  {
    id: "gilligan-ethics-of-care",
    title: "Gilligan's Ethics of Care",
    subtitle: "A Different Moral Voice",
    description: "Carol Gilligan critiqued Kohlberg's male-centered approach, proposing that women often reason from an ethics of care emphasizing relationships, responsibility, and context rather than abstract justice. Her work expanded moral development theory.",
    branch: "developmental",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "moral-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 980,
    y: 400,
    radius: 32,
    color: "#F97316",
    glow: "#FB923C",
    iconName: "Heart",
    difficulty: "intermediate",
    estimatedMinutes: 28,
    tags: ["care", "relationships", "gender"],
    prerequisites: ["moral-development"],
  },
  {
    id: "prosocial-behavior",
    title: "Prosocial Behavior",
    subtitle: "Helping, Sharing, and Cooperating",
    description: "Prosocial behavior emerges in toddlerhood and develops through childhood. Factors include empathy, perspective-taking, parental modeling, and cultural values. Altruism, sharing, and cooperation show developmental progression with individual differences.",
    branch: "developmental",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "moral-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 1060,
    y: 400,
    radius: 32,
    color: "#F97316",
    glow: "#FB923C",
    iconName: "HelpingHand",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["altruism", "empathy", "cooperation"],
    prerequisites: ["moral-development"],
  },
  {
    id: "moral-emotions",
    title: "Moral Emotions",
    subtitle: "Guilt, Shame, and Pride",
    description: "Moral emotions including guilt, shame, embarrassment, and pride develop in early childhood and guide moral behavior. Self-conscious emotions require self-awareness and emerge around 18-24 months. Cultural variations exist in the emphasis on different moral emotions.",
    branch: "developmental",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "moral-development",
    children: [],
    unlocked: false,
    visible: true,
    x: 1140,
    y: 400,
    radius: 32,
    color: "#F97316",
    glow: "#FB923C",
    iconName: "Smile",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["guilt", "shame", "self-conscious"],
    prerequisites: ["moral-development"],
  },

  // ─── ERIKSON ───
  {
    id: "erikson",
    title: "Erikson's Psychosocial Stages",
    subtitle: "Eight Crises Across the Lifespan",
    description: "Erik Erikson proposed eight psychosocial stages, each presenting a crisis between a positive and negative outcome. Successful resolution yields a virtue (e.g., trust, autonomy, identity). Stages span from infancy through old age, emphasizing lifelong development.",
    branch: "developmental",
    level: 1,
    xp: 200,
    status: "available",
    progress: 0,
    completed: 0,
    total: 8,
    parent: "developmental-psychology",
    children: ["erikson-trust-vs-mistrust", "erikson-autonomy-vs-shame", "erikson-initiative-vs-guilt", "erikson-industry-vs-inferiority", "erikson-identity-vs-role-confusion", "erikson-intimacy-vs-isolation", "erikson-generativity-vs-stagnation", "erikson-integrity-vs-despair"],
    unlocked: true,
    visible: true,
    x: 1100,
    y: 250,
    radius: 42,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "Layers",
    difficulty: "advanced",
    estimatedMinutes: 45,
    tags: ["crisis", "virtue", "lifespan"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "erikson-trust-vs-mistrust",
    title: "Trust vs. Mistrust",
    subtitle: "Infancy (0-1 Year)",
    description: "The first psychosocial crisis involves developing basic trust in caregivers and the world. Consistent, responsive caregiving fosters trust and the virtue of hope. Inconsistent care leads to mistrust and insecurity.",
    branch: "developmental",
    level: 2,
    xp: 80,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "erikson",
    children: [],
    unlocked: false,
    visible: true,
    x: 900,
    y: 400,
    radius: 28,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "Shield",
    difficulty: "beginner",
    estimatedMinutes: 15,
    tags: ["trust", "hope", "infancy"],
    prerequisites: ["erikson"],
  },
  {
    id: "erikson-autonomy-vs-shame",
    title: "Autonomy vs. Shame",
    subtitle: "Toddlerhood (1-3 Years)",
    description: "Toddlers strive for independence and self-control. Supportive environments foster autonomy and willpower. Excessive criticism or control leads to shame and doubt about one's capabilities.",
    branch: "developmental",
    level: 2,
    xp: 90,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "erikson",
    children: [],
    unlocked: false,
    visible: true,
    x: 960,
    y: 400,
    radius: 28,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "Move",
    difficulty: "beginner",
    estimatedMinutes: 15,
    tags: ["autonomy", "will", "toddler"],
    prerequisites: ["erikson"],
  },
  {
    id: "erikson-initiative-vs-guilt",
    title: "Initiative vs. Guilt",
    subtitle: "Early Childhood (3-6 Years)",
    description: "Preschoolers explore their environment and initiate activities. Encouragement fosters initiative and purpose. Overly restrictive environments produce guilt about ambitions and desires.",
    branch: "developmental",
    level: 2,
    xp: 100,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "erikson",
    children: [],
    unlocked: false,
    visible: true,
    x: 1020,
    y: 400,
    radius: 28,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "Rocket",
    difficulty: "beginner",
    estimatedMinutes: 18,
    tags: ["initiative", "purpose", "preschool"],
    prerequisites: ["erikson"],
  },
  {
    id: "erikson-industry-vs-inferiority",
    title: "Industry vs. Inferiority",
    subtitle: "Middle Childhood (6-12 Years)",
    description: "School-age children develop competence through achievement and skill mastery. Positive experiences foster industry and competence. Repeated failure or negative comparison leads to feelings of inferiority.",
    branch: "developmental",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "erikson",
    children: [],
    unlocked: false,
    visible: true,
    x: 1080,
    y: 400,
    radius: 28,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "Award",
    difficulty: "beginner",
    estimatedMinutes: 18,
    tags: ["industry", "competence", "school-age"],
    prerequisites: ["erikson"],
  },
  {
    id: "erikson-identity-vs-role-confusion",
    title: "Identity vs. Role Confusion",
    subtitle: "Adolescence (12-18 Years)",
    description: "Adolescents explore identity in areas including vocation, ideology, and sexuality. Successful exploration yields a coherent identity. Failure to commit leads to role confusion and weak sense of self.",
    branch: "developmental",
    level: 2,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "erikson",
    children: [],
    unlocked: false,
    visible: true,
    x: 1140,
    y: 400,
    radius: 30,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "Fingerprint",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["identity", "exploration", "adolescence"],
    prerequisites: ["erikson"],
  },
  {
    id: "erikson-intimacy-vs-isolation",
    title: "Intimacy vs. Isolation",
    subtitle: "Young Adulthood (18-40 Years)",
    description: "Young adults seek committed relationships and intimate connections. Success yields love and companionship. Fear of vulnerability leads to isolation and loneliness.",
    branch: "developmental",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "erikson",
    children: [],
    unlocked: false,
    visible: true,
    x: 1200,
    y: 400,
    radius: 28,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "Heart",
    difficulty: "intermediate",
    estimatedMinutes: 22,
    tags: ["intimacy", "love", "young-adult"],
    prerequisites: ["erikson"],
  },
  {
    id: "erikson-generativity-vs-stagnation",
    title: "Generativity vs. Stagnation",
    subtitle: "Middle Adulthood (40-65 Years)",
    description: "Middle-aged adults focus on contributing to the next generation through parenting, mentoring, or productive work. Success yields care and generativity. Self-absorption leads to stagnation and unproductivity.",
    branch: "developmental",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "erikson",
    children: [],
    unlocked: false,
    visible: true,
    x: 1260,
    y: 400,
    radius: 28,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "TreePine",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["generativity", "care", "middle-age"],
    prerequisites: ["erikson"],
  },
  {
    id: "erikson-integrity-vs-despair",
    title: "Integrity vs. Despair",
    subtitle: "Late Adulthood (65+ Years)",
    description: "Older adults reflect on their lives. Acceptance of one's life journey yields wisdom and integrity. Regret and dissatisfaction lead to despair and fear of death.",
    branch: "developmental",
    level: 2,
    xp: 170,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "erikson",
    children: [],
    unlocked: false,
    visible: true,
    x: 1320,
    y: 400,
    radius: 28,
    color: "#06B6D4",
    glow: "#22D3EE",
    iconName: "Sunset",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["integrity", "wisdom", "elderly"],
    prerequisites: ["erikson"],
  },

  // ─── MIDDLE CHILDHOOD ───
  {
    id: "middle-childhood",
    title: "Middle Childhood",
    subtitle: "Ages 6 to 12",
    description: "Middle childhood is characterized by steady physical growth, concrete operational thinking, peer relationship development, and school achievement. Self-concept becomes more complex, and moral reasoning advances from preconventional to conventional levels.",
    branch: "developmental",
    level: 1,
    xp: 130,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-psychology",
    children: ["cognitive-development-middle-childhood", "peer-relationships", "self-concept-development", "school-achievement"],
    unlocked: true,
    visible: true,
    x: 1250,
    y: 250,
    radius: 40,
    color: "#84CC16",
    glow: "#A3E635",
    iconName: "School",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["school-age", "concrete-operations", "peers"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "cognitive-development-middle-childhood",
    title: "Cognitive Development",
    subtitle: "Concrete Operations and Memory",
    description: "Children develop logical reasoning about concrete objects, improved memory strategies (rehearsal, organization, elaboration), and metacognitive awareness. Information processing approaches highlight working memory and processing speed improvements.",
    branch: "developmental",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "middle-childhood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1200,
    y: 400,
    radius: 32,
    color: "#84CC16",
    glow: "#A3E635",
    iconName: "Brain",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["memory", "logic", "metacognition"],
    prerequisites: ["middle-childhood"],
  },
  {
    id: "peer-relationships",
    title: "Peer Relationships",
    subtitle: "Friendship and Social Status",
    description: "Peer relationships become increasingly important. Friendship quality improves, social comparison intensifies, and peer acceptance influences self-esteem. Bullying, peer rejection, and popularity dynamics emerge as significant social factors.",
    branch: "developmental",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "middle-childhood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1280,
    y: 400,
    radius: 32,
    color: "#84CC16",
    glow: "#A3E635",
    iconName: "Users",
    difficulty: "intermediate",
    estimatedMinutes: 22,
    tags: ["friendship", "bullying", "social-status"],
    prerequisites: ["middle-childhood"],
  },
  {
    id: "self-concept-development",
    title: "Self-Concept Development",
    subtitle: "Understanding the Self",
    description: "Self-concept becomes more differentiated and realistic. Children develop self-esteem based on competence in various domains, social comparisons, and feedback from significant others. The self becomes increasingly stable and internalized.",
    branch: "developmental",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "middle-childhood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1360,
    y: 400,
    radius: 32,
    color: "#84CC16",
    glow: "#A3E635",
    iconName: "User",
    difficulty: "intermediate",
    estimatedMinutes: 20,
    tags: ["self-esteem", "identity", "social-comparison"],
    prerequisites: ["middle-childhood"],
  },
  {
    id: "school-achievement",
    title: "School Achievement",
    subtitle: "Academic Development and Motivation",
    description: "Academic skills advance significantly. Reading comprehension, mathematical reasoning, and writing proficiency improve. Achievement motivation, attributional style, and teacher expectations influence academic outcomes.",
    branch: "developmental",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "middle-childhood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1440,
    y: 400,
    radius: 32,
    color: "#84CC16",
    glow: "#A3E635",
    iconName: "BookOpen",
    difficulty: "beginner",
    estimatedMinutes: 20,
    tags: ["academics", "motivation", "literacy"],
    prerequisites: ["middle-childhood"],
  },

  // ─── ADOLESCENCE ───
  {
    id: "adolescence",
    title: "Adolescence",
    subtitle: "Ages 12 to 18",
    description: "Adolescence involves rapid physical changes (puberty), abstract cognitive development, identity exploration, and intensified peer relationships. Risk-taking increases due to brain development patterns and social influences.",
    branch: "developmental",
    level: 1,
    xp: 180,
    status: "available",
    progress: 0,
    completed: 0,
    total: 6,
    parent: "developmental-psychology",
    children: ["puberty", "adolescent-brain", "identity-formation", "adolescent-peer-influence", "risk-behavior"],
    unlocked: true,
    visible: true,
    x: 1400,
    y: 250,
    radius: 42,
    color: "#E11D48",
    glow: "#FB7185",
    iconName: "Flame",
    difficulty: "intermediate",
    estimatedMinutes: 40,
    tags: ["puberty", "identity", "peers"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "puberty",
    title: "Puberty",
    subtitle: "Physical and Sexual Maturation",
    description: "Puberty involves hormonal changes triggering growth spurts, sexual maturation, and secondary sex characteristics. Timing of puberty (early, on-time, late) influences psychological adjustment, with early maturation having different effects for males and females.",
    branch: "developmental",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "adolescence",
    children: [],
    unlocked: false,
    visible: true,
    x: 1350,
    y: 400,
    radius: 32,
    color: "#E11D48",
    glow: "#FB7185",
    iconName: "Activity",
    difficulty: "beginner",
    estimatedMinutes: 20,
    tags: ["hormones", "growth", "sexual-maturation"],
    prerequisites: ["adolescence"],
  },
  {
    id: "adolescent-brain",
    title: "Adolescent Brain Development",
    subtitle: "Neural Changes and Decision Making",
    description: "The adolescent brain undergoes significant remodeling, with synaptic pruning and myelination increasing efficiency. The prefrontal cortex matures later than limbic regions, contributing to heightened emotionality and risk-taking alongside developing self-control.",
    branch: "developmental",
    level: 2,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "adolescence",
    children: [],
    unlocked: false,
    visible: true,
    x: 1430,
    y: 400,
    radius: 32,
    color: "#E11D48",
    glow: "#FB7185",
    iconName: "Brain",
    difficulty: "advanced",
    estimatedMinutes: 30,
    tags: ["prefrontal-cortex", "synaptic-pruning", "neuroscience"],
    prerequisites: ["adolescence"],
  },
  {
    id: "identity-formation",
    title: "Identity Formation",
    subtitle: "Marcia's Identity Statuses",
    description: "James Marcia expanded Erikson's identity crisis into four statuses: identity achievement (commitment after exploration), moratorium (exploration without commitment), foreclosure (commitment without exploration), and diffusion (neither). Identity development varies across domains.",
    branch: "developmental",
    level: 2,
    xp: 190,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "adolescence",
    children: [],
    unlocked: false,
    visible: true,
    x: 1510,
    y: 400,
    radius: 32,
    color: "#E11D48",
    glow: "#FB7185",
    iconName: "Fingerprint",
    difficulty: "intermediate",
    estimatedMinutes: 28,
    tags: ["marcia", "exploration", "commitment"],
    prerequisites: ["adolescence"],
  },
  {
    id: "adolescent-peer-influence",
    title: "Adolescent Peer Influence",
    subtitle: "Cliques, Crowds, and Conformity",
    description: "Peer influence peaks in early adolescence. Cliques (small friendship groups) and crowds (reputation-based groups) structure social life. Peer pressure can be positive or negative, with susceptibility varying by domain and individual factors.",
    branch: "developmental",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "adolescence",
    children: [],
    unlocked: false,
    visible: true,
    x: 1590,
    y: 400,
    radius: 32,
    color: "#E11D48",
    glow: "#FB7185",
    iconName: "Users",
    difficulty: "intermediate",
    estimatedMinutes: 22,
    tags: ["peer-pressure", "cliques", "conformity"],
    prerequisites: ["adolescence"],
  },
  {
    id: "risk-behavior",
    title: "Risk Behavior",
    subtitle: "Substance Use and Delinquency",
    description: "Adolescent risk-taking includes substance use, reckless driving, and unsafe sexual behavior. Contributing factors include brain development, sensation-seeking, peer influence, and perceived invulnerability. Prevention programs target multiple risk and protective factors.",
    branch: "developmental",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "adolescence",
    children: [],
    unlocked: false,
    visible: true,
    x: 1670,
    y: 400,
    radius: 32,
    color: "#E11D48",
    glow: "#FB7185",
    iconName: "AlertTriangle",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["substance-use", "prevention", "sensation-seeking"],
    prerequisites: ["adolescence"],
  },

  // ─── EMERGING ADULTHOOD ───
  {
    id: "emerging-adulthood",
    title: "Emerging Adulthood",
    subtitle: "Ages 18 to 25",
    description: "Jeffrey Arnett proposed emerging adulthood as a distinct developmental period characterized by identity exploration, instability, self-focus, feeling in-between, and possibilities. It bridges adolescence and young adulthood in industrialized societies.",
    branch: "developmental",
    level: 1,
    xp: 170,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "developmental-psychology",
    children: ["identity-exploration-emerging", "emerging-adulthood-relationships", "career-development"],
    unlocked: true,
    visible: true,
    x: 1550,
    y: 250,
    radius: 40,
    color: "#14B8A6",
    glow: "#2DD4BF",
    iconName: "Compass",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    tags: ["transition", "exploration", "young-adult"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "identity-exploration-emerging",
    title: "Identity Exploration",
    subtitle: "Love, Work, and Worldview",
    description: "Emerging adults actively explore possibilities in love (dating, cohabitation), work (career exploration, education), and worldview (values, beliefs). This exploration is normative and contributes to identity consolidation.",
    branch: "developmental",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "emerging-adulthood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1500,
    y: 400,
    radius: 32,
    color: "#14B8A6",
    glow: "#2DD4BF",
    iconName: "Search",
    difficulty: "intermediate",
    estimatedMinutes: 22,
    tags: ["love", "career", "worldview"],
    prerequisites: ["emerging-adulthood"],
  },
  {
    id: "emerging-adulthood-relationships",
    title: "Relationships in Emerging Adulthood",
    subtitle: "Dating, Cohabitation, and Commitment",
    description: "Romantic relationships in emerging adulthood are characterized by serial monogamy, cohabitation, and delayed marriage. Relationship quality, commitment patterns, and the transition to long-term partnerships vary by culture and individual factors.",
    branch: "developmental",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "emerging-adulthood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1580,
    y: 400,
    radius: 32,
    color: "#14B8A6",
    glow: "#2DD4BF",
    iconName: "Heart",
    difficulty: "intermediate",
    estimatedMinutes: 20,
    tags: ["romance", "cohabitation", "marriage"],
    prerequisites: ["emerging-adulthood"],
  },
  {
    id: "career-development",
    title: "Career Development",
    subtitle: "Vocational Identity and Exploration",
    description: "Career development in emerging adulthood involves education, job exploration, and vocational identity formation. Factors include self-efficacy, interests, socioeconomic background, and labor market conditions.",
    branch: "developmental",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "emerging-adulthood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1660,
    y: 400,
    radius: 32,
    color: "#14B8A6",
    glow: "#2DD4BF",
    iconName: "Briefcase",
    difficulty: "intermediate",
    estimatedMinutes: 20,
    tags: ["vocational", "education", "work"],
    prerequisites: ["emerging-adulthood"],
  },

  // ─── ADULTHOOD ───
  {
    id: "adulthood",
    title: "Adulthood",
    subtitle: "Physical, Cognitive, and Social Maturity",
    description: "Adulthood spans early, middle, and late phases, each with distinct developmental tasks. Physical peak occurs in the 20s, followed by gradual decline. Cognitive abilities show stability or improvement in crystallized intelligence, while fluid intelligence may decline.",
    branch: "developmental",
    level: 1,
    xp: 160,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-psychology",
    children: ["physical-changes-adulthood", "cognitive-aging", "midlife-crisis", "work-life-balance"],
    unlocked: true,
    visible: true,
    x: 1700,
    y: 250,
    radius: 40,
    color: "#6366F1",
    glow: "#818CF8",
    iconName: "Briefcase",
    difficulty: "intermediate",
    estimatedMinutes: 35,
    tags: ["maturity", "career", "family"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "physical-changes-adulthood",
    title: "Physical Changes in Adulthood",
    subtitle: "Peak, Stability, and Decline",
    description: "Physical development peaks in the 20s, followed by gradual sensory and motor declines. Changes include reduced visual acuity, hearing loss, slower metabolism, and decreased bone density. Lifestyle factors significantly influence the rate of physical aging.",
    branch: "developmental",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "adulthood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1650,
    y: 400,
    radius: 32,
    color: "#6366F1",
    glow: "#818CF8",
    iconName: "Activity",
    difficulty: "beginner",
    estimatedMinutes: 20,
    tags: ["physical", "sensory", "aging-process"],
    prerequisites: ["adulthood"],
  },
  {
    id: "cognitive-aging",
    title: "Cognitive Aging",
    subtitle: "Fluid and Crystallized Intelligence",
    description: "Crystallized intelligence (accumulated knowledge) remains stable or improves through middle age. Fluid intelligence (novel problem-solving) may begin declining in the 30s. Cognitive reserve, education, and lifestyle factors moderate age-related cognitive changes.",
    branch: "developmental",
    level: 2,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "adulthood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1730,
    y: 400,
    radius: 32,
    color: "#6366F1",
    glow: "#818CF8",
    iconName: "Brain",
    difficulty: "advanced",
    estimatedMinutes: 30,
    tags: ["intelligence", "cognitive-reserve", "memory"],
    prerequisites: ["adulthood"],
  },
  {
    id: "midlife-crisis",
    title: "Midlife Crisis",
    subtitle: "Myth or Reality",
    description: "The concept of a universal midlife crisis is largely a myth. Research shows most adults experience midlife as a period of stability and satisfaction. However, some individuals face significant reevaluation of life goals, relationships, and personal identity during middle age.",
    branch: "developmental",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "adulthood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1810,
    y: 400,
    radius: 32,
    color: "#6366F1",
    glow: "#818CF8",
    iconName: "Compass",
    difficulty: "intermediate",
    estimatedMinutes: 22,
    tags: ["midlife", "reevaluation", "satisfaction"],
    prerequisites: ["adulthood"],
  },
  {
    id: "work-life-balance",
    title: "Work-Life Balance",
    subtitle: "Career, Family, and Well-being",
    description: "Adults navigate complex demands of career, family, and personal well-being. Work-life balance varies by culture, gender, socioeconomic status, and life stage. Role conflict and role strain are common challenges.",
    branch: "developmental",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "adulthood",
    children: [],
    unlocked: false,
    visible: true,
    x: 1890,
    y: 400,
    radius: 32,
    color: "#6366F1",
    glow: "#818CF8",
    iconName: "Scale",
    difficulty: "intermediate",
    estimatedMinutes: 20,
    tags: ["career", "family", "well-being"],
    prerequisites: ["adulthood"],
  },

  // ─── AGING ───
  {
    id: "aging",
    title: "Aging",
    subtitle: "Late Life Development",
    description: "Late adulthood involves continued psychological growth alongside physical decline. Cognitive changes include potential wisdom accumulation and selective optimization with compensation. Social networks often contract but increase in emotional quality.",
    branch: "developmental",
    level: 1,
    xp: 180,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-psychology",
    children: ["physical-aging", "cognitive-changes-aging", "socioemotional-selectivity", "dementia", "successful-aging"],
    unlocked: true,
    visible: true,
    x: 1850,
    y: 250,
    radius: 40,
    color: "#78716C",
    glow: "#A8A29E",
    iconName: "Hourglass",
    difficulty: "intermediate",
    estimatedMinutes: 35,
    tags: ["elderly", "senescence", "longevity"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "physical-aging",
    title: "Physical Aging",
    subtitle: "Biological Changes in Late Life",
    description: "Physical aging involves declines in sensory acuity, muscle mass, bone density, and organ function. Cellular aging theories include programmed theories (telomere shortening) and damage theories (free radical accumulation). Lifestyle factors significantly influence the aging trajectory.",
    branch: "developmental",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "aging",
    children: [],
    unlocked: false,
    visible: true,
    x: 1800,
    y: 400,
    radius: 32,
    color: "#78716C",
    glow: "#A8A29E",
    iconName: "Activity",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["senescence", "telomeres", "biological-aging"],
    prerequisites: ["aging"],
  },
  {
    id: "cognitive-changes-aging",
    title: "Cognitive Changes in Aging",
    subtitle: "Memory, Speed, and Wisdom",
    description: "Processing speed and working memory decline with age, while semantic memory and crystallized knowledge remain stable. Wisdom-related knowledge and emotional regulation often improve. Dementia affects approximately 10% of adults over 65.",
    branch: "developmental",
    level: 2,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "aging",
    children: [],
    unlocked: false,
    visible: true,
    x: 1880,
    y: 400,
    radius: 32,
    color: "#78716C",
    glow: "#A8A29E",
    iconName: "Brain",
    difficulty: "advanced",
    estimatedMinutes: 30,
    tags: ["memory", "wisdom", "cognitive-decline"],
    prerequisites: ["aging"],
  },
  {
    id: "socioemotional-selectivity",
    title: "Socioemotional Selectivity Theory",
    subtitle: "Prioritizing Meaningful Relationships",
    description: "Laura Carstensen's theory proposes that as perceived time horizons shrink, older adults prioritize emotionally meaningful goals and relationships over information-seeking. This leads to smaller but higher-quality social networks and improved emotional well-being.",
    branch: "developmental",
    level: 2,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "aging",
    children: [],
    unlocked: false,
    visible: true,
    x: 1960,
    y: 400,
    radius: 32,
    color: "#78716C",
    glow: "#A8A29E",
    iconName: "Heart",
    difficulty: "advanced",
    estimatedMinutes: 28,
    tags: ["carstensen", "emotional-goals", "social-networks"],
    prerequisites: ["aging"],
  },
  {
    id: "dementia",
    title: "Dementia",
    subtitle: "Neurocognitive Disorders in Late Life",
    description: "Dementia involves progressive decline in cognitive function affecting memory, reasoning, and daily functioning. Alzheimer's disease accounts for 60-70% of cases. Vascular dementia, Lewy body dementia, and frontotemporal dementia are other major types. Risk factors include age, genetics, and lifestyle.",
    branch: "developmental",
    level: 2,
    xp: 280,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 6,
    parent: "aging",
    children: [],
    unlocked: false,
    visible: true,
    x: 2040,
    y: 400,
    radius: 32,
    color: "#78716C",
    glow: "#A8A29E",
    iconName: "AlertTriangle",
    difficulty: "expert",
    estimatedMinutes: 35,
    tags: ["alzheimers", "neurocognitive", "decline"],
    prerequisites: ["aging"],
  },
  {
    id: "successful-aging",
    title: "Successful Aging",
    subtitle: "Optimizing Late Life Functioning",
    description: "Successful aging involves low probability of disease, high cognitive and physical function, and active engagement with life. Rowe and Kahn's model emphasizes avoiding disease, maintaining high function, and sustained engagement. Resilience and adaptation are key.",
    branch: "developmental",
    level: 2,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "aging",
    children: [],
    unlocked: false,
    visible: true,
    x: 2120,
    y: 400,
    radius: 32,
    color: "#78716C",
    glow: "#A8A29E",
    iconName: "Star",
    difficulty: "intermediate",
    estimatedMinutes: 25,
    tags: ["resilience", "adaptation", "well-being"],
    prerequisites: ["aging"],
  },

  // ─── DEVELOPMENTAL DISORDERS ───
  {
    id: "developmental-disorders",
    title: "Developmental Disorders",
    subtitle: "Atypical Development Across the Lifespan",
    description: "Developmental disorders involve significant delays or deviations in expected developmental trajectories. Major categories include neurodevelopmental disorders (autism, ADHD, intellectual disability), learning disorders, and communication disorders. Early identification and intervention improve outcomes.",
    branch: "developmental",
    level: 1,
    xp: 250,
    status: "available",
    progress: 0,
    completed: 0,
    total: 6,
    parent: "developmental-psychology",
    children: ["autism-spectrum-disorder", "adhd", "intellectual-disability", "learning-disorders", "down-syndrome"],
    unlocked: true,
    visible: true,
    x: 2000,
    y: 250,
    radius: 42,
    color: "#DC2626",
    glow: "#EF4444",
    iconName: "AlertCircle",
    difficulty: "expert",
    estimatedMinutes: 45,
    tags: ["atypical", "intervention", "diagnosis"],
    prerequisites: ["developmental-psychology"],
  },
  {
    id: "autism-spectrum-disorder",
    title: "Autism Spectrum Disorder",
    subtitle: "Social Communication and Repetitive Behaviors",
    description: "ASD is characterized by persistent deficits in social communication and interaction, plus restricted, repetitive patterns of behavior. Symptoms appear in early childhood and vary widely in severity. Prevalence is approximately 1 in 36 children. Early intervention with behavioral therapies improves outcomes.",
    branch: "developmental",
    level: 2,
    xp: 280,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 6,
    parent: "developmental-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 1950,
    y: 400,
    radius: 32,
    color: "#DC2626",
    glow: "#EF4444",
    iconName: "Puzzle",
    difficulty: "expert",
    estimatedMinutes: 40,
    tags: ["ASD", "social-communication", "repetitive-behavior"],
    prerequisites: ["developmental-disorders"],
  },
  {
    id: "adhd",
    title: "ADHD",
    subtitle: "Attention-Deficit/Hyperactivity Disorder",
    description: "ADHD involves persistent patterns of inattention, hyperactivity, and impulsivity interfering with functioning. Three subtypes exist: predominantly inattentive, predominantly hyperactive-impulsive, and combined. Prevalence is 5-10% of children. Treatment includes behavioral interventions and medication.",
    branch: "developmental",
    level: 2,
    xp: 260,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 2030,
    y: 400,
    radius: 32,
    color: "#DC2626",
    glow: "#EF4444",
    iconName: "Zap",
    difficulty: "expert",
    estimatedMinutes: 35,
    tags: ["attention", "hyperactivity", "impulsivity"],
    prerequisites: ["developmental-disorders"],
  },
  {
    id: "intellectual-disability",
    title: "Intellectual Disability",
    subtitle: "Significant Cognitive and Adaptive Limitations",
    description: "Intellectual disability involves significant limitations in intellectual functioning (IQ below 70) and adaptive behavior, originating before age 18. Causes include genetic conditions (Down syndrome, Fragile X), prenatal factors, and environmental deprivation. Support and education optimize independence.",
    branch: "developmental",
    level: 2,
    xp: 240,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 2110,
    y: 400,
    radius: 32,
    color: "#DC2626",
    glow: "#EF4444",
    iconName: "Brain",
    difficulty: "advanced",
    estimatedMinutes: 30,
    tags: ["IQ", "adaptive-behavior", "genetic"],
    prerequisites: ["developmental-disorders"],
  },
  {
    id: "learning-disorders",
    title: "Learning Disorders",
    subtitle: "Specific Academic Skill Deficits",
    description: "Learning disorders involve specific deficits in reading (dyslexia), mathematics (dyscalculia), or written expression despite average intelligence and adequate instruction. Neurobiological origins involve differences in brain structure and function. Specialized instruction and accommodations are effective.",
    branch: "developmental",
    level: 2,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 2190,
    y: 400,
    radius: 32,
    color: "#DC2626",
    glow: "#EF4444",
    iconName: "BookOpen",
    difficulty: "advanced",
    estimatedMinutes: 30,
    tags: ["dyslexia", "dyscalculia", "academic"],
    prerequisites: ["developmental-disorders"],
  },
  {
    id: "down-syndrome",
    title: "Down Syndrome",
    subtitle: "Trisomy 21 and Development",
    description: "Down syndrome, caused by trisomy 21, is the most common chromosomal condition. Characteristics include intellectual disability, distinctive facial features, and increased risk of heart defects and Alzheimer's disease. Early intervention programs support cognitive, motor, and social development.",
    branch: "developmental",
    level: 2,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "developmental-disorders",
    children: [],
    unlocked: false,
    visible: true,
    x: 2270,
    y: 400,
    radius: 32,
    color: "#DC2626",
    glow: "#EF4444",
    iconName: "Dna",
    difficulty: "advanced",
    estimatedMinutes: 28,
    tags: ["trisomy-21", "chromosomal", "genetic"],
    prerequisites: ["developmental-disorders"],
  },
];
