// ============================================================
// SECTION: Type Definitions
// ============================================================

interface TreeNode {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  branch: string;
  level: number;
  xp: number;
  status: 'mastered' | 'available' | 'locked';
  progress: number;
  completed: number;
  total: number;
  parent: string | null;
  children: string[];
  unlocked: boolean;
  visible: boolean;
  x: number;
  y: number;
  radius: number;
  color: string;
  glow: string;
  iconName: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  estimatedMinutes: number;
  tags: string[];
  prerequisites: string[];
}

// ============================================================
// SECTION: Personality Psychology Nodes
// ============================================================

export const personalityNodes: TreeNode[] = [
  {
    id: 'personality',
    title: 'Personality Psychology',
    subtitle: 'Individual Differences and Trait Theory',
    description: 'The study of consistent patterns of thought, emotion, and behavior that distinguish individuals from one another. Examines major theoretical perspectives including trait theory, psychodynamic approaches, humanistic models, and the biological basis of temperament.',
    branch: 'personality',
    level: 1,
    xp: 50,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: ['trait-theory', 'freud', 'jung', 'adler', 'erikson', 'humanistic-theory', 'behaviorism-personality', 'temperament', 'locus-of-control', 'personality-assessment', 'motivation', 'self-concept'],
    unlocked: true,
    visible: true,
    x: 0,
    y: 0,
    radius: 44,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.35)',
    iconName: 'fingerprint',
    difficulty: 'beginner',
    estimatedMinutes: 0,
    tags: ['traits', 'individuality', 'differences'],
    prerequisites: ['psychology'],
  },
  {
    id: 'trait-theory',
    title: 'Trait Theory',
    subtitle: 'Describing Personality Through Dimensions',
    description: 'An approach to personality that focuses on identifying, describing, and measuring specific personality characteristics called traits. Traits are relatively stable dispositions that influence behavior across situations.',
    branch: 'personality',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['big-five', 'allport-traits', 'cattell-16pf', 'eysenck-dimensions', 'trait-stability'],
    unlocked: false,
    visible: true,
    x: -400,
    y: -280,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'bar-chart-3',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['dimensions', 'dispositions', 'measurement'],
    prerequisites: ['personality'],
  },
  {
    id: 'big-five',
    title: 'Big Five Personality Traits',
    subtitle: 'OCEAN Model of Personality Structure',
    description: 'The most widely accepted model of personality structure, comprising five broad dimensions: Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism. Supported by cross-cultural research and behavioral genetics.',
    branch: 'personality',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'trait-theory',
    children: ['openness', 'conscientiousness', 'extraversion', 'agreeableness', 'neuroticism'],
    unlocked: false,
    visible: true,
    x: -520,
    y: -400,
    radius: 28,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'pentagon',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['ocean', 'five-factor', 'structure'],
    prerequisites: ['trait-theory'],
  },
  {
    id: 'openness',
    title: 'Openness to Experience',
    subtitle: 'Curiosity, Creativity, and Preference for Novelty',
    description: 'A Big Five dimension characterized by appreciation for art, emotion, adventure, unusual ideas, curiosity, and variety of experience. High scorers are imaginative and independent; low scorers prefer routine and convention.',
    branch: 'personality',
    level: 4,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'big-five',
    children: [],
    unlocked: false,
    visible: true,
    x: -560,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'palette',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['creativity', 'curiosity', 'novelty'],
    prerequisites: ['big-five'],
  },
  {
    id: 'conscientiousness',
    title: 'Conscientiousness',
    subtitle: 'Organization, Dependability, and Self-Discipline',
    description: 'A Big Five dimension characterized by self-discipline, carefulness, thoroughness, and organization. High scorers are reliable and goal-directed; low scorers are more spontaneous and flexible. Strongly predicts academic and job performance.',
    branch: 'personality',
    level: 4,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'big-five',
    children: [],
    unlocked: false,
    visible: true,
    x: -480,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'clipboard-check',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['discipline', 'organization', 'reliability'],
    prerequisites: ['big-five'],
  },
  {
    id: 'extraversion',
    title: 'Extraversion',
    subtitle: 'Sociability, Energy, and Positive Emotionality',
    description: 'A Big Five dimension characterized by sociability, assertiveness, high activity, and positive emotionality. High scorers gain energy from social interaction; low scorers (introverts) prefer solitude and reflection.',
    branch: 'personality',
    level: 4,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'big-five',
    children: [],
    unlocked: false,
    visible: true,
    x: -400,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'users',
    difficulty: 'beginner',
    estimatedMinutes: 20,
    tags: ['sociability', 'energy', 'introversion'],
    prerequisites: ['big-five'],
  },
  {
    id: 'agreeableness',
    title: 'Agreeableness',
    subtitle: 'Cooperation, Trust, and Prosocial Orientation',
    description: 'A Big Five dimension characterized by trust, altruism, kindness, affection, and cooperative behavior. High scorers are empathetic and helpful; low scorers are more competitive and skeptical. Important for interpersonal relationships.',
    branch: 'personality',
    level: 4,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'big-five',
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'heart-handshake',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['cooperation', 'trust', 'altruism'],
    prerequisites: ['big-five'],
  },
  {
    id: 'neuroticism',
    title: 'Neuroticism',
    subtitle: 'Emotional Instability and Negative Affect',
    description: 'A Big Five dimension characterized by emotional instability, anxiety, moodiness, irritability, and sadness. High scorers experience more negative emotions and stress; low scorers are emotionally stable and resilient.',
    branch: 'personality',
    level: 4,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'big-five',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'cloud-rain',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['anxiety', 'instability', 'resilience'],
    prerequisites: ['big-five'],
  },
  {
    id: 'allport-traits',
    title: 'Allport\'s Trait Theory',
    subtitle: 'Cardinal, Central, and Secondary Traits',
    description: 'Gordon Allport\'s influential theory proposing that traits exist at three levels of hierarchy: cardinal traits that dominate a life, central traits that form the core of personality, and secondary traits that are situation-specific.',
    branch: 'personality',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'trait-theory',
    children: [],
    unlocked: false,
    visible: true,
    x: -440,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'layers',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['allport', 'hierarchy', 'individuality'],
    prerequisites: ['trait-theory'],
  },
  {
    id: 'cattell-16pf',
    title: 'Cattell\'s 16PF',
    subtitle: 'Sixteen Primary Factors of Personality',
    description: 'Raymond Cattell\'s factor-analytic model identifying sixteen primary personality factors measured by the 16PF questionnaire. Provided a more granular alternative to the Big Five and influenced modern personality assessment.',
    branch: 'personality',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'trait-theory',
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'grid-3x3',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['cattell', 'factors', 'questionnaire'],
    prerequisites: ['trait-theory'],
  },
  {
    id: 'eysenck-dimensions',
    title: 'Eysenck\'s Personality Dimensions',
    subtitle: 'Extraversion, Neuroticism, and Psychoticism',
    description: 'Hans Eysenck\'s biologically-based model proposing three major dimensions of personality: extraversion-introversion, neuroticism-emotional stability, and psychoticism-socialization. Linked to arousal and cortical activity.',
    branch: 'personality',
    level: 3,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'trait-theory',
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'activity',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['eysenck', 'biology', 'arousal'],
    prerequisites: ['trait-theory'],
  },
  {
    id: 'trait-stability',
    title: 'Trait Stability and Change',
    subtitle: 'Consistency and Development Over the Lifespan',
    description: 'Research on the degree to which personality traits remain stable or change across the lifespan. Traits show increasing stability with age, with rank-order consistency high by age 30, while mean levels show systematic change patterns.',
    branch: 'personality',
    level: 3,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'trait-theory',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'trending-up',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['stability', 'lifespan', 'development'],
    prerequisites: ['trait-theory'],
  },
  {
    id: 'freud',
    title: 'Freud\'s Psychoanalytic Theory',
    subtitle: 'Unconscious Drives and Psychosexual Development',
    description: 'Sigmund Freud\'s comprehensive theory of personality emphasizing unconscious conflicts, defense mechanisms, and psychosexual stages. Though controversial, it profoundly influenced psychology, psychiatry, and Western culture.',
    branch: 'personality',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['id-ego-superego', 'defense-mechanisms', 'psychosexual-stages', 'freudian-slip', 'unconscious-mind'],
    unlocked: false,
    visible: true,
    x: -280,
    y: -280,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'lock',
    difficulty: 'beginner',
    estimatedMinutes: 45,
    tags: ['psychoanalysis', 'unconscious', 'conflict'],
    prerequisites: ['personality'],
  },
  {
    id: 'id-ego-superego',
    title: 'Id, Ego, and Superego',
    subtitle: 'Structural Model of the Psyche',
    description: 'Freud\'s structural model dividing the psyche into three components: the id (primitive instincts), the ego (rational mediator), and the superego (moral conscience). Their dynamic interactions shape personality and behavior.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'freud',
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'git-merge',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['structure', 'instincts', 'morality'],
    prerequisites: ['freud'],
  },
  {
    id: 'defense-mechanisms',
    title: 'Defense Mechanisms',
    subtitle: 'Unconscious Strategies to Reduce Anxiety',
    description: 'Unconscious psychological strategies used by the ego to manage internal conflict and reduce anxiety. Include repression, denial, projection, displacement, sublimation, and reaction formation, each operating outside awareness.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'freud',
    children: ['repression', 'projection', 'sublimation'],
    unlocked: false,
    visible: true,
    x: -280,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'shield',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['anxiety', 'unconscious', 'coping'],
    prerequisites: ['freud'],
  },
  {
    id: 'repression',
    title: 'Repression',
    subtitle: 'Banishing Unacceptable Thoughts from Awareness',
    description: 'The fundamental defense mechanism in which threatening or unacceptable thoughts, memories, and feelings are pushed out of conscious awareness into the unconscious. Freud considered it the cornerstone of psychoanalysis.',
    branch: 'personality',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'defense-mechanisms',
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'eye-off',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['unconscious', 'banishment', 'threat'],
    prerequisites: ['defense-mechanisms'],
  },
  {
    id: 'projection',
    title: 'Projection',
    subtitle: 'Attributing Unacceptable Impulses to Others',
    description: 'A defense mechanism in which individuals attribute their own unacceptable thoughts, feelings, or impulses to others. Reduces anxiety by externalizing internal threats while maintaining self-image.',
    branch: 'personality',
    level: 4,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'defense-mechanisms',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'arrow-up-right',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['externalization', 'attribution', 'threat'],
    prerequisites: ['defense-mechanisms'],
  },
  {
    id: 'sublimation',
    title: 'Sublimation',
    subtitle: 'Channeling Unacceptable Impulses Constructively',
    description: 'A mature defense mechanism in which socially unacceptable impulses are transformed into socially acceptable actions or behaviors. Considered by Freud to be the most adaptive and constructive defense mechanism.',
    branch: 'personality',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'defense-mechanisms',
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'trending-up',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['constructive', 'channeling', 'adaptive'],
    prerequisites: ['defense-mechanisms'],
  },
  {
    id: 'psychosexual-stages',
    title: 'Psychosexual Stages',
    subtitle: 'Developmental Phases of Libidinal Energy',
    description: 'Freud\'s theory that personality develops through five stages (oral, anal, phallic, latency, genital) during childhood, with fixation in any stage leading to adult personality characteristics. The Oedipus complex occurs in the phallic stage.',
    branch: 'personality',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'freud',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'baby',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['development', 'fixation', 'stages'],
    prerequisites: ['freud'],
  },
  {
    id: 'freudian-slip',
    title: 'Freudian Slips',
    subtitle: 'Unconscious Revealed in Errors',
    description: 'Errors in speech, memory, or physical action that Freud interpreted as revealing unconscious wishes or conflicts. Also called parapraxes, they were considered windows into the unconscious mind rather than random mistakes.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'freud',
    children: [],
    unlocked: false,
    visible: true,
    x: -120,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'message-square',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['parapraxes', 'errors', 'revelation'],
    prerequisites: ['freud'],
  },
  {
    id: 'unconscious-mind',
    title: 'The Unconscious Mind',
    subtitle: 'Mental Processes Outside Awareness',
    description: 'Freud\'s concept of a reservoir of thoughts, memories, and desires that are inaccessible to conscious awareness but influence behavior. The cornerstone of psychoanalytic theory and the target of psychoanalytic therapy.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'freud',
    children: [],
    unlocked: false,
    visible: true,
    x: -40,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'ghost',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['awareness', 'reservoir', 'influence'],
    prerequisites: ['freud'],
  },
  {
    id: 'jung',
    title: 'Jung\'s Analytical Psychology',
    subtitle: 'Archetypes and the Collective Unconscious',
    description: 'Carl Jung\'s theory extending psychoanalysis to include the collective unconscious, archetypes, and individuation. Introduced concepts of extraversion and introversion as fundamental attitudes, later adopted by the Big Five.',
    branch: 'personality',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['collective-unconscious', 'archetypes', 'individuation', 'shadow', 'anima-animus'],
    unlocked: false,
    visible: true,
    x: -160,
    y: -280,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'moon',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['analytical', 'archetypes', 'unconscious'],
    prerequisites: ['personality'],
  },
  {
    id: 'collective-unconscious',
    title: 'Collective Unconscious',
    subtitle: 'Shared Inherited Psychological Content',
    description: 'Jung\'s concept of a universal reservoir of psychic material inherited from ancestors, distinct from the personal unconscious. Contains archetypes and patterns shared across all humanity, independent of individual experience.',
    branch: 'personality',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'jung',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'globe',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['universal', 'inherited', 'shared'],
    prerequisites: ['jung'],
  },
  {
    id: 'archetypes',
    title: 'Archetypes',
    subtitle: 'Universal Symbolic Patterns',
    description: 'Universal, inherited patterns of thought and imagery that reside in the collective unconscious. Include the persona, shadow, anima/animus, and self. Manifest in dreams, myths, art, and religious symbolism across cultures.',
    branch: 'personality',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'jung',
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'star',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['symbols', 'patterns', 'universal'],
    prerequisites: ['jung'],
  },
  {
    id: 'individuation',
    title: 'Individuation',
    subtitle: 'Integration of Conscious and Unconscious',
    description: 'Jung\'s concept of the lifelong psychological process of integrating the conscious and unconscious aspects of the psyche to become a whole, unique individual. The central goal of analytical psychology.',
    branch: 'personality',
    level: 3,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'jung',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'user-check',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['integration', 'wholeness', 'self'],
    prerequisites: ['jung'],
  },
  {
    id: 'shadow',
    title: 'The Shadow',
    subtitle: 'The Dark Side of the Psyche',
    description: 'Jung\'s archetype representing the unconscious aspect of personality, containing repressed weaknesses, desires, and instincts. Integration of the shadow is essential for psychological wholeness and individuation.',
    branch: 'personality',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'jung',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'moon',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['dark', 'repressed', 'integration'],
    prerequisites: ['jung'],
  },
  {
    id: 'anima-animus',
    title: 'Anima and Animus',
    subtitle: 'Inner Contraseual Aspects',
    description: 'Jung\'s archetypes representing the feminine inner personality in men (anima) and the masculine inner personality in women (animus). Integration of these contrasexual elements is necessary for psychological completeness.',
    branch: 'personality',
    level: 3,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'jung',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'git-merge',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['feminine', 'masculine', 'completeness'],
    prerequisites: ['jung'],
  },
  {
    id: 'adler',
    title: 'Adler\'s Individual Psychology',
    subtitle: 'Striving for Superiority and Social Interest',
    description: 'Alfred Adler\'s theory emphasizing the individual\'s striving for superiority, feelings of inferiority, and social interest. Rejected Freud\'s emphasis on sexuality, focusing instead on social factors and conscious goal-directed behavior.',
    branch: 'personality',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['inferiority-complex', 'striving-for-superiority', 'social-interest', 'birth-order'],
    unlocked: false,
    visible: true,
    x: -40,
    y: -280,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'arrow-up',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['individual', 'superiority', 'social'],
    prerequisites: ['personality'],
  },
  {
    id: 'inferiority-complex',
    title: 'Inferiority Complex',
    subtitle: 'Feelings of Inadequacy and Compensation',
    description: 'Adler\'s concept of pervasive feelings of inadequacy and weakness that motivate individuals to compensate through striving for superiority. Healthy compensation leads to achievement; unhealthy compensation leads to neurosis.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'adler',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'trending-down',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['inadequacy', 'compensation', 'weakness'],
    prerequisites: ['adler'],
  },
  {
    id: 'striving-for-superiority',
    title: 'Striving for Superiority',
    subtitle: 'Fundamental Motivational Force',
    description: 'Adler\'s concept that the primary motivational force in human life is the striving for superiority, defined as the desire to overcome difficulties and achieve perfection. Distinguishes healthy striving from neurotic overcompensation.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'adler',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'trending-up',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['motivation', 'perfection', 'achievement'],
    prerequisites: ['adler'],
  },
  {
    id: 'social-interest',
    title: 'Social Interest',
    subtitle: 'Community Feeling and Cooperation',
    description: 'Adler\'s concept of Gemeinschaftsgefuhl, a sense of belonging and contribution to society. Healthy personality development requires social interest; its absence is associated with maladjustment and psychopathology.',
    branch: 'personality',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'adler',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'heart-handshake',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['community', 'cooperation', 'belonging'],
    prerequisites: ['adler'],
  },
  {
    id: 'birth-order',
    title: 'Birth Order Effects',
    subtitle: 'Sibling Position and Personality',
    description: 'Adler\'s theory that ordinal position in the family influences personality development. Firstborns tend toward leadership and responsibility, middle children toward diplomacy, and youngest toward creativity and risk-taking.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'adler',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'users',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['siblings', 'position', 'family'],
    prerequisites: ['adler'],
  },
  {
    id: 'erikson',
    title: 'Erikson\'s Psychosocial Theory',
    subtitle: 'Eight Stages of Lifespan Development',
    description: 'Erik Erikson\'s theory of personality development across the lifespan, proposing eight stages each with a central psychosocial crisis. Successful resolution of each crisis builds ego strength and healthy personality.',
    branch: 'personality',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['trust-vs-mistrust', 'identity-vs-role-confusion', 'integrity-vs-despair', 'erikson-stages-overview'],
    unlocked: false,
    visible: true,
    x: 80,
    y: -280,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'baby',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['lifespan', 'crisis', 'development'],
    prerequisites: ['personality'],
  },
  {
    id: 'erikson-stages-overview',
    title: 'Erikson\'s Eight Stages',
    subtitle: 'Lifespan Psychosocial Crises',
    description: 'An overview of Erikson\'s eight stages from infancy to old age: trust vs mistrust, autonomy vs shame, initiative vs guilt, industry vs inferiority, identity vs role confusion, intimacy vs isolation, generativity vs stagnation, integrity vs despair.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'erikson',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'list-ordered',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['stages', 'lifespan', 'crises'],
    prerequisites: ['erikson'],
  },
  {
    id: 'trust-vs-mistrust',
    title: 'Trust vs Mistrust',
    subtitle: 'Infancy and Basic Security',
    description: 'Erikson\'s first stage (0-18 months) in which infants learn whether the world is trustworthy based on caregiver responsiveness. Successful resolution produces hope; failure produces fear and insecurity.',
    branch: 'personality',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'erikson',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'shield-check',
    difficulty: 'beginner',
    estimatedMinutes: 20,
    tags: ['infancy', 'caregivers', 'hope'],
    prerequisites: ['erikson'],
  },
  {
    id: 'identity-vs-role-confusion',
    title: 'Identity vs Role Confusion',
    subtitle: 'Adolescence and Self-Definition',
    description: 'Erikson\'s fifth stage (12-18 years) in which adolescents explore roles and ideologies to form a coherent sense of self. Successful resolution produces fidelity and identity; failure produces role confusion and weak sense of self.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'erikson',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'user',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['adolescence', 'identity', 'roles'],
    prerequisites: ['erikson'],
  },
  {
    id: 'integrity-vs-despair',
    title: 'Integrity vs Despair',
    subtitle: 'Late Life and Meaning Review',
    description: 'Erikson\'s final stage (65+ years) in which older adults reflect on their lives. Successful resolution produces wisdom and acceptance; failure produces regret, bitterness, and fear of death.',
    branch: 'personality',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'erikson',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'book-open',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['aging', 'wisdom', 'reflection'],
    prerequisites: ['erikson'],
  },
  {
    id: 'humanistic-theory',
    title: 'Humanistic Theory',
    subtitle: 'Growth, Potential, and Self-Actualization',
    description: 'A perspective emphasizing human potential, free will, self-awareness, and the pursuit of personal growth. Rejects deterministic views, focusing instead on subjective experience and the innate drive toward self-actualization.',
    branch: 'personality',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['maslow', 'rogers', 'self-actualization', 'fully-functioning-person'],
    unlocked: false,
    visible: true,
    x: 200,
    y: -280,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'sun',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['growth', 'potential', 'free-will'],
    prerequisites: ['personality'],
  },
  {
    id: 'maslow',
    title: 'Maslow\'s Hierarchy of Needs',
    subtitle: 'Pyramid of Human Motivation',
    description: 'Abraham Maslow\'s theory proposing that human needs are arranged in a hierarchy from physiological needs at the base to self-actualization at the peak. Lower needs must be satisfied before higher needs become motivators.',
    branch: 'personality',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'humanistic-theory',
    children: ['physiological-needs', 'safety-needs', 'belonging-needs', 'esteem-needs', 'self-actualization-need'],
    unlocked: false,
    visible: true,
    x: 120,
    y: -400,
    radius: 28,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'pyramid',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['hierarchy', 'needs', 'motivation'],
    prerequisites: ['humanistic-theory'],
  },
  {
    id: 'physiological-needs',
    title: 'Physiological Needs',
    subtitle: 'Basic Survival Requirements',
    description: 'The most fundamental level of Maslow\'s hierarchy, including needs for food, water, warmth, and rest. Must be substantially satisfied before higher-level needs become significant motivators of behavior.',
    branch: 'personality',
    level: 4,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'maslow',
    children: [],
    unlocked: false,
    visible: true,
    x: -40,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'droplets',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    tags: ['survival', 'food', 'water'],
    prerequisites: ['maslow'],
  },
  {
    id: 'safety-needs',
    title: 'Safety Needs',
    subtitle: 'Security and Stability',
    description: 'The second level of Maslow\'s hierarchy, encompassing needs for security, safety, and stability. Includes physical safety, financial security, health, and protection from accidents and illness.',
    branch: 'personality',
    level: 4,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'maslow',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'shield',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    tags: ['security', 'stability', 'protection'],
    prerequisites: ['maslow'],
  },
  {
    id: 'belonging-needs',
    title: 'Belongingness and Love Needs',
    subtitle: 'Social Connection and Intimacy',
    description: 'The third level of Maslow\'s hierarchy, involving needs for intimate relationships, friendships, and belonging to groups. Failure to satisfy these needs leads to loneliness, social anxiety, and depression.',
    branch: 'personality',
    level: 4,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'maslow',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'heart',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    tags: ['friendship', 'intimacy', 'connection'],
    prerequisites: ['maslow'],
  },
  {
    id: 'esteem-needs',
    title: 'Esteem Needs',
    subtitle: 'Respect and Self-Worth',
    description: 'The fourth level of Maslow\'s hierarchy, including needs for self-esteem, achievement, competence, independence, and recognition from others. Divided into lower esteem (respect from others) and higher esteem (self-respect).',
    branch: 'personality',
    level: 4,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'maslow',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'award',
    difficulty: 'intermediate',
    estimatedMinutes: 15,
    tags: ['respect', 'achievement', 'recognition'],
    prerequisites: ['maslow'],
  },
  {
    id: 'self-actualization-need',
    title: 'Self-Actualization',
    subtitle: 'Realizing One\'s Full Potential',
    description: 'The highest level of Maslow\'s hierarchy, representing the need to become the most that one can be. Involves personal growth, peak experiences, and the fulfillment of one\'s unique potential. Rarely fully achieved.',
    branch: 'personality',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'maslow',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'star',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['potential', 'growth', 'fulfillment'],
    prerequisites: ['maslow'],
  },
  {
    id: 'rogers',
    title: 'Rogers\' Person-Centered Theory',
    subtitle: 'Self-Concept and Unconditional Positive Regard',
    description: 'Carl Rogers\' humanistic theory emphasizing the self-concept, the actualizing tendency, and the importance of unconditional positive regard in healthy development. Central to client-centered therapy and counseling.',
    branch: 'personality',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'humanistic-theory',
    children: ['unconditional-positive-regard', 'conditions-of-worth', 'actualizing-tendency'],
    unlocked: false,
    visible: true,
    x: 200,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'user-check',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['rogers', 'self', 'therapy'],
    prerequisites: ['humanistic-theory'],
  },
  {
    id: 'unconditional-positive-regard',
    title: 'Unconditional Positive Regard',
    subtitle: 'Acceptance Without Judgment',
    description: 'Rogers\' concept of accepting and valuing a person regardless of their behavior. Essential for healthy self-concept development. Its absence leads to conditions of worth and psychological distress.',
    branch: 'personality',
    level: 4,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'rogers',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'heart',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['acceptance', 'judgment', 'value'],
    prerequisites: ['rogers'],
  },
  {
    id: 'conditions-of-worth',
    title: 'Conditions of Worth',
    subtitle: 'Contingent Self-Acceptance',
    description: 'Rogers\' concept that when positive regard is conditional on meeting certain standards, individuals develop distorted self-concepts and incongruence between real and ideal selves, leading to psychological problems.',
    branch: 'personality',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'rogers',
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'lock',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['contingency', 'standards', 'incongruence'],
    prerequisites: ['rogers'],
  },
  {
    id: 'actualizing-tendency',
    title: 'Actualizing Tendency',
    subtitle: 'Innate Drive Toward Growth',
    description: 'Rogers\' concept of an innate motivational drive present in all organisms to develop their capacities to the fullest potential. The fundamental force behind healthy personality development and therapeutic change.',
    branch: 'personality',
    level: 4,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'rogers',
    children: [],
    unlocked: false,
    visible: true,
    x: 320,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'sprout',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['growth', 'innate', 'potential'],
    prerequisites: ['rogers'],
  },
  {
    id: 'self-actualization',
    title: 'Self-Actualization',
    subtitle: 'Realizing One\'s Full Potential',
    description: 'The process of becoming the best version of oneself, central to humanistic psychology. Self-actualized individuals are autonomous, creative, problem-centered, and accepting of themselves and others.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'humanistic-theory',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'star',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['potential', 'growth', 'fulfillment'],
    prerequisites: ['humanistic-theory'],
  },
  {
    id: 'fully-functioning-person',
    title: 'The Fully Functioning Person',
    subtitle: 'Rogers\' Ideal of Psychological Health',
    description: 'Rogers\' concept of the optimally developed individual who is open to experience, lives existentially, trusts their own judgment, feels free to choose, and is creative and constructive in their approach to life.',
    branch: 'personality',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'humanistic-theory',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'user-check',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['health', 'openness', 'existential'],
    prerequisites: ['humanistic-theory'],
  },
  {
    id: 'behaviorism-personality',
    title: 'Behavioral Approaches to Personality',
    subtitle: 'Learning Shapes Who We Become',
    description: 'The view that personality is shaped by learning, conditioning, and environmental contingencies rather than internal traits or unconscious conflicts. Emphasizes observable behavior and the role of reinforcement and punishment.',
    branch: 'personality',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['bandura', 'social-learning-theory', 'reciprocal-determinism', 'behavioral-assessment'],
    unlocked: false,
    visible: true,
    x: 320,
    y: -280,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'activity',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['learning', 'conditioning', 'behavior'],
    prerequisites: ['personality'],
  },
  {
    id: 'bandura',
    title: 'Bandura\'s Social Cognitive Theory',
    subtitle: 'Self-Efficacy and Observational Learning',
    description: 'Albert Bandura\'s comprehensive theory emphasizing reciprocal interactions between personal factors, behavior, and the environment. Introduced the concepts of self-efficacy and observational learning as central to personality.',
    branch: 'personality',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'behaviorism-personality',
    children: ['self-efficacy', 'observational-learning', 'reciprocal-determinism-bandura'],
    unlocked: false,
    visible: true,
    x: 280,
    y: -400,
    radius: 28,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'user',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['bandura', 'cognitive', 'agency'],
    prerequisites: ['behaviorism-personality'],
  },
  {
    id: 'self-efficacy',
    title: 'Self-Efficacy',
    subtitle: 'Belief in One\'s Capabilities',
    description: 'Bandura\'s concept of an individual\'s belief in their capacity to execute behaviors necessary to produce specific performance attainments. High self-efficacy predicts persistence, resilience, and achievement across domains.',
    branch: 'personality',
    level: 4,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'bandura',
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'trophy',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['belief', 'capability', 'confidence'],
    prerequisites: ['bandura'],
  },
  {
    id: 'observational-learning',
    title: 'Observational Learning',
    subtitle: 'Learning by Watching Others',
    description: 'Bandura\'s concept that learning occurs through watching, retaining, and replicating the behavior of models. Distinguished from direct conditioning and central to understanding socialization, media effects, and skill acquisition.',
    branch: 'personality',
    level: 4,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'bandura',
    children: [],
    unlocked: false,
    visible: true,
    x: 320,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'eye',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['modeling', 'imitation', 'socialization'],
    prerequisites: ['bandura'],
  },
  {
    id: 'reciprocal-determinism-bandura',
    title: 'Reciprocal Determinism',
    subtitle: 'Person, Behavior, and Environment Interact',
    description: 'Bandura\'s concept that personality is shaped by the continuous interaction of personal factors (cognition, affect), behavior, and environmental influences. Rejects unidirectional causation in favor of mutual influence.',
    branch: 'personality',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'bandura',
    children: [],
    unlocked: false,
    visible: true,
    x: 400,
    y: -480,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'git-merge',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['interaction', 'mutual', 'triadic'],
    prerequisites: ['bandura'],
  },
  {
    id: 'social-learning-theory',
    title: 'Social Learning Theory',
    subtitle: 'Learning Through Social Interaction',
    description: 'The broader theoretical framework that personality and behavior are learned through observation, imitation, and modeling in social contexts. Integrates behavioral principles with cognitive and social factors.',
    branch: 'personality',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'behaviorism-personality',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'users',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['observation', 'modeling', 'social'],
    prerequisites: ['behaviorism-personality'],
  },
  {
    id: 'reciprocal-determinism',
    title: 'Reciprocal Determinism',
    subtitle: 'Bidirectional Causation in Personality',
    description: 'The principle that personal factors, behavior, and environmental factors influence each other bidirectionally. Personality is not determined by any single factor but emerges from their continuous interaction.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'behaviorism-personality',
    children: [],
    unlocked: false,
    visible: true,
    x: 440,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'arrow-left-right',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['bidirectional', 'causation', 'interaction'],
    prerequisites: ['behaviorism-personality'],
  },
  {
    id: 'behavioral-assessment',
    title: 'Behavioral Assessment',
    subtitle: 'Measuring Observable Actions',
    description: 'Approaches to personality assessment that focus on observable behavior in specific situations rather than internal traits. Includes behavioral observation, self-monitoring, and functional analysis of behavior patterns.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'behaviorism-personality',
    children: [],
    unlocked: false,
    visible: true,
    x: 520,
    y: -400,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'clipboard-list',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['observation', 'measurement', 'behavior'],
    prerequisites: ['behaviorism-personality'],
  },
  {
    id: 'temperament',
    title: 'Temperament',
    subtitle: 'Biologically-Based Individual Differences',
    description: 'Constitutionally based individual differences in emotional, motor, and attentional reactivity and self-regulation, evident from early infancy. Forms the biological foundation upon which personality develops through interaction with environment.',
    branch: 'personality',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['temperament-types', 'goodness-of-fit', 'temperament-personality-link'],
    unlocked: false,
    visible: true,
    x: -400,
    y: 0,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'baby',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['biological', 'infancy', 'reactivity'],
    prerequisites: ['personality'],
  },
  {
    id: 'temperament-types',
    title: 'Temperament Types',
    subtitle: 'Early Behavioral Styles',
    description: 'Classifications of infant temperament including easy, difficult, and slow-to-warm-up patterns identified by Thomas and Chess. These early styles show moderate stability and predict later personality characteristics.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'temperament',
    children: [],
    unlocked: false,
    visible: true,
    x: -480,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'shapes',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['infant', 'styles', 'thomas-chess'],
    prerequisites: ['temperament'],
  },
  {
    id: 'goodness-of-fit',
    title: 'Goodness of Fit',
    subtitle: 'Matching Temperament to Environment',
    description: 'Thomas and Chess\'s concept that optimal development occurs when a child\'s temperament matches environmental demands and expectations. Mismatch leads to adjustment difficulties regardless of temperament quality.',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'temperament',
    children: [],
    unlocked: false,
    visible: true,
    x: -400,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'puzzle',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['match', 'environment', 'adjustment'],
    prerequisites: ['temperament'],
  },
  {
    id: 'temperament-personality-link',
    title: 'Temperament-Personality Link',
    subtitle: 'From Early Reactivity to Adult Traits',
    description: 'Research on the developmental pathways from early temperament to adult personality traits. Evidence supports moderate stability, with early inhibition predicting later introversion and negative reactivity predicting neuroticism.',
    branch: 'personality',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'temperament',
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'link',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['development', 'stability', 'continuity'],
    prerequisites: ['temperament'],
  },
  {
    id: 'locus-of-control',
    title: 'Locus of Control',
    subtitle: 'Beliefs About Personal Agency',
    description: 'Rotter\'s concept describing the extent to which individuals believe they can control events affecting them. Internal locus involves personal control; external locus attributes outcomes to chance, fate, or powerful others.',
    branch: 'personality',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['internal-locus', 'external-locus', 'locus-outcomes'],
    unlocked: false,
    visible: true,
    x: -280,
    y: 0,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'compass',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['control', 'agency', 'beliefs'],
    prerequisites: ['personality'],
  },
  {
    id: 'internal-locus',
    title: 'Internal Locus of Control',
    subtitle: 'Belief in Personal Control',
    description: 'The belief that one\'s actions and decisions primarily determine life outcomes. Associated with higher achievement motivation, better academic performance, greater political activity, and better stress coping.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'locus-of-control',
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'user-check',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['control', 'agency', 'achievement'],
    prerequisites: ['locus-of-control'],
  },
  {
    id: 'external-locus',
    title: 'External Locus of Control',
    subtitle: 'Attributing Outcomes to Outside Forces',
    description: 'The belief that life outcomes are determined by external factors such as luck, fate, or powerful others. Associated with lower achievement motivation, learned helplessness, and greater susceptibility to social influence.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'locus-of-control',
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'cloud',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['fate', 'luck', 'helplessness'],
    prerequisites: ['locus-of-control'],
  },
  {
    id: 'locus-outcomes',
    title: 'Locus of Control and Life Outcomes',
    subtitle: 'Consequences of Control Beliefs',
    description: 'Research on how locus of control beliefs predict academic achievement, health behaviors, job satisfaction, and psychological well-being. Internal locus generally predicts better outcomes, though effects are moderated by culture and context.',
    branch: 'personality',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'locus-of-control',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'trending-up',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['outcomes', 'prediction', 'well-being'],
    prerequisites: ['locus-of-control'],
  },
  {
    id: 'personality-assessment',
    title: 'Personality Assessment',
    subtitle: 'Measuring Individual Differences',
    description: 'The methods and instruments used to evaluate personality characteristics, including self-report inventories, projective tests, behavioral observation, and physiological measures. Each approach has distinct strengths and limitations.',
    branch: 'personality',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['self-report-inventories', 'projective-tests', 'mbti', 'personality-interviews'],
    unlocked: false,
    visible: true,
    x: -160,
    y: 0,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'clipboard-check',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['measurement', 'testing', 'evaluation'],
    prerequisites: ['personality'],
  },
  {
    id: 'self-report-inventories',
    title: 'Self-Report Inventories',
    subtitle: 'Questionnaire-Based Assessment',
    description: 'Personality measures in which individuals answer standardized questions about their thoughts, feelings, and behaviors. Include the MMPI, NEO-PI-R, and 16PF. Efficient but subject to social desirability and self-perception biases.',
    branch: 'personality',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality-assessment',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'file-text',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['questionnaires', 'mmpi', 'neo'],
    prerequisites: ['personality-assessment'],
  },
  {
    id: 'projective-tests',
    title: 'Projective Tests',
    subtitle: 'Ambiguous Stimuli Reveal Unconscious',
    description: 'Personality assessment techniques using ambiguous stimuli to elicit responses that reveal unconscious conflicts, motives, and personality dynamics. Include the Rorschach inkblot test and Thematic Apperception Test (TAT).',
    branch: 'personality',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality-assessment',
    children: ['rorschach-test', 'tat-test'],
    unlocked: false,
    visible: true,
    x: -160,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'image',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['rorschach', 'tat', 'unconscious'],
    prerequisites: ['personality-assessment'],
  },
  {
    id: 'rorschach-test',
    title: 'Rorschach Inkblot Test',
    subtitle: 'Interpreting Ambiguous Visual Stimuli',
    description: 'A projective test using ten symmetrical inkblots in which respondents describe what they see. Responses are scored for location, content, and determinants to infer personality characteristics and psychological functioning.',
    branch: 'personality',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'projective-tests',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -200,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'droplets',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['rorschach', 'inkblot', 'interpretation'],
    prerequisites: ['projective-tests'],
  },
  {
    id: 'tat-test',
    title: 'Thematic Apperception Test',
    subtitle: 'Stories Reveal Motives',
    description: 'A projective test in which respondents create stories about ambiguous pictures of people in various situations. Responses are analyzed for themes of achievement, affiliation, power, and other motives, as well as emotional states.',
    branch: 'personality',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'projective-tests',
    children: [],
    unlocked: false,
    visible: true,
    x: -120,
    y: -200,
    radius: 20,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.15)',
    iconName: 'book-open',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['tat', 'stories', 'motives'],
    prerequisites: ['projective-tests'],
  },
  {
    id: 'mbti',
    title: 'Myers-Briggs Type Indicator',
    subtitle: 'Popular Framework with Scientific Context',
    description: 'A widely used personality inventory based on Jung\'s theory of psychological types, classifying individuals into 16 types across four dichotomies. Popular in organizational settings but criticized by researchers for poor psychometric properties and lack of predictive validity compared to the Big Five.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality-assessment',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'grid',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['myers-briggs', 'types', 'popular'],
    prerequisites: ['personality-assessment'],
  },
  {
    id: 'personality-interviews',
    title: 'Clinical Interviews',
    subtitle: 'Structured and Unstructured Assessment',
    description: 'Face-to-face methods of personality assessment ranging from unstructured clinical interviews to structured diagnostic interviews. Allow for rapport building and observation of behavior but are subject to interviewer bias.',
    branch: 'personality',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality-assessment',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'message-square',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['clinical', 'face-to-face', 'rapport'],
    prerequisites: ['personality-assessment'],
  },
  {
    id: 'motivation',
    title: 'Motivation',
    subtitle: 'Forces That Energize and Direct Behavior',
    description: 'The psychological processes that initiate, guide, and maintain goal-oriented behaviors. Examined through biological, cognitive, and humanistic perspectives, with applications to achievement, work, and personal development.',
    branch: 'personality',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['intrinsic-motivation', 'extrinsic-motivation', 'achievement-motivation', 'goal-setting-theory'],
    unlocked: false,
    visible: true,
    x: -40,
    y: 0,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'zap',
    difficulty: 'beginner',
    estimatedMinutes: 30,
    tags: ['drive', 'goals', 'behavior'],
    prerequisites: ['personality'],
  },
  {
    id: 'intrinsic-motivation',
    title: 'Intrinsic Motivation',
    subtitle: 'Engagement for Its Own Sake',
    description: 'Behavior driven by internal rewards such as enjoyment, interest, and satisfaction rather than external consequences. Associated with greater creativity, persistence, and well-being than extrinsic motivation.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'motivation',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'heart',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['internal', 'enjoyment', 'interest'],
    prerequisites: ['motivation'],
  },
  {
    id: 'extrinsic-motivation',
    title: 'Extrinsic Motivation',
    subtitle: 'External Rewards and Punishments',
    description: 'Behavior driven by external factors such as rewards, grades, money, or avoidance of punishment. Can undermine intrinsic motivation when overused (overjustification effect) but is effective for routine tasks.',
    branch: 'personality',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'motivation',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'gift',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['external', 'rewards', 'punishment'],
    prerequisites: ['motivation'],
  },
  {
    id: 'achievement-motivation',
    title: 'Achievement Motivation',
    subtitle: 'Drive to Excel and Succeed',
    description: 'The need to accomplish difficult tasks, attain high standards, and outperform others. High achievement motivation predicts entrepreneurial behavior, academic success, and career advancement. Measured by the Thematic Apperception Test.',
    branch: 'personality',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'motivation',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'trophy',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['excel', 'success', 'mcclelland'],
    prerequisites: ['motivation'],
  },
  {
    id: 'goal-setting-theory',
    title: 'Goal-Setting Theory',
    subtitle: 'Specific and Challenging Goals Drive Performance',
    description: 'Locke and Latham\'s theory that specific, challenging goals lead to higher performance than easy or vague goals. Goal commitment, feedback, and task complexity moderate the relationship between goals and performance.',
    branch: 'personality',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'motivation',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'target',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['locke', 'latham', 'goals'],
    prerequisites: ['motivation'],
  },
  {
    id: 'self-concept',
    title: 'Self-Concept',
    subtitle: 'The Sum of Beliefs About Oneself',
    description: 'The overall set of beliefs that individuals have about themselves, including self-esteem, self-image, and ideal self. Shapes behavior, emotional experience, and social interactions throughout the lifespan.',
    branch: 'personality',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'personality',
    children: ['self-esteem', 'self-schema', 'possible-selves', 'self-discrepancy'],
    unlocked: false,
    visible: true,
    x: 80,
    y: 0,
    radius: 34,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.25)',
    iconName: 'user',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['self', 'identity', 'beliefs'],
    prerequisites: ['personality'],
  },
  {
    id: 'self-esteem',
    title: 'Self-Esteem',
    subtitle: 'Overall Evaluation of Self-Worth',
    description: 'An individual\'s subjective evaluation of their own worth. High self-esteem is associated with better mental health, resilience, and social relationships, though excessive self-esteem can predict narcissism and aggression.',
    branch: 'personality',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'self-concept',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'smile',
    difficulty: 'beginner',
    estimatedMinutes: 20,
    tags: ['worth', 'evaluation', 'confidence'],
    prerequisites: ['self-concept'],
  },
  {
    id: 'self-schema',
    title: 'Self-Schema',
    subtitle: 'Cognitive Structures About the Self',
    description: 'Cognitive generalizations about the self derived from past experience that guide the processing of self-relevant information. Self-schemas influence what we notice, remember, and believe about ourselves.',
    branch: 'personality',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'self-concept',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'brain',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['cognitive', 'structure', 'processing'],
    prerequisites: ['self-concept'],
  },
  {
    id: 'possible-selves',
    title: 'Possible Selves',
    subtitle: 'Future Representations of the Self',
    description: 'Markus and Nurius\'s concept of the selves that individuals might become, would like to become, or are afraid of becoming. Motivate behavior by providing concrete representations of goals and fears.',
    branch: 'personality',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'self-concept',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'git-branch',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['future', 'goals', 'markus'],
    prerequisites: ['self-concept'],
  },
  {
    id: 'self-discrepancy',
    title: 'Self-Discrepancy Theory',
    subtitle: 'Gaps Between Self-Views',
    description: 'Higgins\'s theory that emotional distress arises from discrepancies between the actual self, ideal self, and ought self. Actual-ideal discrepancies produce dejection; actual-ought discrepancies produce agitation.',
    branch: 'personality',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'self-concept',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -120,
    radius: 26,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.20)',
    iconName: 'minus',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    tags: ['higgins', 'discrepancy', 'emotion'],
    prerequisites: ['self-concept'],
  },
];
