export interface TreeNode {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  branch: string;
  level: number;
  xp: number;
  status: "mastered" | "available" | "locked";
  progress: number;
  completed: number;
  total: number;
  parent: string | null;
  children: string[];
  unlocked: boolean;
  visible: boolean;
  x: number;
  y: number;
  radius: number;
  color: string;
  glow: boolean;
  iconName: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced" | "Expert";
  estimatedMinutes: number;
  tags: string[];
  prerequisites: string[];
}

export const researchNodes: TreeNode[] = [
  {
    id: "research-methods",
    title: "Research Methods",
    subtitle: "The Foundation of Psychological Science",
    description: "Master the systematic approaches psychologists use to investigate behavior, cognition, and mental processes with rigor and ethical integrity.",
    branch: "Research Methods",
    level: 0,
    xp: 0,
    status: "mastered",
    progress: 100,
    completed: 5,
    total: 5,
    parent: null,
    children: ["scientific-method", "variables", "hypothesis", "sampling", "research-design", "reliability", "validity", "ethics", "qualitative-research", "quantitative-research", "mixed-methods"],
    unlocked: true,
    visible: true,
    x: 0,
    y: 0,
    radius: 48,
    color: "#8B5CF6",
    glow: true,
    iconName: "microscope",
    difficulty: "Beginner",
    estimatedMinutes: 0,
    tags: ["research", "methods", "foundation"],
    prerequisites: [],
  },
  {
    id: "scientific-method",
    title: "Scientific Method",
    subtitle: "Systematic Inquiry in Psychology",
    description: "Learn the iterative cycle of observation, hypothesis formation, experimentation, and theory building that underpins all psychological research.",
    branch: "Research Methods",
    level: 1,
    xp: 60,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "research-methods",
    children: ["theory-construction", "falsifiability", "replication"],
    unlocked: true,
    visible: true,
    x: -280,
    y: 140,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "flask",
    difficulty: "Beginner",
    estimatedMinutes: 25,
    tags: ["scientific-method", "inquiry", "theory"],
    prerequisites: ["research-methods"],
  },
  {
    id: "variables",
    title: "Variables",
    subtitle: "Independent, Dependent, and Control",
    description: "Understand how researchers manipulate, measure, and control variables to establish causal and correlational relationships in psychological studies.",
    branch: "Research Methods",
    level: 1,
    xp: 55,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "research-methods",
    children: ["operational-definition", "confounding-variables"],
    unlocked: true,
    visible: true,
    x: -140,
    y: 160,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "sliders",
    difficulty: "Beginner",
    estimatedMinutes: 20,
    tags: ["variables", "iv-dv", "control"],
    prerequisites: ["research-methods"],
  },
  {
    id: "hypothesis",
    title: "Hypothesis",
    subtitle: "Formulating Testable Predictions",
    description: "Develop the skill of crafting clear, falsifiable hypotheses including null and alternative hypotheses with directional and non-directional forms.",
    branch: "Research Methods",
    level: 1,
    xp: 50,
    status: "available",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "research-methods",
    children: ["predictive-hypothesis", "hypothesis-testing"],
    unlocked: true,
    visible: true,
    x: 0,
    y: 170,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "lightbulb",
    difficulty: "Beginner",
    estimatedMinutes: 18,
    tags: ["hypothesis", "prediction", "falsifiable"],
    prerequisites: ["research-methods"],
  },
  {
    id: "sampling",
    title: "Sampling",
    subtitle: "Selecting Participants for Research",
    description: "Explore probability and non-probability sampling techniques, sample size determination, and the critical distinction between samples and populations.",
    branch: "Research Methods",
    level: 1,
    xp: 65,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "research-methods",
    children: ["random-sampling", "sample-size", "sampling-bias"],
    unlocked: true,
    visible: true,
    x: 140,
    y: 160,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "users",
    difficulty: "Beginner",
    estimatedMinutes: 28,
    tags: ["sampling", "population", "selection"],
    prerequisites: ["research-methods"],
  },
  {
    id: "research-design",
    title: "Research Design",
    subtitle: "Structuring Psychological Studies",
    description: "Learn to select and justify appropriate research designs that align with research questions, ethical constraints, and available resources.",
    branch: "Research Methods",
    level: 1,
    xp: 70,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "research-methods",
    children: ["experiments", "observation", "survey", "case-study"],
    unlocked: true,
    visible: true,
    x: 280,
    y: 140,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "layout",
    difficulty: "Beginner",
    estimatedMinutes: 30,
    tags: ["design", "structure", "planning"],
    prerequisites: ["research-methods"],
  },
  {
    id: "theory-construction",
    title: "Theory Construction",
    subtitle: "Building Explanatory Frameworks",
    description: "Understand how empirical findings are synthesized into coherent theoretical models that explain, predict, and generate new hypotheses about psychological phenomena.",
    branch: "Research Methods",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "scientific-method",
    children: ["parsimony", "theory-revision"],
    unlocked: false,
    visible: true,
    x: -380,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "building",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["theory", "framework", "explanation"],
    prerequisites: ["scientific-method"],
  },
  {
    id: "falsifiability",
    title: "Falsifiability",
    subtitle: "The Criterion of Demarcation",
    description: "Study Karl Popper's principle that for a theory to be scientific, it must be capable of being proven false through empirical observation.",
    branch: "Research Methods",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "scientific-method",
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: 320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "shield-x",
    difficulty: "Intermediate",
    estimatedMinutes: 30,
    tags: ["falsifiability", "popper", "demarcation"],
    prerequisites: ["scientific-method"],
  },
  {
    id: "replication",
    title: "Replication",
    subtitle: "Reproducing Research Findings",
    description: "Examine direct, conceptual, and systematic replication as essential practices for verifying results, identifying false positives, and building cumulative knowledge.",
    branch: "Research Methods",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "scientific-method",
    children: ["replication-crisis", "open-science"],
    unlocked: false,
    visible: true,
    x: -180,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "repeat",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["replication", "reproducibility", "verification"],
    prerequisites: ["scientific-method"],
  },
  {
    id: "operational-definition",
    title: "Operational Definition",
    subtitle: "Making Concepts Measurable",
    description: "Learn to translate abstract psychological constructs into precise, observable, and measurable procedures that enable empirical investigation.",
    branch: "Research Methods",
    level: 2,
    xp: 100,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "variables",
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: 320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "ruler",
    difficulty: "Intermediate",
    estimatedMinutes: 25,
    tags: ["operationalization", "measurement", "constructs"],
    prerequisites: ["variables"],
  },
  {
    id: "confounding-variables",
    title: "Confounding Variables",
    subtitle: "Threats to Internal Validity",
    description: "Identify extraneous variables that systematically vary with the independent variable, threatening the ability to infer causal relationships.",
    branch: "Research Methods",
    level: 2,
    xp: 115,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "variables",
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: 310,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "alert-triangle",
    difficulty: "Intermediate",
    estimatedMinutes: 32,
    tags: ["confounds", "extraneous", "threats"],
    prerequisites: ["variables"],
  },
  {
    id: "predictive-hypothesis",
    title: "Predictive Hypothesis",
    subtitle: "Directional vs Non-Directional",
    description: "Distinguish between one-tailed and two-tailed hypotheses, understanding when each is appropriate and the statistical implications of each choice.",
    branch: "Research Methods",
    level: 2,
    xp: 105,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "hypothesis",
    children: [],
    unlocked: false,
    visible: true,
    x: -40,
    y: 320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "arrow-right",
    difficulty: "Intermediate",
    estimatedMinutes: 28,
    tags: ["directional", "prediction", "tails"],
    prerequisites: ["hypothesis"],
  },
  {
    id: "hypothesis-testing",
    title: "Hypothesis Testing",
    subtitle: "Null and Alternative Frameworks",
    description: "Master the logic of null hypothesis significance testing, Type I and Type II errors, and the decision-making process in statistical inference.",
    branch: "Research Methods",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "hypothesis",
    children: ["statistical-significance", "effect-size"],
    unlocked: false,
    visible: true,
    x: 40,
    y: 330,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "check-circle",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["nhst", "errors", "inference"],
    prerequisites: ["hypothesis"],
  },
  {
    id: "random-sampling",
    title: "Random Sampling",
    subtitle: "Probability-Based Selection",
    description: "Explore simple random, stratified, cluster, and systematic sampling methods that maximize representativeness and generalizability.",
    branch: "Research Methods",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "sampling",
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: 310,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "shuffle",
    difficulty: "Intermediate",
    estimatedMinutes: 30,
    tags: ["random", "probability", "selection"],
    prerequisites: ["sampling"],
  },
  {
    id: "sample-size",
    title: "Sample Size",
    subtitle: "Power and Precision",
    description: "Learn power analysis, effect size considerations, and the trade-offs between statistical power, precision, and practical constraints.",
    branch: "Research Methods",
    level: 2,
    xp: 135,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "sampling",
    children: ["statistical-power"],
    unlocked: false,
    visible: true,
    x: 160,
    y: 320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "bar-chart",
    difficulty: "Intermediate",
    estimatedMinutes: 42,
    tags: ["power", "precision", "n-size"],
    prerequisites: ["sampling"],
  },
  {
    id: "sampling-bias",
    title: "Sampling Bias",
    subtitle: "Threats to Generalizability",
    description: "Recognize selection bias, self-selection, survivorship bias, and other sampling distortions that compromise external validity.",
    branch: "Research Methods",
    level: 2,
    xp: 125,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "sampling",
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "filter",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["bias", "generalizability", "distortion"],
    prerequisites: ["sampling"],
  },
  {
    id: "experiments",
    title: "Experiments",
    subtitle: "Controlled Causal Investigation",
    description: "Study laboratory, field, and natural experiments with emphasis on random assignment, control groups, and causal inference.",
    branch: "Research Methods",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "research-design",
    children: ["experimental-designs", "quasi-experiments"],
    unlocked: false,
    visible: true,
    x: 200,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "test-tube",
    difficulty: "Intermediate",
    estimatedMinutes: 50,
    tags: ["experiment", "causality", "control"],
    prerequisites: ["research-design"],
  },
  {
    id: "observation",
    title: "Observation",
    subtitle: "Systematic Behavioral Recording",
    description: "Master participant and non-participant observation, structured and unstructured formats, and behavioral coding systems.",
    branch: "Research Methods",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "research-design",
    children: ["naturalistic-observation", "participant-observation"],
    unlocked: false,
    visible: true,
    x: 300,
    y: 310,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "eye",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["observation", "behavior", "recording"],
    prerequisites: ["research-design"],
  },
  {
    id: "survey",
    title: "Survey",
    subtitle: "Questionnaire and Interview Methods",
    description: "Design valid and reliable surveys, understand questionnaire construction, Likert scales, and interview techniques for data collection.",
    branch: "Research Methods",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "research-design",
    children: ["questionnaire-design", "interview-methods"],
    unlocked: false,
    visible: true,
    x: 380,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "clipboard",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["survey", "questionnaire", "interview"],
    prerequisites: ["research-design"],
  },
  {
    id: "case-study",
    title: "Case Study",
    subtitle: "In-Depth Individual Analysis",
    description: "Explore intensive investigation of single cases, individuals, or events, including clinical, developmental, and neuropsychological applications.",
    branch: "Research Methods",
    level: 2,
    xp: 115,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "research-design",
    children: ["single-case-designs"],
    unlocked: false,
    visible: true,
    x: 460,
    y: 280,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "user",
    difficulty: "Intermediate",
    estimatedMinutes: 32,
    tags: ["case-study", "individual", "depth"],
    prerequisites: ["research-design"],
  },
  {
    id: "reliability",
    title: "Reliability",
    subtitle: "Consistency of Measurement",
    description: "Study test-retest, inter-rater, internal consistency, and parallel forms reliability as foundations of trustworthy psychological measurement.",
    branch: "Research Methods",
    level: 1,
    xp: 75,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "research-methods",
    children: ["test-retest", "inter-rater-reliability", "cronbach-alpha"],
    unlocked: true,
    visible: true,
    x: -320,
    y: 140,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "refresh-cw",
    difficulty: "Beginner",
    estimatedMinutes: 28,
    tags: ["reliability", "consistency", "measurement"],
    prerequisites: ["research-methods"],
  },
  {
    id: "validity",
    title: "Validity",
    subtitle: "Accuracy of Measurement and Inference",
    description: "Distinguish between internal, external, construct, and statistical conclusion validity as criteria for evaluating research quality.",
    branch: "Research Methods",
    level: 1,
    xp: 80,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "research-methods",
    children: ["internal-validity", "external-validity", "construct-validity"],
    unlocked: true,
    visible: true,
    x: 320,
    y: 140,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "check-square",
    difficulty: "Beginner",
    estimatedMinutes: 30,
    tags: ["validity", "accuracy", "inference"],
    prerequisites: ["research-methods"],
  },
  {
    id: "ethics",
    title: "Ethics",
    subtitle: "Responsible Research Conduct",
    description: "Understand informed consent, confidentiality, debriefing, and institutional review as essential safeguards for research participants.",
    branch: "Research Methods",
    level: 1,
    xp: 70,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "research-methods",
    children: ["informed-consent", "deception", "animal-ethics"],
    unlocked: true,
    visible: true,
    x: 0,
    y: -160,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "heart",
    difficulty: "Beginner",
    estimatedMinutes: 25,
    tags: ["ethics", "consent", "responsibility"],
    prerequisites: ["research-methods"],
  },
  {
    id: "qualitative-research",
    title: "Qualitative Research",
    subtitle: "Exploratory and Interpretive Methods",
    description: "Explore phenomenology, grounded theory, ethnography, and thematic analysis as approaches to understanding subjective experience.",
    branch: "Research Methods",
    level: 1,
    xp: 85,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "research-methods",
    children: ["thematic-analysis", "grounded-theory", "phenomenology"],
    unlocked: true,
    visible: true,
    x: -160,
    y: -140,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "message-circle",
    difficulty: "Beginner",
    estimatedMinutes: 35,
    tags: ["qualitative", "interpretive", "exploratory"],
    prerequisites: ["research-methods"],
  },
  {
    id: "quantitative-research",
    title: "Quantitative Research",
    subtitle: "Statistical and Numerical Analysis",
    description: "Learn correlational, experimental, and longitudinal designs that produce numerical data analyzed through statistical inference.",
    branch: "Research Methods",
    level: 1,
    xp: 90,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "research-methods",
    children: ["correlational-design", "longitudinal-study", "cross-sectional"],
    unlocked: true,
    visible: true,
    x: 160,
    y: -140,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "pie-chart",
    difficulty: "Beginner",
    estimatedMinutes: 38,
    tags: ["quantitative", "statistical", "numerical"],
    prerequisites: ["research-methods"],
  },
  {
    id: "mixed-methods",
    title: "Mixed Methods",
    subtitle: "Integrating Qualitative and Quantitative",
    description: "Study convergent, explanatory sequential, and exploratory sequential designs that combine numerical and narrative data.",
    branch: "Research Methods",
    level: 1,
    xp: 100,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "research-methods",
    children: ["triangulation", "convergent-design"],
    unlocked: true,
    visible: true,
    x: 0,
    y: -170,
    radius: 36,
    color: "#A78BFA",
    glow: false,
    iconName: "git-merge",
    difficulty: "Intermediate",
    estimatedMinutes: 42,
    tags: ["mixed-methods", "integration", "triangulation"],
    prerequisites: ["research-methods"],
  },
  {
    id: "internal-validity",
    title: "Internal Validity",
    subtitle: "Causal Inference Confidence",
    description: "Identify threats including history, maturation, testing, instrumentation, regression, selection, and attrition that compromise causal conclusions.",
    branch: "Research Methods",
    level: 2,
    xp: 145,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "validity",
    children: ["experimental-control"],
    unlocked: false,
    visible: true,
    x: 280,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "lock",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["internal", "causality", "threats"],
    prerequisites: ["validity"],
  },
  {
    id: "external-validity",
    title: "External Validity",
    subtitle: "Generalizability Across Contexts",
    description: "Evaluate population, ecological, temporal, and construct generalizability to determine how broadly findings can be applied.",
    branch: "Research Methods",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "validity",
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: 310,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "globe",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["external", "generalizability", "context"],
    prerequisites: ["validity"],
  },
  {
    id: "construct-validity",
    title: "Construct Validity",
    subtitle: "Measuring What We Intend",
    description: "Understand convergent, discriminant, and factorial validity as evidence that a measure actually assesses the theoretical construct.",
    branch: "Research Methods",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "validity",
    children: ["factor-analysis"],
    unlocked: false,
    visible: true,
    x: 440,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "box",
    difficulty: "Intermediate",
    estimatedMinutes: 48,
    tags: ["construct", "convergent", "discriminant"],
    prerequisites: ["validity"],
  },
  {
    id: "test-retest",
    title: "Test-Retest Reliability",
    subtitle: "Temporal Consistency",
    description: "Assess stability of measurement over time, understanding practice effects and the appropriate intervals for retesting.",
    branch: "Research Methods",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "reliability",
    children: [],
    unlocked: false,
    visible: true,
    x: -400,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "clock",
    difficulty: "Intermediate",
    estimatedMinutes: 28,
    tags: ["test-retest", "stability", "temporal"],
    prerequisites: ["reliability"],
  },
  {
    id: "inter-rater-reliability",
    title: "Inter-Rater Reliability",
    subtitle: "Agreement Between Observers",
    description: "Measure consistency across multiple raters using Cohen's kappa, intraclass correlation, and percent agreement statistics.",
    branch: "Research Methods",
    level: 2,
    xp: 125,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "reliability",
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: 320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "users",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["inter-rater", "agreement", "observers"],
    prerequisites: ["reliability"],
  },
  {
    id: "cronbach-alpha",
    title: "Cronbach's Alpha",
    subtitle: "Internal Consistency Coefficient",
    description: "Calculate and interpret internal consistency reliability, understanding item-total correlations and acceptable threshold values.",
    branch: "Research Methods",
    level: 2,
    xp: 135,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "reliability",
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: 300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "align-center",
    difficulty: "Intermediate",
    estimatedMinutes: 38,
    tags: ["cronbach", "alpha", "internal"],
    prerequisites: ["reliability"],
  },
  {
    id: "informed-consent",
    title: "Informed Consent",
    subtitle: "Voluntary Participation",
    description: "Understand the elements of valid informed consent including competence, disclosure, comprehension, voluntariness, and ongoing consent.",
    branch: "Research Methods",
    level: 2,
    xp: 115,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "ethics",
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "file-text",
    difficulty: "Intermediate",
    estimatedMinutes: 30,
    tags: ["consent", "voluntary", "disclosure"],
    prerequisites: ["ethics"],
  },
  {
    id: "deception",
    title: "Deception",
    subtitle: "Ethical Use in Research",
    description: "Evaluate when and how deception may be ethically justified, including debriefing requirements and minimization principles.",
    branch: "Research Methods",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "ethics",
    children: ["debriefing"],
    unlocked: false,
    visible: true,
    x: 0,
    y: -320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "mask",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["deception", "ethics", "debriefing"],
    prerequisites: ["ethics"],
  },
  {
    id: "animal-ethics",
    title: "Animal Ethics",
    subtitle: "Research with Non-Human Subjects",
    description: "Study the three Rs (replacement, reduction, refinement) and institutional animal care standards in psychological research.",
    branch: "Research Methods",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "ethics",
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "paw-print",
    difficulty: "Intermediate",
    estimatedMinutes: 32,
    tags: ["animals", "three-rs", "welfare"],
    prerequisites: ["ethics"],
  },
  {
    id: "thematic-analysis",
    title: "Thematic Analysis",
    subtitle: "Identifying Patterns in Qualitative Data",
    description: "Learn Braun and Clarke's six-phase approach to identifying, analyzing, and reporting themes within qualitative datasets.",
    branch: "Research Methods",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "qualitative-research",
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "layers",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["thematic", "patterns", "qualitative"],
    prerequisites: ["qualitative-research"],
  },
  {
    id: "grounded-theory",
    title: "Grounded Theory",
    subtitle: "Theory Emergence from Data",
    description: "Study the iterative process of constant comparison, theoretical sampling, and memoing to develop theory from qualitative data.",
    branch: "Research Methods",
    level: 2,
    xp: 155,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "qualitative-research",
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: -320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "sprout",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["grounded", "theory", "emergence"],
    prerequisites: ["qualitative-research"],
  },
  {
    id: "phenomenology",
    title: "Phenomenology",
    subtitle: "Lived Experience Investigation",
    description: "Explore Husserlian and Heideggerian approaches to understanding the essence of human experience through bracketing and interpretation.",
    branch: "Research Methods",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "qualitative-research",
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "sun",
    difficulty: "Advanced",
    estimatedMinutes: 52,
    tags: ["phenomenology", "experience", "essence"],
    prerequisites: ["qualitative-research"],
  },
  {
    id: "correlational-design",
    title: "Correlational Design",
    subtitle: "Measuring Relationships Between Variables",
    description: "Understand Pearson, Spearman, and partial correlations while recognizing that correlation does not imply causation.",
    branch: "Research Methods",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "quantitative-research",
    children: ["multiple-regression"],
    unlocked: false,
    visible: true,
    x: 120,
    y: -300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "trending-up",
    difficulty: "Intermediate",
    estimatedMinutes: 38,
    tags: ["correlation", "relationship", "association"],
    prerequisites: ["quantitative-research"],
  },
  {
    id: "longitudinal-study",
    title: "Longitudinal Study",
    subtitle: "Tracking Changes Over Time",
    description: "Study prospective and retrospective longitudinal designs, understanding cohort effects, attrition, and developmental trajectories.",
    branch: "Research Methods",
    level: 2,
    xp: 145,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "quantitative-research",
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "calendar",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["longitudinal", "time", "development"],
    prerequisites: ["quantitative-research"],
  },
  {
    id: "cross-sectional",
    title: "Cross-Sectional Design",
    subtitle: "Snapshot Data Collection",
    description: "Evaluate the efficiency and limitations of collecting data at a single time point across different age groups or populations.",
    branch: "Research Methods",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "quantitative-research",
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -300,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "camera",
    difficulty: "Intermediate",
    estimatedMinutes: 28,
    tags: ["cross-sectional", "snapshot", "comparison"],
    prerequisites: ["quantitative-research"],
  },
  {
    id: "triangulation",
    title: "Triangulation",
    subtitle: "Converging Evidence from Multiple Sources",
    description: "Apply data, method, investigator, and theoretical triangulation to strengthen validity and provide comprehensive understanding.",
    branch: "Research Methods",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "mixed-methods",
    children: [],
    unlocked: false,
    visible: true,
    x: -60,
    y: -320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "triangle",
    difficulty: "Advanced",
    estimatedMinutes: 48,
    tags: ["triangulation", "convergence", "mixed"],
    prerequisites: ["mixed-methods"],
  },
  {
    id: "convergent-design",
    title: "Convergent Design",
    subtitle: "Parallel Qualitative and Quantitative Collection",
    description: "Implement simultaneous data collection and integration strategies that merge quantitative and qualitative findings for comprehensive results.",
    branch: "Research Methods",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "mixed-methods",
    children: [],
    unlocked: false,
    visible: true,
    x: 60,
    y: -320,
    radius: 30,
    color: "#C4B5FD",
    glow: false,
    iconName: "merge",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["convergent", "parallel", "integration"],
    prerequisites: ["mixed-methods"],
  },
  {
    id: "parsimony",
    title: "Parsimony",
    subtitle: "Occam's Razor in Theory Building",
    description: "Apply the principle that among competing explanations, the simplest one with the fewest assumptions should be selected.",
    branch: "Research Methods",
    level: 3,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "theory-construction",
    children: [],
    unlocked: false,
    visible: true,
    x: -440,
    y: 460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "scissors",
    difficulty: "Advanced",
    estimatedMinutes: 35,
    tags: ["parsimony", "occam", "simplicity"],
    prerequisites: ["theory-construction"],
  },
  {
    id: "theory-revision",
    title: "Theory Revision",
    subtitle: "Updating Models with New Evidence",
    description: "Understand how anomalous findings drive theory modification, refinement, or replacement in the cumulative process of scientific knowledge.",
    branch: "Research Methods",
    level: 3,
    xp: 240,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "theory-construction",
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: 480,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "refresh-ccw",
    difficulty: "Advanced",
    estimatedMinutes: 42,
    tags: ["revision", "anomaly", "update"],
    prerequisites: ["theory-construction"],
  },
  {
    id: "replication-crisis",
    title: "Replication Crisis",
    subtitle: "Challenges in Psychological Science",
    description: "Examine the systematic failure to reproduce classic findings, exploring publication bias, p-hacking, and reform initiatives.",
    branch: "Research Methods",
    level: 3,
    xp: 260,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "replication",
    children: [],
    unlocked: false,
    visible: true,
    x: -220,
    y: 460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "alert-octagon",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["crisis", "reproducibility", "reform"],
    prerequisites: ["replication"],
  },
  {
    id: "open-science",
    title: "Open Science",
    subtitle: "Transparency and Open Practices",
    description: "Learn preregistration, open data, open materials, and registered reports as tools to increase transparency and reproducibility.",
    branch: "Research Methods",
    level: 3,
    xp: 280,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "replication",
    children: [],
    unlocked: false,
    visible: true,
    x: -140,
    y: 480,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "unlock",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["open-science", "transparency", "preregistration"],
    prerequisites: ["replication"],
  },
  {
    id: "statistical-significance",
    title: "Statistical Significance",
    subtitle: "P-Values and Decision Thresholds",
    description: "Interpret p-values, alpha levels, and confidence intervals while understanding the distinction between statistical and practical significance.",
    branch: "Research Methods",
    level: 3,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "hypothesis-testing",
    children: [],
    unlocked: false,
    visible: true,
    x: 20,
    y: 480,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "activity",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["p-value", "significance", "alpha"],
    prerequisites: ["hypothesis-testing"],
  },
  {
    id: "effect-size",
    title: "Effect Size",
    subtitle: "Magnitude of Research Findings",
    description: "Calculate and interpret Cohen's d, eta-squared, and odds ratios to quantify the practical importance of research effects.",
    branch: "Research Methods",
    level: 3,
    xp: 210,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "hypothesis-testing",
    children: [],
    unlocked: false,
    visible: true,
    x: 100,
    y: 460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "maximize",
    difficulty: "Advanced",
    estimatedMinutes: 48,
    tags: ["effect-size", "magnitude", "practical"],
    prerequisites: ["hypothesis-testing"],
  },
  {
    id: "statistical-power",
    title: "Statistical Power",
    subtitle: "Probability of Detecting True Effects",
    description: "Calculate power using G*Power, understand the relationship between alpha, effect size, sample size, and beta error.",
    branch: "Research Methods",
    level: 3,
    xp: 230,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "sample-size",
    children: [],
    unlocked: false,
    visible: true,
    x: 180,
    y: 480,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "zap",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["power", "beta", "detection"],
    prerequisites: ["sample-size"],
  },
  {
    id: "experimental-designs",
    title: "Experimental Designs",
    subtitle: "Between, Within, and Factorial",
    description: "Distinguish between-subjects, within-subjects, and mixed designs, including factorial arrangements and counterbalancing strategies.",
    branch: "Research Methods",
    level: 3,
    xp: 250,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "experiments",
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: 460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "grid",
    difficulty: "Advanced",
    estimatedMinutes: 55,
    tags: ["designs", "factorial", "counterbalancing"],
    prerequisites: ["experiments"],
  },
  {
    id: "quasi-experiments",
    title: "Quasi-Experiments",
    subtitle: "Non-Randomized Causal Designs",
    description: "Evaluate nonequivalent group, interrupted time series, and regression discontinuity designs when randomization is impossible.",
    branch: "Research Methods",
    level: 3,
    xp: 270,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "experiments",
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: 480,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "git-branch",
    difficulty: "Advanced",
    estimatedMinutes: 58,
    tags: ["quasi", "non-randomized", "causal"],
    prerequisites: ["experiments"],
  },
  {
    id: "naturalistic-observation",
    title: "Naturalistic Observation",
    subtitle: "Unobtrusive Behavioral Study",
    description: "Conduct observation in natural settings without intervention, managing observer bias and reactivity through systematic protocols.",
    branch: "Research Methods",
    level: 3,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "observation",
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: 460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "binoculars",
    difficulty: "Advanced",
    estimatedMinutes: 40,
    tags: ["naturalistic", "unobtrusive", "field"],
    prerequisites: ["observation"],
  },
  {
    id: "participant-observation",
    title: "Participant Observation",
    subtitle: "Immersion in the Research Setting",
    description: "Balance involvement and detachment as a participant-observer, managing role conflict and maintaining analytical perspective.",
    branch: "Research Methods",
    level: 3,
    xp: 190,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "observation",
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: 480,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "user-check",
    difficulty: "Advanced",
    estimatedMinutes: 42,
    tags: ["participant", "immersion", "ethnography"],
    prerequisites: ["observation"],
  },
  {
    id: "questionnaire-design",
    title: "Questionnaire Design",
    subtitle: "Constructing Valid Instruments",
    description: "Apply principles of item writing, response formats, pilot testing, and cognitive interviewing to develop robust questionnaires.",
    branch: "Research Methods",
    level: 3,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "survey",
    children: [],
    unlocked: false,
    visible: true,
    x: 340,
    y: 460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "file-question",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["questionnaire", "design", "instrument"],
    prerequisites: ["survey"],
  },
  {
    id: "interview-methods",
    title: "Interview Methods",
    subtitle: "Structured, Semi-Structured, and Unstructured",
    description: "Conduct effective interviews using appropriate formats, probing techniques, and rapport-building strategies for rich data collection.",
    branch: "Research Methods",
    level: 3,
    xp: 185,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "survey",
    children: [],
    unlocked: false,
    visible: true,
    x: 420,
    y: 480,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "mic",
    difficulty: "Advanced",
    estimatedMinutes: 40,
    tags: ["interview", "qualitative", "rapport"],
    prerequisites: ["survey"],
  },
  {
    id: "single-case-designs",
    title: "Single-Case Designs",
    subtitle: "ABAB and Multiple Baseline",
    description: "Design and analyze single-subject experiments using reversal, multiple baseline, and changing criterion designs.",
    branch: "Research Methods",
    level: 3,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "case-study",
    children: [],
    unlocked: false,
    visible: true,
    x: 500,
    y: 440,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "user-minus",
    difficulty: "Advanced",
    estimatedMinutes: 48,
    tags: ["single-case", "abdesign", "baseline"],
    prerequisites: ["case-study"],
  },
  {
    id: "experimental-control",
    title: "Experimental Control",
    subtitle: "Eliminating Alternative Explanations",
    description: "Implement randomization, blinding, placebo controls, and statistical control to isolate causal effects from confounding influences.",
    branch: "Research Methods",
    level: 3,
    xp: 240,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "internal-validity",
    children: [],
    unlocked: false,
    visible: true,
    x: 300,
    y: 460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "shield-check",
    difficulty: "Advanced",
    estimatedMinutes: 52,
    tags: ["control", "blinding", "placebo"],
    prerequisites: ["internal-validity"],
  },
  {
    id: "factor-analysis",
    title: "Factor Analysis",
    subtitle: "Dimensionality Reduction",
    description: "Conduct exploratory and confirmatory factor analysis to identify latent structures underlying observed variables.",
    branch: "Research Methods",
    level: 3,
    xp: 420,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "construct-validity",
    children: [],
    unlocked: false,
    visible: true,
    x: 480,
    y: 460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "bar-chart-2",
    difficulty: "Expert",
    estimatedMinutes: 60,
    tags: ["factor", "latent", "dimensionality"],
    prerequisites: ["construct-validity"],
  },
  {
    id: "debriefing",
    title: "Debriefing",
    subtitle: "Post-Study Participant Care",
    description: "Conduct thorough debriefing sessions that explain the true purpose, address deception, and provide resources when research reveals unexpected findings.",
    branch: "Research Methods",
    level: 3,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "deception",
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -480,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "message-square",
    difficulty: "Advanced",
    estimatedMinutes: 30,
    tags: ["debriefing", "care", "explanation"],
    prerequisites: ["deception"],
  },
  {
    id: "multiple-regression",
    title: "Multiple Regression",
    subtitle: "Predicting with Multiple Predictors",
    description: "Build and interpret multiple regression models, understanding multicollinearity, hierarchical entry, and assumption checking.",
    branch: "Research Methods",
    level: 3,
    xp: 450,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "correlational-design",
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -460,
    radius: 26,
    color: "#DDD6FE",
    glow: false,
    iconName: "trending-up",
    difficulty: "Expert",
    estimatedMinutes: 55,
    tags: ["regression", "prediction", "multivariate"],
    prerequisites: ["correlational-design"],
  },
];
