// ============================================================
// SECTION: Type Definitions
// ============================================================

interface TreeNode {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  branch: string;
  level: number;
  xp: number;
  status: 'mastered' | 'available' | 'locked';
  progress: number;
  completed: number;
  total: number;
  parent: string | null;
  children: string[];
  unlocked: boolean;
  visible: boolean;
  x: number;
  y: number;
  radius: number;
  color: string;
  glow: string;
  iconName: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  estimatedMinutes: number;
  tags: string[];
  prerequisites: string[];
}

// ============================================================
// SECTION: Root Nodes
// ============================================================

export const rootNodes: TreeNode[] = [
  {
    id: 'psychology',
    title: 'Psychology',
    subtitle: 'The Scientific Study of Mind and Behavior',
    description: 'The foundational discipline encompassing the systematic investigation of mental processes, brain functions, human behavior, and the intricate interplay between biological, cognitive, emotional, and social factors that shape human experience.',
    branch: 'root',
    level: 0,
    xp: 0,
    status: 'mastered',
    progress: 100,
    completed: 1,
    total: 1,
    parent: null,
    children: ['cognitive', 'biological', 'social', 'personality', 'developmental', 'clinical', 'research', 'statistics'],
    unlocked: true,
    visible: true,
    x: 0,
    y: 0,
    radius: 48,
    color: '#8B5CF6',
    glow: 'rgba(139, 92, 246, 0.35)',
    iconName: 'brain',
    difficulty: 'beginner',
    estimatedMinutes: 0,
    tags: ['foundations', 'overview', 'discipline'],
    prerequisites: [],
  },
  {
    id: 'cognitive',
    title: 'Cognitive Psychology',
    subtitle: 'Mental Processes and Information Processing',
    description: 'The scientific study of internal mental processes including perception, attention, memory, language, problem-solving, reasoning, and decision-making. Examines how humans acquire, process, store, and retrieve information.',
    branch: 'cognitive',
    level: 1,
    xp: 60,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: [],
    unlocked: true,
    visible: true,
    x: -280,
    y: -200,
    radius: 36,
    color: '#3B82F6',
    glow: 'rgba(59, 130, 246, 0.30)',
    iconName: 'lightbulb',
    difficulty: 'beginner',
    estimatedMinutes: 45,
    tags: ['cognition', 'memory', 'perception', 'thinking'],
    prerequisites: ['psychology'],
  },
  {
    id: 'biological',
    title: 'Biological Psychology',
    subtitle: 'Neuroscience and the Biology of Behavior',
    description: 'The study of the biological bases of psychological processes and behavior. Explores neural structures, neurotransmission, brain anatomy, endocrine systems, genetics, and the physiological mechanisms underlying sensation, emotion, and cognition.',
    branch: 'biological',
    level: 1,
    xp: 65,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: [],
    unlocked: true,
    visible: true,
    x: 280,
    y: -200,
    radius: 36,
    color: '#10B981',
    glow: 'rgba(16, 185, 129, 0.30)',
    iconName: 'dna',
    difficulty: 'beginner',
    estimatedMinutes: 50,
    tags: ['neuroscience', 'brain', 'neurotransmitters', 'genetics'],
    prerequisites: ['psychology'],
  },
  {
    id: 'social',
    title: 'Social Psychology',
    subtitle: 'Interpersonal Dynamics and Group Behavior',
    description: 'The scientific study of how individuals think, feel, and behave in social contexts. Investigates attitudes, social cognition, conformity, obedience, group processes, interpersonal relationships, prejudice, aggression, and prosocial behavior.',
    branch: 'social',
    level: 1,
    xp: 55,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: [],
    unlocked: true,
    visible: true,
    x: 380,
    y: 0,
    radius: 36,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.30)',
    iconName: 'users',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['relationships', 'attitudes', 'groups', 'culture'],
    prerequisites: ['psychology'],
  },
  {
    id: 'personality',
    title: 'Personality Psychology',
    subtitle: 'Individual Differences and Trait Theory',
    description: 'The study of consistent patterns of thought, emotion, and behavior that distinguish individuals from one another. Examines major theoretical perspectives including trait theory, psychodynamic approaches, humanistic models, and the biological basis of temperament.',
    branch: 'personality',
    level: 1,
    xp: 50,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: [],
    unlocked: true,
    visible: true,
    x: 280,
    y: 200,
    radius: 36,
    color: '#EC4899',
    glow: 'rgba(236, 72, 153, 0.30)',
    iconName: 'fingerprint',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['traits', 'temperament', 'individual-differences', 'assessment'],
    prerequisites: ['psychology'],
  },
  {
    id: 'developmental',
    title: 'Developmental Psychology',
    subtitle: 'Lifespan Growth and Change',
    description: 'The scientific study of systematic psychological changes that occur throughout the human lifespan. Covers physical, cognitive, social, and emotional development from prenatal stages through infancy, childhood, adolescence, adulthood, and aging.',
    branch: 'developmental',
    level: 1,
    xp: 60,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: [],
    unlocked: true,
    visible: true,
    x: -280,
    y: 200,
    radius: 36,
    color: '#06B6D4',
    glow: 'rgba(6, 182, 212, 0.30)',
    iconName: 'baby',
    difficulty: 'beginner',
    estimatedMinutes: 45,
    tags: ['lifespan', 'child-development', 'aging', 'milestones'],
    prerequisites: ['psychology'],
  },
  {
    id: 'clinical',
    title: 'Clinical Psychology',
    subtitle: 'Mental Health, Disorders, and Treatment',
    description: 'The integration of science, theory, and clinical knowledge for the purpose of understanding, preventing, and relieving psychologically-based distress or dysfunction. Covers psychological assessment, diagnosis of mental disorders, and evidence-based therapeutic interventions.',
    branch: 'clinical',
    level: 1,
    xp: 70,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: [],
    unlocked: true,
    visible: true,
    x: -380,
    y: 0,
    radius: 36,
    color: '#EF4444',
    glow: 'rgba(239, 68, 68, 0.30)',
    iconName: 'heart-pulse',
    difficulty: 'beginner',
    estimatedMinutes: 50,
    tags: ['mental-health', 'disorders', 'therapy', 'assessment'],
    prerequisites: ['psychology'],
  },
  {
    id: 'research',
    title: 'Research Methods',
    subtitle: 'Scientific Inquiry in Psychology',
    description: 'The systematic study of how psychological knowledge is generated through empirical investigation. Covers experimental design, qualitative and quantitative methodologies, ethical considerations, validity, reliability, and the scientific method as applied to behavioral science.',
    branch: 'research',
    level: 1,
    xp: 45,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: [],
    unlocked: true,
    visible: true,
    x: 0,
    y: -320,
    radius: 36,
    color: '#6366F1',
    glow: 'rgba(99, 102, 241, 0.30)',
    iconName: 'microscope',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['methodology', 'experiments', 'ethics', 'design'],
    prerequisites: ['psychology'],
  },
  {
    id: 'statistics',
    title: 'Psychological Statistics',
    subtitle: 'Data Analysis and Quantitative Reasoning',
    description: 'The application of statistical methods to psychological data. Covers descriptive and inferential statistics, probability, hypothesis testing, correlation, regression, effect sizes, and the interpretation of quantitative findings in psychological research.',
    branch: 'statistics',
    level: 1,
    xp: 55,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: [],
    unlocked: true,
    visible: true,
    x: 0,
    y: 320,
    radius: 36,
    color: '#8B5CF6',
    glow: 'rgba(139, 92, 246, 0.30)',
    iconName: 'bar-chart-3',
    difficulty: 'beginner',
    estimatedMinutes: 45,
    tags: ['data', 'analysis', 'quantitative', 'inference'],
    prerequisites: ['psychology'],
  },
];
