// ============================================================
// SECTION: Type Definitions
// ============================================================

interface TreeNode {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  branch: string;
  level: number;
  xp: number;
  status: 'mastered' | 'available' | 'locked';
  progress: number;
  completed: number;
  total: number;
  parent: string | null;
  children: string[];
  unlocked: boolean;
  visible: boolean;
  x: number;
  y: number;
  radius: number;
  color: string;
  glow: string;
  iconName: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  estimatedMinutes: number;
  tags: string[];
  prerequisites: string[];
}

// ============================================================
// SECTION: Social Psychology Nodes
// ============================================================

export const socialNodes: TreeNode[] = [
  {
    id: 'social',
    title: 'Social Psychology',
    subtitle: 'Interpersonal Dynamics and Group Behavior',
    description: 'The scientific study of how individuals think, feel, and behave in social contexts. Investigates attitudes, social cognition, conformity, obedience, group processes, interpersonal relationships, prejudice, aggression, and prosocial behavior.',
    branch: 'social',
    level: 1,
    xp: 55,
    status: 'available',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'psychology',
    children: ['attitudes', 'attribution', 'conformity', 'obedience', 'persuasion', 'prejudice', 'aggression', 'prosocial-behaviour', 'group-dynamics', 'social-identity', 'relationships', 'social-cognition', 'social-influence'],
    unlocked: true,
    visible: true,
    x: 0,
    y: 0,
    radius: 44,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.35)',
    iconName: 'users',
    difficulty: 'beginner',
    estimatedMinutes: 0,
    tags: ['social', 'interpersonal', 'groups'],
    prerequisites: ['psychology'],
  },
  {
    id: 'attitudes',
    title: 'Attitudes',
    subtitle: 'Evaluative Dispositions Toward Objects and People',
    description: 'Relatively enduring evaluations of people, objects, and ideas that influence thought and behavior. Examined through the ABC model (affective, behavioral, cognitive) and theories of attitude formation and change.',
    branch: 'social',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['attitude-formation', 'attitude-change', 'abc-model', 'implicit-attitudes'],
    unlocked: false,
    visible: true,
    x: -400,
    y: -280,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'thumbs-up',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['evaluation', 'disposition', 'behavior'],
    prerequisites: ['social'],
  },
  {
    id: 'attitude-formation',
    title: 'Attitude Formation',
    subtitle: 'How Attitudes Develop',
    description: 'The processes through which attitudes are acquired, including direct experience, social learning, classical and operant conditioning, and genetic influences. Mere exposure and socialization play key roles.',
    branch: 'social',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'attitudes',
    children: [],
    unlocked: false,
    visible: true,
    x: -480,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'plus-circle',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['learning', 'experience', 'conditioning'],
    prerequisites: ['attitudes'],
  },
  {
    id: 'attitude-change',
    title: 'Attitude Change',
    subtitle: 'Shifting Evaluations Over Time',
    description: 'The processes by which existing attitudes are modified or replaced. Influenced by persuasive communication, cognitive dissonance, direct experience, and social influence. Central to advertising and behavior change interventions.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'attitudes',
    children: [],
    unlocked: false,
    visible: true,
    x: -400,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'refresh-cw',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['persuasion', 'dissonance', 'shift'],
    prerequisites: ['attitudes'],
  },
  {
    id: 'abc-model',
    title: 'ABC Model of Attitudes',
    subtitle: 'Affective, Behavioral, and Cognitive Components',
    description: 'A framework describing attitudes as comprising three components: affect (feelings), behavior (actions), and cognition (beliefs). The components may be consistent or inconsistent, with implications for attitude strength and prediction of behavior.',
    branch: 'social',
    level: 3,
    xp: 80,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'attitudes',
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'triangle',
    difficulty: 'beginner',
    estimatedMinutes: 20,
    tags: ['components', 'feelings', 'beliefs'],
    prerequisites: ['attitudes'],
  },
  {
    id: 'implicit-attitudes',
    title: 'Implicit Attitudes',
    subtitle: 'Unconscious Evaluative Associations',
    description: 'Attitudes that exist outside conscious awareness and control, measured by implicit association tests and other reaction-time measures. Can differ from explicit attitudes and predict spontaneous behavior independently.',
    branch: 'social',
    level: 3,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'attitudes',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'ghost',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['unconscious', 'iat', 'automatic'],
    prerequisites: ['attitudes'],
  },
  {
    id: 'attribution',
    title: 'Attribution',
    subtitle: 'Explaining the Causes of Behavior',
    description: 'The process by which individuals explain the causes of behavior and events. Central to social perception, with implications for relationships, motivation, mental health, and intergroup relations.',
    branch: 'social',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['internal-external-attribution', 'fundamental-attribution-error-social', 'actor-observer-bias', 'attributional-style'],
    unlocked: false,
    visible: true,
    x: -280,
    y: -280,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'search',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['causality', 'perception', 'explanation'],
    prerequisites: ['social'],
  },
  {
    id: 'internal-external-attribution',
    title: 'Internal vs External Attribution',
    subtitle: 'Dispositional vs Situational Causes',
    description: 'The distinction between attributing behavior to internal factors such as personality traits (dispositional) versus external factors such as the situation (situational). A core dimension of attribution theory developed by Heider and extended by Weiner.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'attribution',
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'scale',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['dispositional', 'situational', 'heider'],
    prerequisites: ['attribution'],
  },
  {
    id: 'fundamental-attribution-error-social',
    title: 'Fundamental Attribution Error',
    subtitle: 'Overestimating Dispositional Causes',
    description: 'The tendency to overestimate the influence of personality and underestimate the influence of situations when explaining others\' behavior. More pronounced in individualistic cultures and when judging strangers.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'attribution',
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'user-x',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['bias', 'disposition', 'situation'],
    prerequisites: ['attribution'],
  },
  {
    id: 'actor-observer-bias',
    title: 'Actor-Observer Bias',
    subtitle: 'Different Attributions for Self and Others',
    description: 'The tendency to attribute one\'s own actions to situational factors while attributing others\' actions to dispositional factors. Explained by differences in perceptual focus and information availability.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'attribution',
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'users',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['self', 'others', 'perspective'],
    prerequisites: ['attribution'],
  },
  {
    id: 'attributional-style',
    title: 'Attributional Style',
    subtitle: 'Habitual Patterns of Explanation',
    description: 'An individual\'s characteristic way of explaining events, particularly negative ones, along dimensions of internality, stability, and globality. Pessimistic styles predict depression and learned helplessness.',
    branch: 'social',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'attribution',
    children: [],
    unlocked: false,
    visible: true,
    x: -120,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'repeat',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['seligman', 'depression', 'habitual'],
    prerequisites: ['attribution'],
  },
  {
    id: 'conformity',
    title: 'Conformity',
    subtitle: 'Aligning Behavior with Group Norms',
    description: 'The tendency to adjust one\'s behavior or thinking to coincide with group standards. A fundamental social influence process examined through classic studies by Asch and others, revealing the power of social pressure.',
    branch: 'social',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['asch-conformity', 'normative-influence', 'informational-influence', 'minority-influence'],
    unlocked: false,
    visible: true,
    x: -160,
    y: -280,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'users-round',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['group', 'pressure', 'norms'],
    prerequisites: ['social'],
  },
  {
    id: 'asch-conformity',
    title: 'Asch Conformity Experiments',
    subtitle: 'Line Judgment and Social Pressure',
    description: 'Solomon Asch\'s classic 1950s experiments demonstrating that individuals would conform to obviously incorrect group judgments in about one-third of trials. Revealed the powerful influence of unanimous majority opinion.',
    branch: 'social',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'conformity',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'ruler',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['asch', 'lines', 'majority'],
    prerequisites: ['conformity'],
  },
  {
    id: 'normative-influence',
    title: 'Normative Social Influence',
    subtitle: 'Conforming to Be Liked and Accepted',
    description: 'Conformity driven by the desire to gain social approval and avoid rejection. Individuals conform publicly while privately maintaining their original beliefs. Stronger when the group is important and the individual feels scrutinized.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'conformity',
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'heart',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['approval', 'acceptance', 'public'],
    prerequisites: ['conformity'],
  },
  {
    id: 'informational-influence',
    title: 'Informational Social Influence',
    subtitle: 'Conforming to Be Correct',
    description: 'Conformity driven by the belief that others have accurate information, especially in ambiguous or crisis situations. Leads to private acceptance of the group norm as individuals genuinely believe the group is correct.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'conformity',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'help-circle',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['accuracy', 'ambiguity', 'private'],
    prerequisites: ['conformity'],
  },
  {
    id: 'minority-influence',
    title: 'Minority Influence',
    subtitle: 'Changing the Majority from Within',
    description: 'The process by which a small faction within a group influences the opinions or behavior of the majority. Requires consistency, confidence, and flexibility. Moscovici\'s research on blue-green slide judgments demonstrated its power.',
    branch: 'social',
    level: 3,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'conformity',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'megaphone',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['moscovici', 'consistency', 'change'],
    prerequisites: ['conformity'],
  },
  {
    id: 'obedience',
    title: 'Obedience',
    subtitle: 'Compliance with Authority',
    description: 'Compliance with orders from an authority figure. Distinguished from conformity by the presence of a direct command. One of the most studied and disturbing phenomena in social psychology.',
    branch: 'social',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['milgram-experiment', 'authority-figures', 'destructive-obedience', 'agentic-state'],
    unlocked: false,
    visible: true,
    x: -40,
    y: -280,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'shield',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['authority', 'commands', 'compliance'],
    prerequisites: ['social'],
  },
  {
    id: 'milgram-experiment',
    title: 'Milgram Obedience Experiments',
    subtitle: 'Shocking Revelations About Authority',
    description: 'Stanley Milgram\'s 1961-1963 experiments in which participants administered what they believed were dangerous electric shocks to a learner under an experimenter\'s orders. Approximately 65% delivered the maximum voltage.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'obedience',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'zap',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['milgram', 'shock', 'ethics'],
    prerequisites: ['obedience'],
  },
  {
    id: 'authority-figures',
    title: 'Authority Figures',
    subtitle: 'The Power of Legitimate Commands',
    description: 'Individuals perceived as having legitimate power or expertise whose directives are followed. Obedience increases with perceived legitimacy, proximity, and institutional support. Uniforms and titles enhance authority.',
    branch: 'social',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'obedience',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'crown',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['legitimacy', 'power', 'commands'],
    prerequisites: ['obedience'],
  },
  {
    id: 'destructive-obedience',
    title: 'Destructive Obedience',
    subtitle: 'Harmful Compliance with Orders',
    description: 'Obedience that leads to morally reprehensible acts, as seen in war crimes, corporate malfeasance, and organizational abuse. Understanding destructive obedience is essential for preventing atrocities and promoting ethical behavior.',
    branch: 'social',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'obedience',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'alert-triangle',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['harm', 'ethics', 'atrocities'],
    prerequisites: ['obedience'],
  },
  {
    id: 'agentic-state',
    title: 'Agentic State',
    subtitle: 'Acting as an Instrument of Authority',
    description: 'Milgram\'s concept describing a mental state in which individuals see themselves as agents carrying out another person\'s wishes rather than autonomous actors responsible for their own actions. Explains abdication of moral responsibility.',
    branch: 'social',
    level: 3,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'obedience',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'user-check',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['milgram', 'responsibility', 'autonomy'],
    prerequisites: ['obedience'],
  },
  {
    id: 'persuasion',
    title: 'Persuasion',
    subtitle: 'Changing Attitudes Through Communication',
    description: 'The process by which a message induces change in beliefs, attitudes, or behaviors. Central to advertising, politics, health promotion, and interpersonal influence. Examined through dual-process and message-based models.',
    branch: 'social',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['elaboration-likelihood-model', 'central-route', 'peripheral-route', 'source-credibility', 'foot-in-door', 'door-in-face'],
    unlocked: false,
    visible: true,
    x: 80,
    y: -280,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'megaphone',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['communication', 'influence', 'change'],
    prerequisites: ['social'],
  },
  {
    id: 'elaboration-likelihood-model',
    title: 'Elaboration Likelihood Model',
    subtitle: 'Dual Routes to Persuasion',
    description: 'Petty and Cacioppo\'s theory that persuasion occurs through two routes: central (thoughtful consideration of arguments) and peripheral (reliance on cues such as attractiveness or expertise). Motivation and ability determine the route.',
    branch: 'social',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'persuasion',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'git-branch',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['petty', 'cacioppo', 'elm'],
    prerequisites: ['persuasion'],
  },
  {
    id: 'central-route',
    title: 'Central Route to Persuasion',
    subtitle: 'Thoughtful Argument Processing',
    description: 'Persuasion through careful and thoughtful consideration of the true merits of the information presented. Produces durable attitude change that predicts behavior. Requires motivation and cognitive ability.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'persuasion',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'brain',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['arguments', 'durable', 'thoughtful'],
    prerequisites: ['persuasion'],
  },
  {
    id: 'peripheral-route',
    title: 'Peripheral Route to Persuasion',
    subtitle: 'Cue-Based Influence',
    description: 'Persuasion through superficial cues such as speaker attractiveness, celebrity endorsement, or message length rather than careful argument evaluation. Produces less durable attitude change but is effective when motivation is low.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'persuasion',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'sparkles',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['cues', 'superficial', 'heuristics'],
    prerequisites: ['persuasion'],
  },
  {
    id: 'source-credibility',
    title: 'Source Credibility',
    subtitle: 'Trustworthiness and Expertise',
    description: 'The perceived expertise and trustworthiness of a communicator, which enhances persuasion through the peripheral route. Credibility can be established through credentials, similarity to the audience, and perceived lack of bias.',
    branch: 'social',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'persuasion',
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'award',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['trust', 'expertise', 'speaker'],
    prerequisites: ['persuasion'],
  },
  {
    id: 'foot-in-door',
    title: 'Foot-in-the-Door Technique',
    subtitle: 'Small Request Leading to Larger Compliance',
    description: 'A compliance technique in which a small initial request is followed by a larger related request. The initial compliance creates a self-perception of helpfulness and consistency, increasing likelihood of agreeing to the larger request.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'persuasion',
    children: [],
    unlocked: false,
    visible: true,
    x: 320,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'door-open',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['compliance', 'consistency', 'sequence'],
    prerequisites: ['persuasion'],
  },
  {
    id: 'door-in-face',
    title: 'Door-in-the-Face Technique',
    subtitle: 'Large Request Followed by Compromise',
    description: 'A compliance technique in which a large, unreasonable request is followed by a smaller, more reasonable one. The contrast and perceived concession increase compliance with the second request through reciprocity norms.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'persuasion',
    children: [],
    unlocked: false,
    visible: true,
    x: 400,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'door-closed',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['reciprocity', 'contrast', 'concession'],
    prerequisites: ['persuasion'],
  },
  {
    id: 'prejudice',
    title: 'Prejudice',
    subtitle: 'Negative Attitudes Toward Groups',
    description: 'A preconceived negative attitude toward members of a group based on their group membership. Involves affective, cognitive, and behavioral components, and operates at both conscious and unconscious levels.',
    branch: 'social',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['stereotypes', 'discrimination', 'implicit-bias', 'contact-hypothesis', 'social-categorization'],
    unlocked: false,
    visible: true,
    x: 200,
    y: -280,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'alert-octagon',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['bias', 'groups', 'negative'],
    prerequisites: ['social'],
  },
  {
    id: 'stereotypes',
    title: 'Stereotypes',
    subtitle: 'Generalized Beliefs About Groups',
    description: 'Overgeneralized beliefs about the characteristics of members of a particular group. Can be positive or negative, accurate or inaccurate, and operate automatically. Serve cognitive efficiency but lead to biased judgments.',
    branch: 'social',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prejudice',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'tags',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['beliefs', 'generalization', 'groups'],
    prerequisites: ['prejudice'],
  },
  {
    id: 'discrimination',
    title: 'Discrimination',
    subtitle: 'Behavioral Expression of Prejudice',
    description: 'Unjustified negative behavior toward members of a group based on their group membership. The behavioral component of prejudice, distinct from stereotypes (cognitive) and prejudice (affective). Can be individual or institutional.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prejudice',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'ban',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['behavior', 'unjust', 'action'],
    prerequisites: ['prejudice'],
  },
  {
    id: 'implicit-bias',
    title: 'Implicit Bias',
    subtitle: 'Unconscious Negative Associations',
    description: 'Automatic, unconscious attitudes or stereotypes that affect understanding, actions, and decisions. Measured by implicit association tests and can operate independently of conscious beliefs and intentions.',
    branch: 'social',
    level: 3,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prejudice',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'eye-off',
    difficulty: 'advanced',
    estimatedMinutes: 35,
    tags: ['unconscious', 'automatic', 'iat'],
    prerequisites: ['prejudice'],
  },
  {
    id: 'contact-hypothesis',
    title: 'Contact Hypothesis',
    subtitle: 'Reducing Prejudice Through Interaction',
    description: 'Gordon Allport\'s theory that under optimal conditions, intergroup contact reduces prejudice. Optimal conditions include equal status, common goals, intergroup cooperation, and institutional support.',
    branch: 'social',
    level: 3,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prejudice',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'handshake',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['allport', 'contact', 'reduction'],
    prerequisites: ['prejudice'],
  },
  {
    id: 'social-categorization',
    title: 'Social Categorization',
    subtitle: 'Dividing the World into Groups',
    description: 'The cognitive process of classifying people into groups based on shared characteristics. A fundamental mechanism underlying stereotyping and prejudice, as it accentuates intergroup differences and intragroup similarities.',
    branch: 'social',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prejudice',
    children: [],
    unlocked: false,
    visible: true,
    x: 440,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'folder-tree',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['tajfel', 'groups', 'classification'],
    prerequisites: ['prejudice'],
  },
  {
    id: 'aggression',
    title: 'Aggression',
    subtitle: 'Behavior Intended to Cause Harm',
    description: 'Any physical or verbal behavior intended to hurt or destroy. Examined through biological, psychological, and social perspectives, with important implications for understanding violence, bullying, and conflict resolution.',
    branch: 'social',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['frustration-aggression', 'social-learning-aggression', 'deindividuation', 'weapons-effect'],
    unlocked: false,
    visible: true,
    x: 320,
    y: -280,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'sword',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['violence', 'harm', 'conflict'],
    prerequisites: ['social'],
  },
  {
    id: 'frustration-aggression',
    title: 'Frustration-Aggression Hypothesis',
    subtitle: 'Blocked Goals Lead to Hostility',
    description: 'The theory that frustration, defined as the blocking of goal-directed behavior, always leads to aggression, and aggression is always caused by frustration. Later revised to acknowledge that frustration increases the probability of aggression.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'aggression',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'ban',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['dollard', 'goals', 'blocking'],
    prerequisites: ['aggression'],
  },
  {
    id: 'social-learning-aggression',
    title: 'Social Learning of Aggression',
    subtitle: 'Modeling and Imitation of Violence',
    description: 'Bandura\'s theory that aggression is learned through observation, imitation, and reinforcement. The Bobo doll experiments demonstrated that children imitate aggressive models, especially when the aggression is rewarded.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'aggression',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'tv',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['bandura', 'modeling', 'bobo'],
    prerequisites: ['aggression'],
  },
  {
    id: 'deindividuation',
    title: 'Deindividuation',
    subtitle: 'Loss of Self-Awareness in Groups',
    description: 'A state in which individuals in groups lose their sense of personal identity and self-awareness, leading to disinhibited behavior. Explains mob violence, hooliganism, and online trolling. Increased by anonymity and arousal.',
    branch: 'social',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'aggression',
    children: [],
    unlocked: false,
    visible: true,
    x: 440,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'users-x',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['anonymity', 'mob', 'disinhibition'],
    prerequisites: ['aggression'],
  },
  {
    id: 'weapons-effect',
    title: 'Weapons Effect',
    subtitle: 'Presence of Weapons Increases Aggression',
    description: 'The phenomenon whereby the mere presence of weapons increases aggressive thoughts and behaviors. First demonstrated by Berkowitz and LePage, it has implications for gun control and environmental design.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'aggression',
    children: [],
    unlocked: false,
    visible: true,
    x: 520,
    y: -400,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'crosshair',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['berkowitz', 'guns', 'priming'],
    prerequisites: ['aggression'],
  },
  {
    id: 'prosocial-behaviour',
    title: 'Prosocial Behaviour',
    subtitle: 'Actions That Benefit Others',
    description: 'Voluntary behavior intended to benefit another person or society as a whole. Includes helping, sharing, donating, cooperating, and comforting. The positive counterpart to aggression in social psychology.',
    branch: 'social',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['helping-behaviour', 'altruism', 'empathy', 'reciprocity-norm', 'social-responsibility-norm'],
    unlocked: false,
    visible: true,
    x: -400,
    y: 0,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'heart-handshake',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['helping', 'cooperation', 'benefit'],
    prerequisites: ['social'],
  },
  {
    id: 'helping-behaviour',
    title: 'Helping Behaviour',
    subtitle: 'Assisting Others in Need',
    description: 'Any act that is intended to benefit another person, ranging from small favors to life-saving interventions. Examined through models of bystander intervention, cost-reward analysis, and empathy-altruism hypotheses.',
    branch: 'social',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prosocial-behaviour',
    children: [],
    unlocked: false,
    visible: true,
    x: -480,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'hand-helping',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['assistance', 'need', 'intervention'],
    prerequisites: ['prosocial-behaviour'],
  },
  {
    id: 'altruism',
    title: 'Altruism',
    subtitle: 'Selfless Concern for Others',
    description: 'Behavior motivated by the desire to help another person without expectation of personal benefit. Debated whether true altruism exists or whether all helping is ultimately egoistic. Central to evolutionary and moral psychology.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prosocial-behaviour',
    children: [],
    unlocked: false,
    visible: true,
    x: -400,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'gift',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['selfless', 'benefit', 'egoism'],
    prerequisites: ['prosocial-behaviour'],
  },
  {
    id: 'empathy',
    title: 'Empathy',
    subtitle: 'Understanding and Sharing Others\' Feelings',
    description: 'The ability to understand and share the feelings of another person. Involves both cognitive empathy (perspective-taking) and affective empathy (emotional resonance). A key motivator of prosocial behavior and moral development.',
    branch: 'social',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prosocial-behaviour',
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'heart',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['perspective', 'emotion', 'compassion'],
    prerequisites: ['prosocial-behaviour'],
  },
  {
    id: 'reciprocity-norm',
    title: 'Reciprocity Norm',
    subtitle: 'Returning Favors and Cooperation',
    description: 'The social expectation that people will respond to each other in kind, returning benefits for benefits and responding to harm with harm. A universal moral rule that underlies cooperation and trust in social relationships.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prosocial-behaviour',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'repeat',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['favors', 'cooperation', 'exchange'],
    prerequisites: ['prosocial-behaviour'],
  },
  {
    id: 'social-responsibility-norm',
    title: 'Social Responsibility Norm',
    subtitle: 'Obligation to Help Those in Need',
    description: 'The expectation that individuals should help others who are dependent and in dire need of assistance, regardless of the potential costs. Stronger when the victim is perceived as unable to help themselves.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'prosocial-behaviour',
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'shield-check',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['obligation', 'need', 'duty'],
    prerequisites: ['prosocial-behaviour'],
  },
  {
    id: 'group-dynamics',
    title: 'Group Dynamics',
    subtitle: 'Processes Within and Between Groups',
    description: 'The interactions, attitudes, and behaviors that occur within and between groups. Encompasses group formation, cohesion, decision-making, leadership, and intergroup relations. Central to organizational and political psychology.',
    branch: 'social',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['leadership', 'groupthink', 'social-facilitation', 'social-loafing', 'deindividuation-group'],
    unlocked: false,
    visible: true,
    x: -280,
    y: 0,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'users',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['groups', 'interaction', 'cohesion'],
    prerequisites: ['social'],
  },
  {
    id: 'leadership',
    title: 'Leadership',
    subtitle: 'Influencing and Guiding Groups',
    description: 'The ability to influence, guide, and direct a group toward the achievement of goals. Examined through trait, behavioral, contingency, and transformational theories, with applications to organizations and politics.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'group-dynamics',
    children: ['transformational-leadership', 'transactional-leadership', 'situational-leadership'],
    unlocked: false,
    visible: true,
    x: -360,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'crown',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['influence', 'guidance', 'power'],
    prerequisites: ['group-dynamics'],
  },
  {
    id: 'transformational-leadership',
    title: 'Transformational Leadership',
    subtitle: 'Inspiring and Empowering Followers',
    description: 'A leadership style in which leaders inspire followers to transcend self-interest for the good of the group. Characterized by idealized influence, inspirational motivation, intellectual stimulation, and individualized consideration.',
    branch: 'social',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'leadership',
    children: [],
    unlocked: false,
    visible: true,
    x: -400,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'sparkles',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['inspiration', 'vision', 'bass'],
    prerequisites: ['leadership'],
  },
  {
    id: 'transactional-leadership',
    title: 'Transactional Leadership',
    subtitle: 'Exchange-Based Management',
    description: 'A leadership style focused on clarifying roles and task requirements and providing rewards or punishments contingent on performance. Effective for maintaining stability and achieving short-term goals.',
    branch: 'social',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'leadership',
    children: [],
    unlocked: false,
    visible: true,
    x: -320,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'exchange',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['rewards', 'punishment', 'exchange'],
    prerequisites: ['leadership'],
  },
  {
    id: 'situational-leadership',
    title: 'Situational Leadership',
    subtitle: 'Adapting Style to Context',
    description: 'The theory that effective leadership depends on matching the leader\'s style to the readiness and capabilities of followers and the demands of the situation. No single best leadership style exists.',
    branch: 'social',
    level: 4,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'leadership',
    children: [],
    unlocked: false,
    visible: true,
    x: -240,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'settings',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['adaptation', 'context', 'followers'],
    prerequisites: ['leadership'],
  },
  {
    id: 'groupthink',
    title: 'Groupthink',
    subtitle: 'Dysfunctional Desire for Consensus',
    description: 'A mode of thinking that occurs when the desire for harmony in a decision-making group overrides realistic appraisal of alternatives. Leads to poor decisions, as seen in the Bay of Pigs invasion and Challenger disaster.',
    branch: 'social',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'group-dynamics',
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'users-round',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['janis', 'consensus', 'decisions'],
    prerequisites: ['group-dynamics'],
  },
  {
    id: 'social-facilitation',
    title: 'Social Facilitation',
    subtitle: 'Performance Changes in Presence of Others',
    description: 'The tendency for people to perform differently when in the presence of others compared to when alone. Simple or well-learned tasks are performed better, while complex or novel tasks are performed worse due to arousal.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'group-dynamics',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'trending-up',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['audience', 'arousal', 'performance'],
    prerequisites: ['group-dynamics'],
  },
  {
    id: 'social-loafing',
    title: 'Social Loafing',
    subtitle: 'Reduced Effort in Groups',
    description: 'The tendency for individuals to exert less effort when working collectively in a group compared to when working individually. Explained by diffusion of responsibility, reduced evaluation apprehension, and perceived dispensability.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'group-dynamics',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'trending-down',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['effort', 'diffusion', 'groups'],
    prerequisites: ['group-dynamics'],
  },
  {
    id: 'deindividuation-group',
    title: 'Deindividuation in Groups',
    subtitle: 'Loss of Individual Identity',
    description: 'The loss of self-awareness and individual accountability that occurs in groups, leading to behavior that deviates from personal standards. Facilitated by anonymity, group size, and arousal. Explains mob behavior and rioting.',
    branch: 'social',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'group-dynamics',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'user-x',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['anonymity', 'mob', 'accountability'],
    prerequisites: ['group-dynamics'],
  },
  {
    id: 'social-identity',
    title: 'Social Identity',
    subtitle: 'Self-Concept Derived from Group Membership',
    description: 'The portion of an individual\'s self-concept derived from perceived membership in a relevant social group. Proposed by Tajfel and Turner as central to understanding intergroup behavior, self-esteem, and group cohesion.',
    branch: 'social',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['social-identity-theory', 'in-group-bias', 'out-group-homogeneity', 'self-categorization'],
    unlocked: false,
    visible: true,
    x: -160,
    y: 0,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'id-card',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['tajfel', 'turner', 'groups'],
    prerequisites: ['social'],
  },
  {
    id: 'social-identity-theory',
    title: 'Social Identity Theory',
    subtitle: 'Groups Shape Self-Concept',
    description: 'Tajfel and Turner\'s theory that individuals derive self-esteem from group membership and strive to maintain positive social identity through intergroup comparisons. Explains in-group favoritism and out-group discrimination.',
    branch: 'social',
    level: 3,
    xp: 150,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-identity',
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'users',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['tajfel', 'turner', 'self-esteem'],
    prerequisites: ['social-identity'],
  },
  {
    id: 'in-group-bias',
    title: 'In-Group Bias',
    subtitle: 'Favoring One\'s Own Group',
    description: 'The tendency to favor members of one\'s own group over those in other groups. Occurs even with minimal group distinctions and is driven by the need for positive social identity and self-esteem.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-identity',
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'star',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['favoritism', 'own-group', 'bias'],
    prerequisites: ['social-identity'],
  },
  {
    id: 'out-group-homogeneity',
    title: 'Out-Group Homogeneity',
    subtitle: 'Seeing Other Groups as Alike',
    description: 'The tendency to perceive members of out-groups as more similar to each other than members of one\'s own in-group. Contributes to stereotyping and reduces recognition of individual differences in other groups.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-identity',
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'copy',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['similarity', 'stereotyping', 'perception'],
    prerequisites: ['social-identity'],
  },
  {
    id: 'self-categorization',
    title: 'Self-Categorization Theory',
    subtitle: 'Defining Self Through Group Membership',
    description: 'Turner\'s extension of social identity theory proposing that self-concept shifts between personal identity (unique individual) and social identity (group member). The salience of a category determines which self is activated.',
    branch: 'social',
    level: 3,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-identity',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'folder-tree',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    tags: ['turner', 'salience', 'activation'],
    prerequisites: ['social-identity'],
  },
  {
    id: 'relationships',
    title: 'Relationships',
    subtitle: 'Interpersonal Connections and Bonds',
    description: 'The study of how people form, maintain, and dissolve close relationships. Examines attraction, love, attachment, communication, conflict, and relationship satisfaction across romantic, familial, and friendship contexts.',
    branch: 'social',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['interpersonal-attraction', 'attachment-theory', 'love-types', 'relationship-satisfaction'],
    unlocked: false,
    visible: true,
    x: -40,
    y: 0,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'heart',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['love', 'attraction', 'bonds'],
    prerequisites: ['social'],
  },
  {
    id: 'interpersonal-attraction',
    title: 'Interpersonal Attraction',
    subtitle: 'Factors That Draw People Together',
    description: 'The factors that lead people to form relationships, including physical proximity, similarity, reciprocity, and physical attractiveness. The mere exposure effect and matching hypothesis are key principles.',
    branch: 'social',
    level: 3,
    xp: 90,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'relationships',
    children: [],
    unlocked: false,
    visible: true,
    x: -40,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'magnet',
    difficulty: 'beginner',
    estimatedMinutes: 25,
    tags: ['proximity', 'similarity', 'attractiveness'],
    prerequisites: ['relationships'],
  },
  {
    id: 'attachment-theory',
    title: 'Attachment Theory',
    subtitle: 'Early Bonds Shape Adult Relationships',
    description: 'Bowlby and Ainsworth\'s theory that early caregiver relationships create internal working models that shape adult romantic relationships. Styles include secure, anxious, and avoidant attachment.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'relationships',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'baby',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['bowlby', 'ainsworth', 'styles'],
    prerequisites: ['relationships'],
  },
  {
    id: 'love-types',
    title: 'Types of Love',
    subtitle: 'Classifying Romantic Affection',
    description: 'Theories classifying different types of love, including Sternberg\'s triangular theory (intimacy, passion, commitment) and Lee\'s love styles. Distinguishes romantic, companionate, consummate, and other forms of love.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'relationships',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'heart-pulse',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['sternberg', 'passion', 'commitment'],
    prerequisites: ['relationships'],
  },
  {
    id: 'relationship-satisfaction',
    title: 'Relationship Satisfaction',
    subtitle: 'What Makes Relationships Thrive',
    description: 'The factors that contribute to happy, stable relationships, including equity, communication, commitment, and positive illusions. Examined through investment model, interdependence theory, and behavioral approaches.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'relationships',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'smile',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['equity', 'communication', 'stability'],
    prerequisites: ['relationships'],
  },
  {
    id: 'social-cognition',
    title: 'Social Cognition',
    subtitle: 'How People Think About Social Worlds',
    description: 'The study of how people process, store, and apply information about other people and social situations. Bridges cognitive and social psychology, examining schemas, heuristics, and biases in social judgment.',
    branch: 'social',
    level: 2,
    xp: 70,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['person-perception', 'social-schemas', 'attribution-heuristics', 'self-fulfilling-prophecy'],
    unlocked: false,
    visible: true,
    x: 80,
    y: 0,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'brain',
    difficulty: 'beginner',
    estimatedMinutes: 40,
    tags: ['thinking', 'judgment', 'schemas'],
    prerequisites: ['social'],
  },
  {
    id: 'person-perception',
    title: 'Person Perception',
    subtitle: 'Forming Impressions of Others',
    description: 'The process of forming impressions of other people based on available information. Involves rapid, automatic judgments influenced by physical appearance, behavior, and context, subject to primacy effects and halo effects.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-cognition',
    children: [],
    unlocked: false,
    visible: true,
    x: 40,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'user-search',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['impressions', 'appearance', 'judgment'],
    prerequisites: ['social-cognition'],
  },
  {
    id: 'social-schemas',
    title: 'Social Schemas',
    subtitle: 'Mental Frameworks for Social Information',
    description: 'Cognitive structures that organize knowledge about social concepts, people, groups, and events. Include person schemas, role schemas, event schemas (scripts), and self-schemas that guide social information processing.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-cognition',
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'layout-template',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['frameworks', 'organization', 'knowledge'],
    prerequisites: ['social-cognition'],
  },
  {
    id: 'attribution-heuristics',
    title: 'Attribution Heuristics',
    subtitle: 'Shortcuts in Social Explanation',
    description: 'Cognitive shortcuts used when explaining the causes of social behavior, including the fundamental attribution error, actor-observer bias, and self-serving bias. Systematic patterns that reveal the architecture of social inference.',
    branch: 'social',
    level: 3,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-cognition',
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'zap',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['shortcuts', 'bias', 'inference'],
    prerequisites: ['social-cognition'],
  },
  {
    id: 'self-fulfilling-prophecy',
    title: 'Self-Fulfilling Prophecy',
    subtitle: 'Expectations Create Reality',
    description: 'A prediction that directly or indirectly causes itself to become true through feedback between belief and behavior. Demonstrated in educational settings (Rosenthal effect) and intergroup contexts, with powerful social consequences.',
    branch: 'social',
    level: 3,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-cognition',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'refresh-cw',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    tags: ['expectations', 'rosenthal', 'feedback'],
    prerequisites: ['social-cognition'],
  },
  {
    id: 'social-influence',
    title: 'Social Influence',
    subtitle: 'How Others Shape Our Behavior',
    description: 'The ways in which individuals change their behavior to meet the demands of a social environment. Encompasses conformity, compliance, obedience, and persuasion as mechanisms through which society shapes individual action.',
    branch: 'social',
    level: 2,
    xp: 60,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social',
    children: ['bystander-effect', 'cognitive-dissonance', 'compliance', 'reciprocity'],
    unlocked: false,
    visible: true,
    x: 160,
    y: 0,
    radius: 34,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.25)',
    iconName: 'users-round',
    difficulty: 'beginner',
    estimatedMinutes: 35,
    tags: ['influence', 'pressure', 'change'],
    prerequisites: ['social'],
  },
  {
    id: 'bystander-effect',
    title: 'Bystander Effect',
    subtitle: 'More Witnesses, Less Help',
    description: 'The phenomenon whereby individuals are less likely to offer help to a victim when other people are present. The greater the number of bystanders, the less likely any one of them is to help. Explained by diffusion of responsibility and pluralistic ignorance.',
    branch: 'social',
    level: 3,
    xp: 110,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-influence',
    children: ['diffusion-of-responsibility', 'pluralistic-ignorance', 'kitty-genovese'],
    unlocked: false,
    visible: true,
    x: 120,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'eye-off',
    difficulty: 'intermediate',
    estimatedMinutes: 30,
    tags: ['helping', 'witnesses', 'diffusion'],
    prerequisites: ['social-influence'],
  },
  {
    id: 'diffusion-of-responsibility',
    title: 'Diffusion of Responsibility',
    subtitle: 'Shared Blame Reduces Individual Action',
    description: 'A social phenomenon in which the presence of others leads individuals to feel less personal responsibility for taking action. Each bystander assumes someone else will intervene, resulting in collective inaction.',
    branch: 'social',
    level: 4,
    xp: 130,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'bystander-effect',
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'users-x',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['shared', 'blame', 'inaction'],
    prerequisites: ['bystander-effect'],
  },
  {
    id: 'pluralistic-ignorance',
    title: 'Pluralistic Ignorance',
    subtitle: 'Misreading Group Consensus',
    description: 'A situation in which a majority of group members privately reject a norm but incorrectly assume that most others accept it. Leads to public conformity with norms that most people privately oppose, contributing to bystander inaction.',
    branch: 'social',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'bystander-effect',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'eye',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['norms', 'misreading', 'conformity'],
    prerequisites: ['bystander-effect'],
  },
  {
    id: 'kitty-genovese',
    title: 'Kitty Genovese Case',
    subtitle: 'The Murder That Sparked Bystander Research',
    description: 'The 1964 murder of Kitty Genovese in New York City, initially reported as witnessed by 38 neighbors who failed to intervene. While details were later disputed, the case catalyzed research into bystander intervention and diffusion of responsibility.',
    branch: 'social',
    level: 4,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'bystander-effect',
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'alert-circle',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['history', 'case', 'intervention'],
    prerequisites: ['bystander-effect'],
  },
  {
    id: 'cognitive-dissonance',
    title: 'Cognitive Dissonance',
    subtitle: 'Tension from Inconsistent Cognitions',
    description: 'Festinger\'s theory that psychological discomfort arises from holding two or more inconsistent cognitions, leading individuals to change attitudes, beliefs, or behaviors to reduce the inconsistency. A powerful driver of attitude change.',
    branch: 'social',
    level: 3,
    xp: 120,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-influence',
    children: ['effort-justification', 'induced-compliance', 'post-decision-dissonance'],
    unlocked: false,
    visible: true,
    x: 200,
    y: -120,
    radius: 28,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'brain-circuit',
    difficulty: 'intermediate',
    estimatedMinutes: 35,
    tags: ['festinger', 'inconsistency', 'tension'],
    prerequisites: ['social-influence'],
  },
  {
    id: 'effort-justification',
    title: 'Effort Justification',
    subtitle: 'Valuing What Costs More',
    description: 'The tendency to increase the subjective value of outcomes that required high effort to achieve. A form of cognitive dissonance reduction where individuals justify their investment by inflating the value of the goal.',
    branch: 'social',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'cognitive-dissonance',
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'trending-up',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['investment', 'value', 'justification'],
    prerequisites: ['cognitive-dissonance'],
  },
  {
    id: 'induced-compliance',
    title: 'Induced Compliance',
    subtitle: 'Changing Attitudes Through Counterattitudinal Action',
    description: 'A paradigm in which individuals are induced to behave in ways inconsistent with their attitudes, leading to attitude change to reduce dissonance. The less external justification for the behavior, the greater the attitude change.',
    branch: 'social',
    level: 4,
    xp: 160,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'cognitive-dissonance',
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'arrow-right-left',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    tags: ['behavior', 'justification', 'change'],
    prerequisites: ['cognitive-dissonance'],
  },
  {
    id: 'post-decision-dissonance',
    title: 'Post-Decision Dissonance',
    subtitle: 'Reassuring Choices After the Fact',
    description: 'The dissonance experienced after making a difficult decision, leading individuals to enhance the attractiveness of the chosen alternative and devalue the rejected alternative. Explains buyer\'s remorse and confirmation bias.',
    branch: 'social',
    level: 4,
    xp: 140,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'cognitive-dissonance',
    children: [],
    unlocked: false,
    visible: true,
    x: 320,
    y: -200,
    radius: 20,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.15)',
    iconName: 'check-circle',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['decision', 'reassurance', 'choice'],
    prerequisites: ['cognitive-dissonance'],
  },
  {
    id: 'compliance',
    title: 'Compliance',
    subtitle: 'Yielding to Explicit Requests',
    description: 'Behavior change in response to a direct request from another person, without necessarily changing private attitudes. Distinguished from conformity (no request) and obedience (authority command).',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-influence',
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'hand',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['requests', 'yielding', 'techniques'],
    prerequisites: ['social-influence'],
  },
  {
    id: 'reciprocity',
    title: 'Reciprocity Principle',
    subtitle: 'Obligation to Return Favors',
    description: 'A powerful social norm creating a sense of obligation to repay what another person has provided. Explains why free samples, small gifts, and concessions are effective compliance techniques across cultures.',
    branch: 'social',
    level: 3,
    xp: 100,
    status: 'locked',
    progress: 0,
    completed: 0,
    total: 1,
    parent: 'social-influence',
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: -120,
    radius: 26,
    color: '#F59E0B',
    glow: 'rgba(245, 158, 11, 0.20)',
    iconName: 'repeat-2',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    tags: ['obligation', 'favors', 'compliance'],
    prerequisites: ['social-influence'],
  },
];
