export interface TreeNode {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  branch: string;
  level: number;
  xp: number;
  status: "mastered" | "available" | "locked";
  progress: number;
  completed: number;
  total: number;
  parent: string | null;
  children: string[];
  unlocked: boolean;
  visible: boolean;
  x: number;
  y: number;
  radius: number;
  color: string;
  glow: boolean;
  iconName: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced" | "Expert";
  estimatedMinutes: number;
  tags: string[];
  prerequisites: string[];
}

export const statisticsNodes: TreeNode[] = [
  {
    id: "psychology-statistics",
    title: "Psychology Statistics",
    subtitle: "Quantitative Methods for Behavioral Science",
    description: "Master the statistical tools and inferential methods that enable psychologists to analyze data, test hypotheses, and draw evidence-based conclusions about human behavior and mental processes.",
    branch: "Statistics",
    level: 0,
    xp: 0,
    status: "mastered",
    progress: 100,
    completed: 5,
    total: 5,
    parent: null,
    children: ["descriptive-statistics", "probability", "inferential-statistics", "correlation", "regression", "reliability-statistics", "validity-statistics"],
    unlocked: true,
    visible: true,
    x: 0,
    y: 0,
    radius: 48,
    color: "#10B981",
    glow: true,
    iconName: "bar-chart-2",
    difficulty: "Beginner",
    estimatedMinutes: 0,
    tags: ["statistics", "quantitative", "behavioral-science"],
    prerequisites: [],
  },
  {
    id: "descriptive-statistics",
    title: "Descriptive Statistics",
    subtitle: "Summarizing and Organizing Data",
    description: "Learn to summarize, organize, and present data through measures of central tendency, variability, and graphical representations that reveal patterns in psychological research.",
    branch: "Statistics",
    level: 1,
    xp: 60,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "psychology-statistics",
    children: ["central-tendency", "variability", "normal-distribution", "data-visualization"],
    unlocked: true,
    visible: true,
    x: -240,
    y: 140,
    radius: 36,
    color: "#34D399",
    glow: false,
    iconName: "pie-chart",
    difficulty: "Beginner",
    estimatedMinutes: 25,
    tags: ["descriptive", "summary", "data"],
    prerequisites: ["psychology-statistics"],
  },
  {
    id: "probability",
    title: "Probability",
    subtitle: "Foundations of Statistical Inference",
    description: "Understand probability theory, random variables, distributions, and the laws that underpin all statistical decision-making in psychological research.",
    branch: "Statistics",
    level: 1,
    xp: 55,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "psychology-statistics",
    children: ["probability-rules", "sampling-distributions", "binomial-distribution"],
    unlocked: true,
    visible: true,
    x: -80,
    y: 160,
    radius: 36,
    color: "#34D399",
    glow: false,
    iconName: "dice",
    difficulty: "Beginner",
    estimatedMinutes: 22,
    tags: ["probability", "randomness", "foundation"],
    prerequisites: ["psychology-statistics"],
  },
  {
    id: "inferential-statistics",
    title: "Inferential Statistics",
    subtitle: "Drawing Conclusions from Samples",
    description: "Master the logic of generalizing from sample statistics to population parameters, including hypothesis testing frameworks and error control.",
    branch: "Statistics",
    level: 1,
    xp: 70,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "psychology-statistics",
    children: ["hypothesis-testing", "confidence-interval", "effect-size", "statistical-power"],
    unlocked: true,
    visible: true,
    x: 80,
    y: 170,
    radius: 36,
    color: "#34D399",
    glow: false,
    iconName: "git-branch",
    difficulty: "Beginner",
    estimatedMinutes: 30,
    tags: ["inferential", "generalization", "testing"],
    prerequisites: ["psychology-statistics"],
  },
  {
    id: "correlation",
    title: "Correlation",
    subtitle: "Measuring Relationships Between Variables",
    description: "Explore Pearson, Spearman, and point-biserial correlation coefficients to quantify the strength and direction of linear relationships in psychological data.",
    branch: "Statistics",
    level: 1,
    xp: 65,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "psychology-statistics",
    children: ["pearson-correlation", "spearman-correlation", "partial-correlation"],
    unlocked: true,
    visible: true,
    x: 220,
    y: 160,
    radius: 36,
    color: "#34D399",
    glow: false,
    iconName: "trending-up",
    difficulty: "Beginner",
    estimatedMinutes: 28,
    tags: ["correlation", "relationship", "association"],
    prerequisites: ["psychology-statistics"],
  },
  {
    id: "regression",
    title: "Regression",
    subtitle: "Predicting Outcomes from Predictors",
    description: "Build and interpret linear and multiple regression models to predict psychological outcomes and understand predictor contributions.",
    branch: "Statistics",
    level: 1,
    xp: 75,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "psychology-statistics",
    children: ["simple-regression", "multiple-regression", "logistic-regression"],
    unlocked: true,
    visible: true,
    x: 360,
    y: 140,
    radius: 36,
    color: "#34D399",
    glow: false,
    iconName: "activity",
    difficulty: "Beginner",
    estimatedMinutes: 32,
    tags: ["regression", "prediction", "modeling"],
    prerequisites: ["psychology-statistics"],
  },
  {
    id: "reliability-statistics",
    title: "Reliability Statistics",
    subtitle: "Quantifying Measurement Consistency",
    description: "Calculate and interpret statistical indices of measurement reliability including Cronbach's alpha, test-retest correlations, and inter-rater agreement.",
    branch: "Statistics",
    level: 1,
    xp: 80,
    status: "available",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "psychology-statistics",
    children: ["cronbach-alpha", "test-retest-correlation", "split-half-reliability"],
    unlocked: true,
    visible: true,
    x: -360,
    y: 140,
    radius: 36,
    color: "#34D399",
    glow: false,
    iconName: "refresh-cw",
    difficulty: "Beginner",
    estimatedMinutes: 30,
    tags: ["reliability", "consistency", "measurement"],
    prerequisites: ["psychology-statistics"],
  },
  {
    id: "validity-statistics",
    title: "Validity Statistics",
    subtitle: "Quantifying Measurement Accuracy",
    description: "Evaluate construct, criterion, and content validity using factor analysis, ROC curves, and sensitivity-specificity statistics in psychological assessment.",
    branch: "Statistics",
    level: 1,
    xp: 85,
    status: "available",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "psychology-statistics",
    children: ["factor-analysis", "roc-analysis", "sensitivity-specificity"],
    unlocked: true,
    visible: true,
    x: 480,
    y: 140,
    radius: 36,
    color: "#34D399",
    glow: false,
    iconName: "check-square",
    difficulty: "Beginner",
    estimatedMinutes: 35,
    tags: ["validity", "accuracy", "assessment"],
    prerequisites: ["psychology-statistics"],
  },
  {
    id: "central-tendency",
    title: "Central Tendency",
    subtitle: "Mean, Median, and Mode",
    description: "Calculate and appropriately select measures of central tendency while understanding how distribution shape and outliers influence each measure.",
    branch: "Statistics",
    level: 2,
    xp: 100,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "descriptive-statistics",
    children: ["mean", "median", "mode"],
    unlocked: false,
    visible: true,
    x: -340,
    y: 300,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "align-center",
    difficulty: "Intermediate",
    estimatedMinutes: 25,
    tags: ["central-tendency", "average", "center"],
    prerequisites: ["descriptive-statistics"],
  },
  {
    id: "variability",
    title: "Variability",
    subtitle: "Spread and Dispersion Measures",
    description: "Quantify data spread using range, interquartile range, variance, and standard deviation to understand the distribution of psychological measurements.",
    branch: "Statistics",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "descriptive-statistics",
    children: ["range", "variance", "standard-deviation"],
    unlocked: false,
    visible: true,
    x: -220,
    y: 320,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "arrow-left-right",
    difficulty: "Intermediate",
    estimatedMinutes: 28,
    tags: ["variability", "spread", "dispersion"],
    prerequisites: ["descriptive-statistics"],
  },
  {
    id: "normal-distribution",
    title: "Normal Distribution",
    subtitle: "The Bell Curve in Psychology",
    description: "Understand the properties, parameters, and applications of the Gaussian distribution as the foundation for parametric statistical inference.",
    branch: "Statistics",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "descriptive-statistics",
    children: ["z-scores", "percentiles", "skewness-kurtosis"],
    unlocked: false,
    visible: true,
    x: -100,
    y: 300,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "bell",
    difficulty: "Intermediate",
    estimatedMinutes: 32,
    tags: ["normal", "gaussian", "bell-curve"],
    prerequisites: ["descriptive-statistics"],
  },
  {
    id: "data-visualization",
    title: "Data Visualization",
    subtitle: "Graphical Representation of Data",
    description: "Create and interpret histograms, box plots, scatter plots, and Q-Q plots to visually communicate statistical findings in psychological research.",
    branch: "Statistics",
    level: 2,
    xp: 105,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "descriptive-statistics",
    children: [],
    unlocked: false,
    visible: true,
    x: -20,
    y: 320,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "bar-chart",
    difficulty: "Intermediate",
    estimatedMinutes: 26,
    tags: ["visualization", "graphs", "plots"],
    prerequisites: ["descriptive-statistics"],
  },
  {
    id: "probability-rules",
    title: "Probability Rules",
    subtitle: "Addition, Multiplication, and Bayes",
    description: "Apply the addition rule, multiplication rule, conditional probability, and Bayes' theorem to calculate probabilities in psychological contexts.",
    branch: "Statistics",
    level: 2,
    xp: 115,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "probability",
    children: ["bayes-theorem", "conditional-probability"],
    unlocked: false,
    visible: true,
    x: -160,
    y: 320,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "calculator",
    difficulty: "Intermediate",
    estimatedMinutes: 30,
    tags: ["rules", "bayes", "conditional"],
    prerequisites: ["probability"],
  },
  {
    id: "sampling-distributions",
    title: "Sampling Distributions",
    subtitle: "Distribution of Sample Statistics",
    description: "Understand the central limit theorem and how sample means, proportions, and variances form distributions that enable statistical inference.",
    branch: "Statistics",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "probability",
    children: ["central-limit-theorem", "standard-error"],
    unlocked: false,
    visible: true,
    x: -60,
    y: 330,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "layers",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["sampling", "distribution", "clt"],
    prerequisites: ["probability"],
  },
  {
    id: "binomial-distribution",
    title: "Binomial Distribution",
    subtitle: "Discrete Probability for Binary Outcomes",
    description: "Model binary outcome probabilities using the binomial distribution, understanding its parameters and approximation to the normal distribution.",
    branch: "Statistics",
    level: 2,
    xp: 125,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "probability",
    children: [],
    unlocked: false,
    visible: true,
    x: 20,
    y: 310,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "binary",
    difficulty: "Intermediate",
    estimatedMinutes: 32,
    tags: ["binomial", "discrete", "binary"],
    prerequisites: ["probability"],
  },
  {
    id: "hypothesis-testing",
    title: "Hypothesis Testing",
    subtitle: "Null and Alternative Frameworks",
    description: "Master the logic of null hypothesis significance testing, Type I and Type II errors, and the decision-making process in statistical inference.",
    branch: "Statistics",
    level: 2,
    xp: 140,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "inferential-statistics",
    children: ["z-test", "t-test", "anova", "chi-square"],
    unlocked: false,
    visible: true,
    x: 40,
    y: 330,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "check-circle",
    difficulty: "Intermediate",
    estimatedMinutes: 40,
    tags: ["hypothesis", "testing", "nhst"],
    prerequisites: ["inferential-statistics"],
  },
  {
    id: "confidence-interval",
    title: "Confidence Interval",
    subtitle: "Estimating Population Parameters",
    description: "Construct and interpret confidence intervals for means, proportions, and differences to quantify the precision of sample estimates.",
    branch: "Statistics",
    level: 2,
    xp: 135,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "inferential-statistics",
    children: ["confidence-interval-mean", "confidence-interval-proportion"],
    unlocked: false,
    visible: true,
    x: 140,
    y: 320,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "target",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["confidence", "interval", "estimation"],
    prerequisites: ["inferential-statistics"],
  },
  {
    id: "effect-size",
    title: "Effect Size",
    subtitle: "Magnitude of Research Findings",
    description: "Calculate and interpret Cohen's d, eta-squared, and odds ratios to quantify the practical importance of research effects beyond p-values.",
    branch: "Statistics",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "inferential-statistics",
    children: ["cohens-d", "eta-squared", "odds-ratio"],
    unlocked: false,
    visible: true,
    x: 220,
    y: 300,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "maximize",
    difficulty: "Intermediate",
    estimatedMinutes: 42,
    tags: ["effect-size", "magnitude", "practical"],
    prerequisites: ["inferential-statistics"],
  },
  {
    id: "statistical-power",
    title: "Statistical Power",
    subtitle: "Probability of Detecting True Effects",
    description: "Calculate statistical power, understand the relationship between alpha, effect size, sample size, and beta error in research design.",
    branch: "Statistics",
    level: 2,
    xp: 155,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "inferential-statistics",
    children: ["power-analysis", "sample-size-calculation"],
    unlocked: false,
    visible: true,
    x: 300,
    y: 310,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "zap",
    difficulty: "Intermediate",
    estimatedMinutes: 45,
    tags: ["power", "beta", "detection"],
    prerequisites: ["inferential-statistics"],
  },
  {
    id: "pearson-correlation",
    title: "Pearson Correlation",
    subtitle: "Linear Relationship Coefficient",
    description: "Calculate and interpret Pearson's r, understand its assumptions, and recognize when linear correlation is appropriate for psychological data.",
    branch: "Statistics",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "correlation",
    children: ["coefficient-determination", "correlation-matrix"],
    unlocked: false,
    visible: true,
    x: 180,
    y: 320,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "trending-up",
    difficulty: "Intermediate",
    estimatedMinutes: 32,
    tags: ["pearson", "linear", "r-value"],
    prerequisites: ["correlation"],
  },
  {
    id: "spearman-correlation",
    title: "Spearman Correlation",
    subtitle: "Rank-Order Relationship Coefficient",
    description: "Apply Spearman's rank correlation for ordinal data and non-linear monotonic relationships common in psychological measurement.",
    branch: "Statistics",
    level: 2,
    xp: 115,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "correlation",
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: 330,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "list-ordered",
    difficulty: "Intermediate",
    estimatedMinutes: 28,
    tags: ["spearman", "rank", "ordinal"],
    prerequisites: ["correlation"],
  },
  {
    id: "partial-correlation",
    title: "Partial Correlation",
    subtitle: "Controlling for Third Variables",
    description: "Calculate partial correlations to assess the relationship between two variables while statistically controlling for the influence of confounding variables.",
    branch: "Statistics",
    level: 2,
    xp: 145,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "correlation",
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: 300,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "filter",
    difficulty: "Intermediate",
    estimatedMinutes: 38,
    tags: ["partial", "control", "confounding"],
    prerequisites: ["correlation"],
  },
  {
    id: "simple-regression",
    title: "Simple Regression",
    subtitle: "One Predictor Linear Model",
    description: "Build and interpret simple linear regression models with one predictor, understanding slope, intercept, and residual analysis.",
    branch: "Statistics",
    level: 2,
    xp: 130,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "regression",
    children: ["regression-assumptions", "residual-analysis"],
    unlocked: false,
    visible: true,
    x: 320,
    y: 320,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "trending-up",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["simple", "linear", "predictor"],
    prerequisites: ["regression"],
  },
  {
    id: "multiple-regression",
    title: "Multiple Regression",
    subtitle: "Predicting with Multiple Predictors",
    description: "Build and interpret multiple regression models, understanding multicollinearity, hierarchical entry, and assumption checking.",
    branch: "Statistics",
    level: 2,
    xp: 160,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "regression",
    children: ["multicollinearity", "hierarchical-regression"],
    unlocked: false,
    visible: true,
    x: 420,
    y: 310,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "git-merge",
    difficulty: "Advanced",
    estimatedMinutes: 48,
    tags: ["multiple", "predictors", "multivariate"],
    prerequisites: ["regression"],
  },
  {
    id: "logistic-regression",
    title: "Logistic Regression",
    subtitle: "Predicting Binary Outcomes",
    description: "Apply logistic regression to predict categorical outcomes, interpreting odds ratios and model fit statistics for dichotomous dependent variables.",
    branch: "Statistics",
    level: 2,
    xp: 170,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "regression",
    children: [],
    unlocked: false,
    visible: true,
    x: 500,
    y: 290,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "toggle-right",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["logistic", "binary", "odds"],
    prerequisites: ["regression"],
  },
  {
    id: "cronbach-alpha",
    title: "Cronbach's Alpha",
    subtitle: "Internal Consistency Coefficient",
    description: "Calculate and interpret Cronbach's alpha as a measure of internal consistency reliability for multi-item psychological scales.",
    branch: "Statistics",
    level: 2,
    xp: 125,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "reliability-statistics",
    children: ["item-total-correlation", "alpha-if-deleted"],
    unlocked: false,
    visible: true,
    x: -460,
    y: 300,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "align-center",
    difficulty: "Intermediate",
    estimatedMinutes: 32,
    tags: ["cronbach", "alpha", "internal"],
    prerequisites: ["reliability-statistics"],
  },
  {
    id: "test-retest-correlation",
    title: "Test-Retest Correlation",
    subtitle: "Temporal Stability Coefficient",
    description: "Calculate Pearson correlations between repeated measurements to assess the temporal stability of psychological instruments.",
    branch: "Statistics",
    level: 2,
    xp: 110,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "reliability-statistics",
    children: [],
    unlocked: false,
    visible: true,
    x: -380,
    y: 320,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "clock",
    difficulty: "Intermediate",
    estimatedMinutes: 28,
    tags: ["test-retest", "stability", "temporal"],
    prerequisites: ["reliability-statistics"],
  },
  {
    id: "split-half-reliability",
    title: "Split-Half Reliability",
    subtitle: "Internal Consistency via Halves",
    description: "Apply split-half methods and Spearman-Brown correction to estimate the reliability of psychological measures from a single administration.",
    branch: "Statistics",
    level: 2,
    xp: 120,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "reliability-statistics",
    children: [],
    unlocked: false,
    visible: true,
    x: -300,
    y: 300,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "scissors",
    difficulty: "Intermediate",
    estimatedMinutes: 30,
    tags: ["split-half", "spearman-brown", "halves"],
    prerequisites: ["reliability-statistics"],
  },
  {
    id: "factor-analysis",
    title: "Factor Analysis",
    subtitle: "Dimensionality Reduction",
    description: "Conduct exploratory and confirmatory factor analysis to identify latent structures underlying observed psychological variables.",
    branch: "Statistics",
    level: 2,
    xp: 165,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "validity-statistics",
    children: ["exploratory-factor-analysis", "confirmatory-factor-analysis"],
    unlocked: false,
    visible: true,
    x: 440,
    y: 300,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "bar-chart-2",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["factor", "latent", "dimensionality"],
    prerequisites: ["validity-statistics"],
  },
  {
    id: "roc-analysis",
    title: "ROC Analysis",
    subtitle: "Receiver Operating Characteristic Curves",
    description: "Construct and interpret ROC curves to evaluate the diagnostic accuracy of psychological tests and screening instruments.",
    branch: "Statistics",
    level: 2,
    xp: 150,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "validity-statistics",
    children: ["auc-interpretation", "optimal-cutoff"],
    unlocked: false,
    visible: true,
    x: 540,
    y: 320,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "activity",
    difficulty: "Intermediate",
    estimatedMinutes: 42,
    tags: ["roc", "diagnostic", "accuracy"],
    prerequisites: ["validity-statistics"],
  },
  {
    id: "sensitivity-specificity",
    title: "Sensitivity and Specificity",
    subtitle: "Diagnostic Test Performance",
    description: "Calculate and interpret sensitivity, specificity, positive predictive value, and negative predictive value for psychological assessments.",
    branch: "Statistics",
    level: 2,
    xp: 135,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "validity-statistics",
    children: [],
    unlocked: false,
    visible: true,
    x: 620,
    y: 300,
    radius: 30,
    color: "#6EE7B7",
    glow: false,
    iconName: "shield",
    difficulty: "Intermediate",
    estimatedMinutes: 35,
    tags: ["sensitivity", "specificity", "diagnostic"],
    prerequisites: ["validity-statistics"],
  },
  {
    id: "mean",
    title: "Mean",
    subtitle: "Arithmetic Average",
    description: "Calculate the arithmetic mean and understand its properties, sensitivity to outliers, and appropriate use as a measure of central tendency.",
    branch: "Statistics",
    level: 3,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "central-tendency",
    children: [],
    unlocked: false,
    visible: true,
    x: -420,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "plus",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    tags: ["mean", "average", "arithmetic"],
    prerequisites: ["central-tendency"],
  },
  {
    id: "median",
    title: "Median",
    subtitle: "Middle Value of Ordered Data",
    description: "Determine the median for ordinal and interval data, understanding its robustness to outliers and when it outperforms the mean.",
    branch: "Statistics",
    level: 3,
    xp: 190,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "central-tendency",
    children: [],
    unlocked: false,
    visible: true,
    x: -360,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "minus",
    difficulty: "Advanced",
    estimatedMinutes: 18,
    tags: ["median", "middle", "robust"],
    prerequisites: ["central-tendency"],
  },
  {
    id: "mode",
    title: "Mode",
    subtitle: "Most Frequent Value",
    description: "Identify the mode for nominal, ordinal, and continuous data, understanding its use for categorical variables and multimodal distributions.",
    branch: "Statistics",
    level: 3,
    xp: 180,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "central-tendency",
    children: [],
    unlocked: false,
    visible: true,
    x: -300,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "hash",
    difficulty: "Advanced",
    estimatedMinutes: 15,
    tags: ["mode", "frequency", "nominal"],
    prerequisites: ["central-tendency"],
  },
  {
    id: "range",
    title: "Range",
    subtitle: "Simple Spread Measure",
    description: "Calculate the range as the simplest measure of variability, understanding its limitations and sensitivity to extreme values.",
    branch: "Statistics",
    level: 3,
    xp: 185,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 2,
    parent: "variability",
    children: [],
    unlocked: false,
    visible: true,
    x: -280,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "arrow-left-right",
    difficulty: "Advanced",
    estimatedMinutes: 15,
    tags: ["range", "spread", "simple"],
    prerequisites: ["variability"],
  },
  {
    id: "variance",
    title: "Variance",
    subtitle: "Average Squared Deviation",
    description: "Calculate population and sample variance, understanding degrees of freedom and why squared deviations are used to quantify spread.",
    branch: "Statistics",
    level: 3,
    xp: 210,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "variability",
    children: [],
    unlocked: false,
    visible: true,
    x: -220,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "sigma",
    difficulty: "Advanced",
    estimatedMinutes: 25,
    tags: ["variance", "squared", "deviation"],
    prerequisites: ["variability"],
  },
  {
    id: "standard-deviation",
    title: "Standard Deviation",
    subtitle: "Square Root of Variance",
    description: "Calculate and interpret standard deviation as the most widely used measure of variability, understanding its relationship to the normal distribution.",
    branch: "Statistics",
    level: 3,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "variability",
    children: [],
    unlocked: false,
    visible: true,
    x: -160,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "sigma",
    difficulty: "Advanced",
    estimatedMinutes: 28,
    tags: ["standard-deviation", "sd", "variability"],
    prerequisites: ["variability"],
  },
  {
    id: "z-scores",
    title: "Z-Scores",
    subtitle: "Standardized Deviation Scores",
    description: "Convert raw scores to z-scores to compare values from different distributions and identify extreme scores in psychological testing.",
    branch: "Statistics",
    level: 3,
    xp: 230,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "normal-distribution",
    children: [],
    unlocked: false,
    visible: true,
    x: -120,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "zap",
    difficulty: "Advanced",
    estimatedMinutes: 25,
    tags: ["z-score", "standardized", "comparison"],
    prerequisites: ["normal-distribution"],
  },
  {
    id: "percentiles",
    title: "Percentiles",
    subtitle: "Relative Standing in a Distribution",
    description: "Calculate and interpret percentiles, quartiles, and deciles to understand the relative position of scores within psychological distributions.",
    branch: "Statistics",
    level: 3,
    xp: 200,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "normal-distribution",
    children: [],
    unlocked: false,
    visible: true,
    x: -60,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "percent",
    difficulty: "Advanced",
    estimatedMinutes: 22,
    tags: ["percentile", "quartile", "standing"],
    prerequisites: ["normal-distribution"],
  },
  {
    id: "skewness-kurtosis",
    title: "Skewness and Kurtosis",
    subtitle: "Shape of the Distribution",
    description: "Measure and interpret skewness and kurtosis to assess departure from normality and select appropriate statistical procedures.",
    branch: "Statistics",
    level: 3,
    xp: 240,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "normal-distribution",
    children: [],
    unlocked: false,
    visible: true,
    x: 0,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "waves",
    difficulty: "Advanced",
    estimatedMinutes: 30,
    tags: ["skewness", "kurtosis", "shape"],
    prerequisites: ["normal-distribution"],
  },
  {
    id: "bayes-theorem",
    title: "Bayes' Theorem",
    subtitle: "Updating Beliefs with Evidence",
    description: "Apply Bayes' theorem to update prior probabilities with new evidence, understanding its role in diagnostic testing and decision-making.",
    branch: "Statistics",
    level: 3,
    xp: 260,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "probability-rules",
    children: [],
    unlocked: false,
    visible: true,
    x: -200,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "refresh-cw",
    difficulty: "Advanced",
    estimatedMinutes: 35,
    tags: ["bayes", "updating", "evidence"],
    prerequisites: ["probability-rules"],
  },
  {
    id: "conditional-probability",
    title: "Conditional Probability",
    subtitle: "Probability Given Prior Information",
    description: "Calculate conditional probabilities and understand independence, mutual exclusivity, and their implications for psychological inference.",
    branch: "Statistics",
    level: 3,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "probability-rules",
    children: [],
    unlocked: false,
    visible: true,
    x: -140,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "git-branch",
    difficulty: "Advanced",
    estimatedMinutes: 28,
    tags: ["conditional", "independence", "given"],
    prerequisites: ["probability-rules"],
  },
  {
    id: "central-limit-theorem",
    title: "Central Limit Theorem",
    subtitle: "Normal Approximation of Sample Means",
    description: "Understand how sample means approach a normal distribution regardless of population shape as sample size increases, enabling parametric inference.",
    branch: "Statistics",
    level: 3,
    xp: 250,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "sampling-distributions",
    children: [],
    unlocked: false,
    visible: true,
    x: -80,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "trending-up",
    difficulty: "Advanced",
    estimatedMinutes: 35,
    tags: ["clt", "approximation", "sample-size"],
    prerequisites: ["sampling-distributions"],
  },
  {
    id: "standard-error",
    title: "Standard Error",
    subtitle: "Variability of Sample Statistics",
    description: "Calculate standard error of the mean and other statistics, understanding how sample size reduces sampling variability and increases precision.",
    branch: "Statistics",
    level: 3,
    xp: 230,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "sampling-distributions",
    children: [],
    unlocked: false,
    visible: true,
    x: -20,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "minus",
    difficulty: "Advanced",
    estimatedMinutes: 28,
    tags: ["standard-error", "se", "precision"],
    prerequisites: ["sampling-distributions"],
  },
  {
    id: "z-test",
    title: "Z-Test",
    subtitle: "One-Sample and Two-Sample Tests",
    description: "Conduct z-tests for means and proportions when population variance is known, calculating test statistics and critical values.",
    branch: "Statistics",
    level: 3,
    xp: 240,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "hypothesis-testing",
    children: [],
    unlocked: false,
    visible: true,
    x: 20,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "zap",
    difficulty: "Advanced",
    estimatedMinutes: 35,
    tags: ["z-test", "known-variance", "parametric"],
    prerequisites: ["hypothesis-testing"],
  },
  {
    id: "t-test",
    title: "T-Test",
    subtitle: "One-Sample, Independent, and Paired",
    description: "Select and conduct appropriate t-tests for comparing means, understanding degrees of freedom and assumptions of the t-distribution.",
    branch: "Statistics",
    level: 3,
    xp: 260,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "hypothesis-testing",
    children: [],
    unlocked: false,
    visible: true,
    x: 80,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "t",
    difficulty: "Advanced",
    estimatedMinutes: 42,
    tags: ["t-test", "means", "comparison"],
    prerequisites: ["hypothesis-testing"],
  },
  {
    id: "anova",
    title: "ANOVA",
    subtitle: "Analysis of Variance",
    description: "Conduct one-way, factorial, and repeated measures ANOVA to compare means across multiple groups, interpreting F-ratios and post-hoc tests.",
    branch: "Statistics",
    level: 3,
    xp: 280,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "hypothesis-testing",
    children: [],
    unlocked: false,
    visible: true,
    x: 140,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "bar-chart-2",
    difficulty: "Advanced",
    estimatedMinutes: 50,
    tags: ["anova", "variance", "groups"],
    prerequisites: ["hypothesis-testing"],
  },
  {
    id: "chi-square",
    title: "Chi-Square",
    subtitle: "Tests of Independence and Goodness-of-Fit",
    description: "Apply chi-square tests for categorical data to test independence between variables and goodness-of-fit to theoretical distributions.",
    branch: "Statistics",
    level: 3,
    xp: 270,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "hypothesis-testing",
    children: [],
    unlocked: false,
    visible: true,
    x: 200,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "grid",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["chi-square", "categorical", "independence"],
    prerequisites: ["hypothesis-testing"],
  },
  {
    id: "confidence-interval-mean",
    title: "Confidence Interval for Mean",
    subtitle: "Estimating the Population Mean",
    description: "Construct confidence intervals for population means using z and t distributions, understanding the relationship between width and confidence level.",
    branch: "Statistics",
    level: 3,
    xp: 240,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "confidence-interval",
    children: [],
    unlocked: false,
    visible: true,
    x: 120,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "target",
    difficulty: "Advanced",
    estimatedMinutes: 30,
    tags: ["confidence-interval", "mean", "estimation"],
    prerequisites: ["confidence-interval"],
  },
  {
    id: "confidence-interval-proportion",
    title: "Confidence Interval for Proportion",
    subtitle: "Estimating Population Proportions",
    description: "Construct confidence intervals for population proportions, applying normal approximation and exact methods for binary outcomes.",
    branch: "Statistics",
    level: 3,
    xp: 250,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "confidence-interval",
    children: [],
    unlocked: false,
    visible: true,
    x: 180,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "percent",
    difficulty: "Advanced",
    estimatedMinutes: 32,
    tags: ["confidence-interval", "proportion", "binary"],
    prerequisites: ["confidence-interval"],
  },
  {
    id: "cohens-d",
    title: "Cohen's d",
    subtitle: "Standardized Mean Difference",
    description: "Calculate Cohen's d for comparing two means, interpreting small, medium, and large effect sizes in psychological research contexts.",
    branch: "Statistics",
    level: 3,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "effect-size",
    children: [],
    unlocked: false,
    visible: true,
    x: 240,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "maximize",
    difficulty: "Advanced",
    estimatedMinutes: 28,
    tags: ["cohens-d", "standardized", "difference"],
    prerequisites: ["effect-size"],
  },
  {
    id: "eta-squared",
    title: "Eta-Squared",
    subtitle: "Proportion of Variance Explained",
    description: "Calculate eta-squared and partial eta-squared as measures of effect size for ANOVA designs, interpreting the proportion of variance accounted for.",
    branch: "Statistics",
    level: 3,
    xp: 260,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "effect-size",
    children: [],
    unlocked: false,
    visible: true,
    x: 300,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "pie-chart",
    difficulty: "Advanced",
    estimatedMinutes: 35,
    tags: ["eta-squared", "variance", "anova"],
    prerequisites: ["effect-size"],
  },
  {
    id: "odds-ratio",
    title: "Odds Ratio",
    subtitle: "Effect Size for Categorical Outcomes",
    description: "Calculate and interpret odds ratios for categorical data, understanding their relationship to relative risk and logistic regression coefficients.",
    branch: "Statistics",
    level: 3,
    xp: 280,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "effect-size",
    children: [],
    unlocked: false,
    visible: true,
    x: 360,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "scale",
    difficulty: "Advanced",
    estimatedMinutes: 38,
    tags: ["odds-ratio", "categorical", "risk"],
    prerequisites: ["effect-size"],
  },
  {
    id: "power-analysis",
    title: "Power Analysis",
    subtitle: "Planning for Statistical Detection",
    description: "Conduct a priori and post-hoc power analyses using G*Power to determine required sample sizes and evaluate completed studies.",
    branch: "Statistics",
    level: 3,
    xp: 300,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "statistical-power",
    children: [],
    unlocked: false,
    visible: true,
    x: 320,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "zap",
    difficulty: "Advanced",
    estimatedMinutes: 45,
    tags: ["power-analysis", "planning", "gpower"],
    prerequisites: ["statistical-power"],
  },
  {
    id: "sample-size-calculation",
    title: "Sample Size Calculation",
    subtitle: "Determining N for Adequate Power",
    description: "Calculate required sample sizes for desired power, effect size, and alpha level across different statistical tests and research designs.",
    branch: "Statistics",
    level: 3,
    xp: 320,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "statistical-power",
    children: [],
    unlocked: false,
    visible: true,
    x: 400,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "users",
    difficulty: "Expert",
    estimatedMinutes: 50,
    tags: ["sample-size", "n-calculation", "planning"],
    prerequisites: ["statistical-power"],
  },
  {
    id: "coefficient-determination",
    title: "Coefficient of Determination",
    subtitle: "R-Squared and Variance Explained",
    description: "Interpret R-squared as the proportion of variance in the dependent variable explained by the predictor(s) in correlation and regression.",
    branch: "Statistics",
    level: 3,
    xp: 230,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "pearson-correlation",
    children: [],
    unlocked: false,
    visible: true,
    x: 160,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "percent",
    difficulty: "Advanced",
    estimatedMinutes: 25,
    tags: ["r-squared", "variance", "explained"],
    prerequisites: ["pearson-correlation"],
  },
  {
    id: "correlation-matrix",
    title: "Correlation Matrix",
    subtitle: "Multiple Variable Relationships",
    description: "Construct and interpret correlation matrices for multiple variables, identifying patterns of association in multivariate psychological data.",
    branch: "Statistics",
    level: 3,
    xp: 240,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "pearson-correlation",
    children: [],
    unlocked: false,
    visible: true,
    x: 220,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "grid",
    difficulty: "Advanced",
    estimatedMinutes: 30,
    tags: ["correlation-matrix", "multivariate", "patterns"],
    prerequisites: ["pearson-correlation"],
  },
  {
    id: "regression-assumptions",
    title: "Regression Assumptions",
    subtitle: "Linearity, Independence, Normality, and Homoscedasticity",
    description: "Evaluate the four core assumptions of linear regression and apply diagnostic procedures to verify model appropriateness.",
    branch: "Statistics",
    level: 3,
    xp: 250,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "simple-regression",
    children: [],
    unlocked: false,
    visible: true,
    x: 280,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "check-circle",
    difficulty: "Advanced",
    estimatedMinutes: 35,
    tags: ["assumptions", "linearity", "diagnostics"],
    prerequisites: ["simple-regression"],
  },
  {
    id: "residual-analysis",
    title: "Residual Analysis",
    subtitle: "Examining Model Fit",
    description: "Analyze residuals to assess model fit, identify outliers, and detect violations of regression assumptions in psychological data.",
    branch: "Statistics",
    level: 3,
    xp: 260,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "simple-regression",
    children: [],
    unlocked: false,
    visible: true,
    x: 340,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "activity",
    difficulty: "Advanced",
    estimatedMinutes: 38,
    tags: ["residuals", "fit", "outliers"],
    prerequisites: ["simple-regression"],
  },
  {
    id: "multicollinearity",
    title: "Multicollinearity",
    subtitle: "Correlated Predictor Problem",
    description: "Detect and address multicollinearity in multiple regression, understanding variance inflation factors and remedial strategies.",
    branch: "Statistics",
    level: 3,
    xp: 280,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "multiple-regression",
    children: [],
    unlocked: false,
    visible: true,
    x: 400,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "alert-triangle",
    difficulty: "Advanced",
    estimatedMinutes: 42,
    tags: ["multicollinearity", "vif", "predictors"],
    prerequisites: ["multiple-regression"],
  },
  {
    id: "hierarchical-regression",
    title: "Hierarchical Regression",
    subtitle: "Sequential Predictor Entry",
    description: "Implement hierarchical regression to examine the incremental contribution of predictor blocks and test theoretical models.",
    branch: "Statistics",
    level: 3,
    xp: 300,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 4,
    parent: "multiple-regression",
    children: [],
    unlocked: false,
    visible: true,
    x: 460,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "layers",
    difficulty: "Expert",
    estimatedMinutes: 48,
    tags: ["hierarchical", "sequential", "blocks"],
    prerequisites: ["multiple-regression"],
  },
  {
    id: "item-total-correlation",
    title: "Item-Total Correlation",
    subtitle: "Item Quality in Scales",
    description: "Calculate item-total correlations to evaluate the contribution of individual items to the total score of psychological scales.",
    branch: "Statistics",
    level: 3,
    xp: 220,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "cronbach-alpha",
    children: [],
    unlocked: false,
    visible: true,
    x: -500,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "link",
    difficulty: "Advanced",
    estimatedMinutes: 28,
    tags: ["item-total", "correlation", "scale"],
    prerequisites: ["cronbach-alpha"],
  },
  {
    id: "alpha-if-deleted",
    title: "Alpha If Item Deleted",
    subtitle: "Improving Scale Reliability",
    description: "Evaluate how removing individual items affects overall Cronbach's alpha to refine and optimize psychological measurement instruments.",
    branch: "Statistics",
    level: 3,
    xp: 230,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "cronbach-alpha",
    children: [],
    unlocked: false,
    visible: true,
    x: -440,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "trash-2",
    difficulty: "Advanced",
    estimatedMinutes: 30,
    tags: ["alpha-deleted", "refinement", "optimization"],
    prerequisites: ["cronbach-alpha"],
  },
  {
    id: "exploratory-factor-analysis",
    title: "Exploratory Factor Analysis",
    subtitle: "Discovering Latent Structures",
    description: "Conduct exploratory factor analysis to discover the underlying factor structure of psychological measures without a priori hypotheses.",
    branch: "Statistics",
    level: 3,
    xp: 320,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "factor-analysis",
    children: [],
    unlocked: false,
    visible: true,
    x: 420,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "search",
    difficulty: "Expert",
    estimatedMinutes: 55,
    tags: ["efa", "exploratory", "discovery"],
    prerequisites: ["factor-analysis"],
  },
  {
    id: "confirmatory-factor-analysis",
    title: "Confirmatory Factor Analysis",
    subtitle: "Testing Hypothesized Structures",
    description: "Use confirmatory factor analysis to test hypothesized factor models, evaluating model fit indices and measurement invariance.",
    branch: "Statistics",
    level: 3,
    xp: 420,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 5,
    parent: "factor-analysis",
    children: [],
    unlocked: false,
    visible: true,
    x: 480,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "check-circle",
    difficulty: "Expert",
    estimatedMinutes: 60,
    tags: ["cfa", "confirmatory", "model-fit"],
    prerequisites: ["factor-analysis"],
  },
  {
    id: "auc-interpretation",
    title: "AUC Interpretation",
    subtitle: "Area Under the Curve",
    description: "Interpret the area under the ROC curve as a global measure of diagnostic accuracy, understanding benchmarks for excellent, good, and poor tests.",
    branch: "Statistics",
    level: 3,
    xp: 240,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "roc-analysis",
    children: [],
    unlocked: false,
    visible: true,
    x: 520,
    y: 460,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "activity",
    difficulty: "Advanced",
    estimatedMinutes: 30,
    tags: ["auc", "accuracy", "interpretation"],
    prerequisites: ["roc-analysis"],
  },
  {
    id: "optimal-cutoff",
    title: "Optimal Cutoff",
    subtitle: "Threshold Selection for Diagnosis",
    description: "Determine optimal cutoff scores for diagnostic tests using Youden's index and cost-benefit analysis to balance sensitivity and specificity.",
    branch: "Statistics",
    level: 3,
    xp: 260,
    status: "locked",
    progress: 0,
    completed: 0,
    total: 3,
    parent: "roc-analysis",
    children: [],
    unlocked: false,
    visible: true,
    x: 580,
    y: 480,
    radius: 26,
    color: "#A7F3D0",
    glow: false,
    iconName: "scissors",
    difficulty: "Advanced",
    estimatedMinutes: 35,
    tags: ["cutoff", "threshold", "youden"],
    prerequisites: ["roc-analysis"],
  },
];
